server:
  publicAddress: http://localhost:3500
  publicDomain: localhost:3500
  port: 3500
  listen: "0.0.0.0"

db:
  type: "sqlite"
  database: "alfa.db"

auth:
  enabled: true
  openIdConfigurationURL: http://localhost:3700/.well-known/openid-configuration
  callbackURL: http://localhost:3550/api/auth/callback
  clientId: alfa-wallet
  tokenEndpointAuthMethod: private_key_jwt
  privateKeyJwk:
    kty: EC
    x: TNroQXAH5gSedz9Wh5Gwb36PqPbQcUUhDjoaOkuOVP4
    y: oxlGyXlgptnf93RBtGOG1TXBo3_xC8nJyNXMylJ3CHs
    crv: P-256
    d: wTwrfUl_atP34TR61hOAjreRQwxfISFic13zvVzkvT8
    kid: alfa-wallet-key-1767782612424
    alg: ES256
    use: sig
  redirectURL: http://localhost:3550/

initKeys:
  - id: key-0
    type: EdDSA
    default: true

runtime:
  title: Alfa
  color: "#3B8BF6"
  acceptUnauthenticatedCredentialRequests: true
  issueMobileCredentials: true
  issueDebugCredentials: true

issuance:
  dcp:
    - credentialType:
        - ExampleCredential
      issuerId: did:web:localhost%3A3400
      preAuthorizedCode: 386527fd21960fd8bd3aa0208c9275a4437fde1bdae9469daaf91fb7cace67d827ff152e5f89c02ccdbde1766387feb2

trustAnchors:
  - id: did:web:localhost%3A3400
    credentialTypes:
      - ExampleCredential
      - alfa:ExampleCredential
      - http://localhost:3400/credentials/ExampleCredential

didServices:
  - id: did:web:localhost%3A3500#control-plane
    type: connector
    serviceEndpoint: http://localhost:3501/

did:
  method: "did:web:"

audit:
  logExecute: true
