server:
  publicAddress: http://localhost:3601
  publicDomain: localhost:3601
  port: 3601
  listen: "0.0.0.0"

db:
  type: sqlite
  database: "bravo.db"

auth:
  enabled: true
  openIdConfigurationURL: http://localhost:3700/.well-known/openid-configuration
  callbackURL: http://localhost:3651/api/auth/callback
  clientId: bravo-control-plane
  tokenEndpointAuthMethod: private_key_jwt
  privateKeyJwk:
    kty: EC
    x: FEoIkUEOd9kvrv62_5ZSHPuMZyeAsgqJjPtmUiB_CyM
    y: 8rQTOzJT6PnvTyw-GWz6DGAF_S3oMgFGiE-MjBloppg
    crv: P-256
    d: 48etwEPjYNSkChrRAZgZr9BvTleF217LXBmyk7oOPgs
    kid: bravo-control-plane-key-1767782797384
    alg: ES256
    use: sig
  redirectURL: http://localhost:3651/

runtime:
  controlPlaneInteractions: automatic
  color: "#3B8BF6"

registry:
  useRegistry: true
  registryIntervalInMilliseconds: 30000

iam:
  type: tsg
  didId: did:web:localhost%3A3600
  issuerFilter: did:web:localhost%3A3400
  typeFilter: ExampleCredential
  walletUrl: http://localhost:3600
  siopUrl: http://localhost:3600/management/dcp/holder/token
  verifyUrl: http://localhost:3600/management/dcp/verifier/verify

initCatalog:
  participantId: did:web:localhost%3A3600
  creator: did:web:localhost%3A3600
  publisher: did:web:localhost%3A3600
  title: Bravo
  description: Bravo connector

audit:
  logExecute: true
