dataspacetck.callback.address=http://localhost:8080
dataspacetck.did.holder=did:web:localhost%3A32491
dataspacetck.launcher=org.eclipse.dataspacetck.dcp.system.DcpSystemLauncher
dataspacetck.credentials.correlation.id=my-correlation-id