stages:
  - build
  - test
  - package
  - release
  - check

variables:
  RULES_CHANGES_PATH: "**/*"

.base-rules:
  image: node:24
  variables:
    # Corepack integrity checks are often failing in CI, so we disable them
    COREPACK_INTEGRITY_KEYS: "0"
  before_script:
    - corepack enable pnpm
    - pnpm config set store-dir .pnpm-store
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

openapi:
  extends: .base-rules
  stage: test
  script:
    - pnpm install --frozen-lockfile
    - pnpm --filter "./libs/*" build
    - pnpm -r swagger
    - git diff --exit-code
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

config_docs:
  extends: .base-rules
  stage: test
  script:
    - pnpm install --frozen-lockfile
    - pnpm --filter "./libs/*" build
    - pnpm -r configDocs
    - git diff --exit-code
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
lint:
  extends: .base-rules
  stage: test
  script:
    - pnpm install --frozen-lockfile
    - pnpm prettier --check . && pnpm eslint --quiet
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

renovate:
  stage: check
  image: ghcr.io/renovatebot/renovate:42.84.2
  needs: []
  script:
    - renovate
  rules:
    - if: '$RENOVATE_CHECK == "true" && $CI_COMMIT_BRANCH == "main"'
  variables:
    RENOVATE_CONFIG_FILE: .gitlab/renovate-config.cjs

renovate_test:
  stage: check
  image: ghcr.io/renovatebot/renovate:42.84.2
  needs: []
  script:
    - renovate-config-validator
    - renovate --dry-run=full
  variables:
    RENOVATE_CONFIG_FILE: .gitlab/renovate-config.cjs
  rules:
    - changes:
        - .gitlab/renovate-config.cjs
        - .gitlab/renovate.json
        - .gitlab-ci.yml
      if: $CI_PIPELINE_SOURCE == "merge_request_event"

release:
  image: node:24
  tags:
    - saas-linux-large-amd64
  stage: release
  needs: []
  variables:
    GIT_EMAIL: semantic-release-bot@dataspac.es
    GIT_NAME: semantic-release
    GIT_DEPTH: 1000
    TITLE: TNO Security Gateway
  before_script:
    # TODO workaround for: https://github.com/postmanlabs/postman-code-generators/issues/772 (closed but not fixed)
    - mv /usr/local/bin/yarn /usr/local/bin/yarn.bak

  script:
    - cd release/
    - npm install
    - NEW_VERSION=$(node version.js)
    - OLD_VERSION=$(node version.js --current)
    - echo "NEW_VERSION=$NEW_VERSION" >> ../build.env
    - echo "OLD_VERSION=$OLD_VERSION" >> ../build.env
    - echo "Old Version:$OLD_VERSION, New Version:$NEW_VERSION"
    - VERSION=v$NEW_VERSION
    - echo $VERSION
    - cd ../website/
    - npm install
    - npm run docusaurus clean-api-docs all
    - npm run docusaurus gen-api-docs all
    - npm run docusaurus docs:version $VERSION
    - npm run build:gitlab
    - mv public ../public
    - git add .
    - cd ..
    - node ./release/release.js
  artifacts:
    reports:
      dotenv: build.env
    paths:
      - public
  rules:
    - if: '$RELEASE_NOW == "true" && $CI_COMMIT_BRANCH == "main"'

update_deployments:
  stage: release
  image: node:24
  needs:
    - job: release
      artifacts: true
  variables:
    GIT_EMAIL: semantic-release-bot@dataspac.es
    GIT_NAME: semantic-release
  script:
    - git clone https://semantic-release:${DEPLOYMENTS_TOKEN}@${CI_SERVER_HOST}/tno-tsg/deployments.git
    - cd deployments
    - 'find . -type f -name "*.yaml" -exec sed -i -e "s/v${OLD_VERSION}/v${NEW_VERSION}/g" -e "s/\([^v]\)${OLD_VERSION}/\1${NEW_VERSION}/g" {} +'
    - git config user.email "${GIT_EMAIL}"
    - git config user.name "${GIT_NAME}"
    - git add .
    - 'git commit -m "chore: release v${NEW_VERSION}"'
    - git push origin master
  rules:
    - if: '$RELEASE_NOW == "true" && $CI_COMMIT_BRANCH == "main"'

test_release:
  image: node:24
  stage: release
  needs: []
  before_script:
    - mv /usr/local/bin/yarn /usr/local/bin/yarn.bak
  script:
    - cd release/
    - npm install
    - VERSION=v$(node version.js)
    - echo $VERSION
    - cd ..
    - node ./release/release.js debug
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - local: apps/apps.gitlab-ci.yml
  - local: website/docs.gitlab-ci.yml
  - local: libs/libs.gitlab-ci.yml
  - local: tools/tools.gitlab-ci.yml
  - local: helm-charts/helm.gitlab-ci.yml

container_scanning:
  parallel:
    matrix:
      - CS_IMAGE: "${CI_REGISTRY_IMAGE}/wallet:${CI_COMMIT_REF_SLUG}"
      - CS_IMAGE: "${CI_REGISTRY_IMAGE}/control-plane:${CI_COMMIT_REF_SLUG}"
      - CS_IMAGE: "${CI_REGISTRY_IMAGE}/http-data-plane:${CI_COMMIT_REF_SLUG}"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
