stages:
  - build
  - test
  - package
  - release
  - check

variables:
  RULES_CHANGES_PATH: "**/*"

.base-rules:
  image: node:22
  before_script:
    - corepack enable
    - corepack prepare pnpm@9.15.0 --activate
    - pnpm config set store-dir .pnpm-store
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

lint:
  extends: .base-rules
  stage: test
  script:
    - pnpm install --frozen-lockfile
    - npx prettier@^3.4.1 --check . && pnpm eslint --quiet
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

renovate:
  stage: check
  image: ghcr.io/renovatebot/renovate:39.90.5
  needs: []
  script:
    - renovate
  rules:
    - if: '$RENOVATE_CHECK == "true" && $CI_COMMIT_BRANCH == "main"'
  variables:
    RENOVATE_CONFIG_FILE: .gitlab/renovate-config.cjs

release:
  image: node:22
  tags:
    - saas-linux-large-amd64
  stage: release
  needs: []
  variables:
    GIT_EMAIL: semantic-release-bot@dataspac.es
    GIT_NAME: semantic-release
    GIT_DEPTH: 1000
    TITLE: TNO Security Gateway
  before_script:
    # TODO workaround for: https://github.com/postmanlabs/postman-code-generators/issues/772
    - mv /usr/local/bin/yarn /usr/local/bin/yarn.bak
  script:
    - cd release/
    - npm install
    - VERSION=v$(node version.js)
    - echo $VERSION
    - cd ../website/
    - npm install
    - npm run docusaurus clean-api-docs all
    - npm run docusaurus gen-api-docs all
    - npm run docusaurus docs:version $VERSION
    - npm run build:gitlab
    - mv public ../public
    - git add .
    - cd ..
    - node ./release/release.js
  artifacts:
    paths:
      - public
  rules:
    - if: '$RELEASE_NOW == "true" && $CI_COMMIT_BRANCH == "main"'

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - local: apps/apps.gitlab-ci.yml
  - local: website/docs.gitlab-ci.yml
  - local: libs/libs.gitlab-ci.yml
  - local: tools/tools.gitlab-ci.yml
  - local: helm-charts/helm.gitlab-ci.yml

container_scanning:
  parallel:
    matrix:
      - CS_IMAGE: "${CI_REGISTRY_IMAGE}/wallet:${CI_COMMIT_REF_SLUG}"
      - CS_IMAGE: "${CI_REGISTRY_IMAGE}/control-plane:${CI_COMMIT_REF_SLUG}"
      - CS_IMAGE: "${CI_REGISTRY_IMAGE}/http-data-plane:${CI_COMMIT_REF_SLUG}"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
