image: node:22

stages:
  - build
  - test
  - release

variables:
  RULES_CHANGES_PATH: "**/*"

.base-rules:
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir .pnpm-store

.build:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
      changes:
        - "*/$APP*/**/*"
        - "libs/common*/**/*"
        - .gitlab-ci.yml
  tags:
    - saas-linux-medium-amd64
  script:
    - pnpm install --frozen-lockfile
    - pnpm build --filter $APP*
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store

.test:
  stage: test
  tags:
    - saas-linux-medium-amd64
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
      changes:
        - "apps/$APP-api/**/*"
        - "libs/$APP-dtos/**/*"
        - "libs/common-dsp/**/*"
        - "libs/common-utils/**/*"
        - .gitlab-ci.yml
  script:
    - pnpm install --frozen-lockfile
    - pnpm build --filter $APP*
    - NODE_OPTIONS="--experimental-vm-modules" pnpm test:ci --filter $APP*
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    reports:
      junit:
        - apps/$APP-api/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: apps/$APP-api/coverage/cobertura-coverage.xml

.release:
  stage: release
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - saas-linux-medium-amd64
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      --build-arg BUILD_SHA=${CI_COMMIT_SHORT_SHA}
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile-$APP"
      --destination "${CI_REGISTRY_IMAGE}/$APP:${CI_COMMIT_REF_SLUG}"
  only:
    refs:
      - main
      - tags

wallet-build:
  extends:
    - .build
  variables:
    APP: wallet

wallet-test:
  extends:
    - .test
  variables:
    APP: wallet
wallet-release:
  extends: .release
  variables:
    APP: wallet

control-plane-build:
  extends:
    - .build
  variables:
    APP: control-plane

control-plane-test:
  extends:
    - .test
  variables:
    APP: control-plane
control-plane-release:
  extends: .release
  variables:
    APP: control-plane

http-data-plane-build:
  extends:
    - .build
  variables:
    APP: http-data-plane

http-data-plane-test:
  extends:
    - .test
  variables:
    APP: http-data-plane

http-data-plane-release:
  extends: .release
  variables:
    APP: http-data-plane

publish:
  extends:
    - .base-rules
  stage: release
  script:
    - pnpm install --frozen-lockfile
    - npx semantic-release -e "@semantic-release/gitlab-config" -e semantic-release-monorepo -p "@semantic-release/commit-analyzer" -p "@semantic-release/release-notes-generator" -p "@semantic-release/gitlab"
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  rules:
    - if: '$RELEASE_NOW == "true"'

include:
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - local: helm-charts/.gitlab-ci.yml

container_scanning:
  parallel:
    matrix:
      - CS_IMAGE: "${CI_REGISTRY_IMAGE}/wallet:${CI_COMMIT_REF_SLUG}"
      - CS_IMAGE: "${CI_REGISTRY_IMAGE}/control-plane:${CI_COMMIT_REF_SLUG}"
      - CS_IMAGE: "${CI_REGISTRY_IMAGE}/http-data-plane:${CI_COMMIT_REF_SLUG}"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
