db:
  type: sqlite
  database: control-plane

server:
  port: '3000'
  listen: '0.0.0.0'
  publicDomain: localhost:3000
  publicAddress: http://localhost:3000

iam:
  type: tsg
  didId: did:web:localhost%3A3001
  tokenUrl: http://localhost:3001/api/auth/login
  presentationUrl: http://localhost:3001/api/presentations
  validationUrl: http://localhost:3001/api/presentations/validate
  clientId: client
  clientSecret: secret
  credentialId: did:web:localhost%3A3001#00000000-0000-0000-0000-000000000000
  validations:
  - valid

users:
  - username: admin
    password: $2a$12$/1aqZWSslSi8E556dpChNOxOyEv3hPA.k8asnRk9iIN2bxH6VGUE6

initCatalog:
  creator: did:web:localhost%3A3001
  publisher: did:web:localhost%3A3001
  title: TSG Test Connector
  description: TSG Test Connector testing Data Space Protocol support