FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN corepack prepare pnpm@9.15.0 --activate

FROM node:22 AS build
WORKDIR /app 
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN corepack prepare pnpm@9.15.0 --activate
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/control-plane-api/package.json apps/control-plane-api/
COPY apps/control-plane-ui/package.json apps/control-plane-ui/
COPY libs/common-api/package.json libs/common-api/
COPY libs/common-dsp/package.json libs/common-dsp/
COPY libs/common-dtos/package.json libs/common-dtos/
COPY libs/common-ui/package.json libs/common-ui/
COPY libs/control-plane-dtos/package.json libs/control-plane-dtos/
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY apps apps
COPY libs libs
RUN pnpm run --filter "common-dsp" build
RUN pnpm run --filter "control-plane-dtos" build
RUN pnpm run --filter "common-dtos" build
RUN pnpm run --filter "common-api" build
ARG TSG_MODE=development
ARG TSG_VERSION=0.0.0
ARG TSG_STATIC_MODE=${TSG_MODE}
ARG TSG_STATIC_VERSION=${TSG_VERSION}
RUN pnpm run --filter "./libs/common*" -r build 
RUN pnpm run --filter "./libs/control-plane*" --parallel -r build
RUN pnpm run --filter "./apps/control-plane*" --parallel -r build 
RUN pnpm deploy --filter control-plane-api --prod /prod/control-plane-api
COPY apps/control-plane-api/config.yaml /prod/control-plane-api
RUN pnpm deploy --filter control-plane-ui --prod /prod/control-plane-ui

FROM base AS deploy 
WORKDIR /app
COPY --from=build /prod/control-plane-api .
COPY --from=build /prod/control-plane-ui/dist control-plane-ui/
EXPOSE 3000
ARG TSG_MODE=development
ARG TSG_VERSION=0.0.0
ENV TSG_MODE=${TSG_MODE}
ENV TSG_VERSION=${TSG_VERSION}
ENV NODE_OPTIONS="--max-old-space-size=300"
ENV EMBEDDED_FRONTEND="/app/control-plane-ui"
CMD ["npm", "run", "start"]
