FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS build
WORKDIR /app 
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/http-data-plane-api/package.json apps/http-data-plane-api/
COPY apps/http-data-plane-ui/package.json apps/http-data-plane-ui/
COPY libs/common-dsp/package.json libs/common-dsp/
COPY libs/common-dtos/package.json libs/common-dtos/
COPY libs/common-ui/package.json libs/common-ui/
COPY libs/control-plane-dtos/package.json libs/control-plane-dtos/
COPY libs/http-data-plane-dtos/package.json libs/http-data-plane-dtos/
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY apps apps
COPY libs libs 
RUN pnpm run --filter "common-dsp" build 
RUN pnpm run --filter "control-plane-dtos" build 
ARG TSG_MODE=development
ARG TSG_VERSION=0.0.0
ARG TSG_STATIC_MODE=${TSG_MODE}
ARG TSG_STATIC_VERSION=${TSG_VERSION}
RUN pnpm run --filter "./libs/common*" -r build 
RUN pnpm run --filter "./libs/http-data-plane*" --parallel -r build
RUN pnpm run --filter "./apps/http-data-plane*" --parallel -r build
RUN pnpm deploy --filter http-data-plane-api --prod /prod/http-data-plane-api
COPY apps/http-data-plane-api/config.yaml /prod/http-data-plane-api
RUN pnpm deploy --filter http-data-plane-ui --prod /prod/http-data-plane-ui

FROM base AS deploy 
WORKDIR /app
COPY --from=build /prod/http-data-plane-api .
COPY --from=build /prod/http-data-plane-ui/dist http-data-plane-ui/
EXPOSE 3000
ARG TSG_MODE=development
ARG TSG_VERSION=0.0.0
ENV TSG_MODE=${TSG_MODE}
ENV TSG_VERSION=${TSG_VERSION}
ENV NODE_OPTIONS="--max-old-space-size=300"
ENV EMBEDDED_FRONTEND="/app/http-data-plane-ui"
CMD ["npm", "run", "start"]