# Build image
FROM node:24-slim AS build
# Install pnpm
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
WORKDIR /app
RUN corepack enable pnpm

# Fetch and install dependencies
COPY patches patches
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm fetch
COPY libs libs
COPY apps apps
RUN pnpm install --frozen-lockfile --offline -r

# Set build arguments, TSG_STATIC used during compilation of the UI 
ARG TSG_MODE=development 
ARG TSG_VERSION=0.0.0
ARG TSG_STATIC_MODE=${TSG_MODE}
ARG TSG_STATIC_VERSION=${TSG_VERSION}

# Build all libs
RUN pnpm run --filter "./libs/*" -r build

# Build API and UI
RUN pnpm run --filter "./apps/http-data-plane*" --parallel -r build

# Package production dependencies and build of API
RUN pnpm deploy --legacy --filter http-data-plane-api --prod /app/prod/http-data-plane-api


# Deploy image
FROM node:24-slim AS deploy
WORKDIR /app
# Run as non-root user
RUN chown -R node:node /app
USER node

# Copy API and UI
COPY --chown=node:node --from=build /app/prod/http-data-plane-api .
COPY --chown=node:node --from=build /app/apps/http-data-plane-ui/dist http-data-plane-ui/

# Set exposed port and enviornment variables. TSG_MODE and TSG_VERSION are used at runtime by the API
EXPOSE 3000
ARG TSG_MODE=development 
ARG TSG_VERSION=0.0.0
ENV TSG_MODE=${TSG_MODE}
ENV TSG_VERSION=${TSG_VERSION}
ENV NODE_OPTIONS="--max-old-space-size=300"
ENV EMBEDDED_FRONTEND="/app/http-data-plane-ui"
CMD ["node", "./dist/app.js"]