FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS build
WORKDIR /app 
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/wallet-api/package.json apps/wallet-api/
COPY apps/wallet-ui/package.json apps/wallet-ui/
COPY libs/common-dsp/package.json libs/common-dsp/
COPY libs/common-dtos/package.json libs/common-dtos/
COPY libs/common-ui/package.json libs/common-ui/
COPY libs/wallet-dtos/package.json libs/wallet-dtos/
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY apps apps
COPY libs libs 
RUN pnpm run --filter "./libs/common-dsp" build 
ARG TSG_MODE=development
ARG TSG_VERSION=0.0.0
ARG TSG_STATIC_MODE=${TSG_MODE}
ARG TSG_STATIC_VERSION=${TSG_VERSION}
RUN pnpm run --filter "./libs/common*" -r build 
RUN pnpm run --filter "./libs/wallet*" --parallel -r build
RUN pnpm run --filter "./apps/wallet*" --parallel -r build
RUN pnpm deploy --filter wallet-api --prod /prod/wallet-api
COPY apps/wallet-api/config.yaml /prod/wallet-api
RUN pnpm deploy --filter wallet-ui --prod /prod/wallet-ui

FROM base AS deploy 
WORKDIR /app
COPY --from=build /prod/wallet-api .
COPY --from=build /prod/wallet-ui/dist wallet-ui/
EXPOSE 3000
ARG TSG_MODE=development
ARG TSG_VERSION=0.0.0
ENV TSG_MODE=${TSG_MODE}
ENV TSG_VERSION=${TSG_VERSION}
ENV NODE_OPTIONS="--max-old-space-size=300"
ENV EMBEDDED_FRONTEND="/app/wallet-ui"
CMD ["npm", "run", "start"]
