FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN corepack prepare pnpm@9.15.0 --activate

FROM base AS build
WORKDIR /app 
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/sso-bridge-api/package.json apps/sso-bridge-api/
COPY apps/sso-bridge-ui/package.json apps/sso-bridge-ui/
COPY libs/common-dsp/package.json libs/common-dsp/
COPY libs/common-dtos/package.json libs/common-dtos/
COPY libs/common-api/package.json libs/common-api/
COPY libs/common-ui/package.json libs/common-ui/
COPY libs/sso-bridge-dtos/package.json libs/sso-bridge-dtos/
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY apps apps
COPY libs libs 
RUN pnpm run --filter "common-api" build 
ARG TSG_MODE=development
ARG TSG_VERSION=0.0.0
ARG TSG_STATIC_MODE=${TSG_MODE}
ARG TSG_STATIC_VERSION=${TSG_VERSION}
RUN pnpm run --filter "./libs/common-*" build 
RUN pnpm run --filter "./libs/sso-bridge*" --parallel -r build
RUN pnpm run --filter "./apps/sso-bridge-*" --parallel -r build
RUN pnpm deploy --filter sso-bridge-api --prod /prod/sso-bridge-api
COPY apps/sso-bridge-api/config.yaml /prod/sso-bridge-api
RUN pnpm deploy --filter sso-bridge-ui --prod /prod/sso-bridge-ui

FROM base AS deploy 
WORKDIR /app
COPY --from=build /prod/sso-bridge-api .
COPY --from=build /prod/sso-bridge-ui/dist sso-bridge-ui/
EXPOSE 3000
ARG TSG_MODE=development
ARG TSG_VERSION=0.0.0
ENV TSG_MODE=${TSG_MODE}
ENV TSG_VERSION=${TSG_VERSION}
ENV NODE_OPTIONS="--max-old-space-size=300"
ENV EMBEDDED_FRONTEND="/app/sso-bridge-ui"
CMD ["npm", "run", "start"]