FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
RUN corepack prepare pnpm@9.15.0 --activate

FROM base AS build
WORKDIR /app 
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/oauth-server-api/package.json apps/oauth-server-api/
COPY apps/oauth-server-ui/package.json apps/oauth-server-ui/
COPY libs/common-dsp/package.json libs/common-dsp/
COPY libs/common-dtos/package.json libs/common-dtos/
COPY libs/common-api/package.json libs/common-api/
COPY libs/common-ui/package.json libs/common-ui/
COPY libs/oauth-server-dtos/package.json libs/oauth-server-dtos/
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY apps apps
COPY libs libs 
RUN pnpm run --filter "common-api" build 
ARG TSG_MODE=development
ARG TSG_VERSION=0.0.0
ARG TSG_STATIC_MODE=${TSG_MODE}
ARG TSG_STATIC_VERSION=${TSG_VERSION}
RUN pnpm run --filter "./libs/common-*" build 
RUN pnpm run --filter "./libs/oauth-server*" --parallel -r build
RUN pnpm run --filter "./apps/oauth-server-*" --parallel -r build
RUN pnpm deploy --filter oauth-server-api --prod /prod/oauth-server-api
COPY apps/oauth-server-api/config.yaml /prod/oauth-server-api
RUN pnpm deploy --filter oauth-server-ui --prod /prod/oauth-server-ui

FROM base AS deploy 
WORKDIR /app
COPY --from=build /prod/oauth-server-api .
COPY --from=build /prod/oauth-server-ui/dist oauth-server-ui/
EXPOSE 3000
ARG TSG_MODE=development
ARG TSG_VERSION=0.0.0
ENV TSG_MODE=${TSG_MODE}
ENV TSG_VERSION=${TSG_VERSION}
ENV NODE_OPTIONS="--max-old-space-size=300"
ENV EMBEDDED_FRONTEND="/app/oauth-server-ui"
CMD ["npm", "run", "start"]