server:
  port: 3000
  listen: '0.0.0.0'
  publicDomain: localhost:3000

initClients:
  - id: admin
    secret: test
    email: noreply@dataspac.es
    roles:
      - view_all_credentials
      - manage_all_credentials
      - manage_keys
      - manage_clients
      - view_presentations
  - id: connector
    secret: test
    email: noreply@dataspac.es
    roles:
      - view_presentations
initKeys:
  - id: key-0
    type: EdDSA
    # default: true
  - id: key-1
    type: ES384
    default: true

initCredentials:
  - context:
      - https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework
    id: gaiax
    credentialSubject:
      id: did:web:localhost%3A3000
      gx:legalName: Stichting Maastricht Radiation Oncology "Maastro-Clinic"
      gx:registrationNumber:
        gx:registrationNumberType: vatID
        gx:registrationNumberNumber: NL004210104B01
      gx:headquarterAddress:
        gx:addressCountryCode: NL
        gx:addressCode: NL-LI
        gx:streetAddress: Dr Tanslaan 12
        gx:postalCode: 6229ET
      gx:legalAddress:
        gx:addressCountryCode: NL
        gx:addressCode: NL-LI
        gx:streetAddress: Dr Tanslaan 12
        gx:postalCode: 6229ET
      gx:termsAndConditions: 70c1d713215f95191a11d38fe2341faed27d19e083917bc8732ca4fea4976700

  - id: scsn
    context:
      - http://localhost:3000/context/SCSN
    type:
      - SCSNCredential
    credentialSubject:
      id: did:web:localhost%3A3000
      scsnIdentifier: 'urn:scsn:123456789'
      scsnRole: 'scsn:ServiceProvider'

db:
  type: sqlite
  database: wallet.sqlite

# db:
#   type: postgres
#   database: wallet
#   host: localhost
#   port: 5432
#   username: test
#   password: test


mail:
  enabled: true
  smtp:
    host: aa
    port: 123
    secure: true
    user: abcdef
    password: abcd
    from: noreply@dataspac.es
  title: SCSN Wallet
  dataspace: SCSN

trustAnchors:
  - identifier: did:web:localhost%3A3000
    credentialTypes:
      - SCSNCredential
      - scsn:SCSNCredential
      - https://wallet.alpha.scsn.dataspac.es/credentials/SCSNCredential

contexts:
  - id: SCSN
    credentialType: SCSNCredential
    issuable: true
    document:
      '@context':
        '@version': 1.1
        '@protected': true
        scsn: https://wallet.alpha.scsn.dataspac.es/credentials/
        id: '@id'
        type: '@type'
        SCSNCredential:
          '@context':
            - https://www.w3.org/2018/credentials/v1
          '@id': 'scsn:SCSNCredential'
        scsnIdentifier:
          '@id': 'scsn:scsnIdentifier'
        scsnRole:
          '@id': 'scsn:scsnRole'
          "@type": '@id'
        ServiceProvider:
          '@id': 'scsn:ServiceProvider'
        Manufacturer:
          '@id': 'scsn:Manufacturer'
        Administrator:
          '@id': 'scsn:Administrator'
    schema:
      type: object
      title: SCSNCredential
      additionalProperties: true
      properties:
        id:
          type: string
          pattern: "^did:web:.*"
        scsnIdentifier:
          type: string
          pattern: "^urn:scsn:.*"
        scsnRole:
          enum:
          - scsn:ServiceProvider
          - scsn:Manufacturer
          - scsn:Administrator
      required:
      - id
      - scsnIdentifier
      - scsnRole
  - id: Catena-X
    credentialType: SummaryCredential
    issuable: false
    documentUrl: https://catenax-ng.github.io/product-core-schemas/SummaryVC.json