server:
  port: 3000
  listen: '0.0.0.0'
  publicDomain: localhost:3000

initClients:
  - id: admin
    secret: test
    email: noreply@dataspac.es
    roles:
      - view_all_credentials
      - manage_all_credentials
      - manage_keys
      - manage_clients
initKeys:
  - id: key-0
    type: EdDSA
    # default: true
  - id: key-1
    type: ES384
    default: true

initCredentials:
  - context:
      - https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework
    id: gaiax
    credentialSubject:
      id: did:web:localhost%3A3000
      gx:legalName: Stichting Maastricht Radiation Oncology "Maastro-Clinic"
      gx:registrationNumber:
        gx:registrationNumberType: vatID
        gx:registrationNumberNumber: NL004210104B01
      gx:headquarterAddress:
        gx:addressCountryCode: NL
        gx:addressCode: NL-LI
        gx:streetAddress: Dr Tanslaan 12
        gx:postalCode: 6229ET
      gx:legalAddress:
        gx:addressCountryCode: NL
        gx:addressCode: NL-LI
        gx:streetAddress: Dr Tanslaan 12
        gx:postalCode: 6229ET
      gx:termsAndConditions: 70c1d713215f95191a11d38fe2341faed27d19e083917bc8732ca4fea4976700

  - id: scsn
    type:
      - http://smart-connected.nl/context/SCSNCredential
    credentialSubject:
      id: did:web:localhost%3A3000
      'http://smart-connected.nl/context/scsnId': 'urn:scsn:123456789'
      'http://smart-connected.nl/context/role': 'http://smart-connected.nl/context/ServiceProvider'

db:
  type: sqlite
  database: wallet.sqlite

# db:
#   type: postgres
#   database: wallet
#   host: localhost
#   port: 5432
#   username: test
#   password: test


mail:
  enabled: true
  smtp:
    host: aa
    port: 123
    secure: true
    user: abcdef
    password: abcd
    from: noreply@dataspac.es
  title: SCSN Wallet
  dataspace: SCSN
  
