apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "casdoor.fullname" . }}-config
  labels: {{ include "casdoor.labels" $ | nindent 4 }}
data:
  app.conf: |-
    {{- tpl (.Values.config | toToml) $ | replace ".0" "" | nindent 4}}