apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "casdoor.fullname" . }}
  labels: {{ include "casdoor.labels" $ | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "casdoor.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "casdoor.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ tpl (toYaml .Values.config) . | sha256sum }}
    spec:
      containers:
        - name: casdoor
          image: "{{ .Values.image }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: RUNNING_IN_DOCKER
              value: "true"
          {{- with concat .Values.env (fromYamlArray (list .Values.configFromSecrets "" | include "recurseSecretConfig"))}}
           {{ toYaml . | nindent 12 }}
          {{- end }}
          resources:
            requests:
              memory: "100Mi"
          ports:
            - name: http
              containerPort: {{ .Values.config.httpport | default 8000 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - name: casdoor-config
            mountPath: /conf/app.conf
            subPath: "app.conf"
      volumes:
      - name: casdoor-config
        configMap:
          name: {{ template "casdoor.fullname" . }}-config
