---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-init" (include "tsg.fullname" .) }}
  labels: {{- include "tsg.labels" . | nindent 4 }}
spec:
  template:
    spec:
      serviceAccountName: {{ include "tsg.serviceAccountName" . }}
      restartPolicy: "OnFailure"
      containers:
        - image: {{ .Values.initImage }}
          name: casdoor-init
          imagePullPolicy: Always
          args: ["while true; do sleep 5; done;"]
          volumeMounts:
            - name: init-config
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: init-config
          configMap:
            name: {{ printf "%s-init-config" (include "tsg.fullname" .) }}
