apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-init-config" (include "tsg.fullname" .) }}
  labels:
    {{- include "tsg.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- tpl (toYaml .Values.initConfig) . | nindent 4 }}