apiVersion: v1
kind: Service
metadata:
  name: {{ template "casdoor.fullname" . }}
  labels: {{ include "casdoor.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $.Values.config.httpport | default 8000 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ template "casdoor.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
