import { MigrationInterface, QueryRunner } from "typeorm";

export class Sqlite20241112151859 implements MigrationInterface {
    name = 'Sqlite20241112151859'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "transfer_event_dao" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "_id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "time" varchar NOT NULL, "state" varchar CHECK( "state" IN ('dspace:REQUESTED','dspace:STARTED','dspace:TERMINATED','dspace:COMPLETED','dspace:SUSPENDED') ) NOT NULL, "localMessage" varchar, "code" varchar, "reason" text, "type" varchar NOT NULL, "StatusLocalId" varchar)`);
        await queryRunner.query(`CREATE TABLE "transfer_detail_dao" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "localId" varchar PRIMARY KEY NOT NULL, "remoteId" varchar, "role" varchar NOT NULL, "remoteAddress" varchar NOT NULL, "remoteParty" varchar NOT NULL, "state" varchar CHECK( "state" IN ('dspace:REQUESTED','dspace:STARTED','dspace:TERMINATED','dspace:COMPLETED','dspace:SUSPENDED') ) NOT NULL, "process" text NOT NULL, "agreementId" varchar NOT NULL, "format" varchar, "dataAddress" text, "dataPlaneTransfer" text NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "registry" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "catalogId" varchar NOT NULL, "catalogJson" text NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "dataplanedetails" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "identifier" varchar PRIMARY KEY NOT NULL, "created" varchar, "modified" varchar, "health" varchar CHECK( "health" IN ('0','1','2','3','4') ) NOT NULL, "missedHealthChecks" integer NOT NULL, "etag" varchar, "dataplaneType" varchar NOT NULL, "endpointPrefix" varchar NOT NULL, "callbackAddress" varchar NOT NULL, "managementAddress" varchar NOT NULL, "managementToken" varchar NOT NULL, "catalogSynchronization" varchar NOT NULL, "role" varchar NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "resource" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "contactPoint" varchar, "keyword" text, "landingPage" varchar, "theme" text, "conformsTo" text, "creator" varchar, "description" text, "identifier" varchar, "isReferencedBy" varchar, "issued" varchar, "language" varchar, "license" varchar, "modified" varchar, "publisher" varchar, "relation" varchar, "title" varchar, "type" varchar, "hasVersion" text, "isVersionOf" varchar, "version" varchar, "hasCurrentVersion" varchar, "previousVersion" varchar, "extraProps" text, "hasPolicy" text)`);
        await queryRunner.query(`CREATE TABLE "dataservice" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "endpointDescription" varchar, "endpointURL" varchar, "extraProps" text, "CatalogId" varchar, "ResourceId" varchar, CONSTRAINT "REL_edb6e4ec31e7b2b836b2557ae8" UNIQUE ("ResourceId"))`);
        await queryRunner.query(`CREATE TABLE "distribution" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "accessURL" varchar, "byteSize" varchar, "compressFormat" varchar, "downloadURL" varchar, "mediaType" varchar, "packageFormat" varchar, "spatialResolutionInMeters" varchar, "temporalResolution" varchar, "conformsTo" text, "description" text, "format" varchar, "issued" varchar, "modified" varchar, "title" varchar, "extraProps" text, "hasPolicy" text)`);
        await queryRunner.query(`CREATE TABLE "dataset" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "spatialResolutionInMeters" varchar, "temporalResolution" varchar, "accrualPeriodicity" varchar, "spatial" varchar, "temporal" varchar, "wasGeneratedBy" text, "hasCodingSystem" text, "numberOfRecords" integer, "numberOfUniqueIndividuals" integer, "healthTheme" text, "extraProps" text, "ResourceId" varchar, "DataPlaneIdentifier" varchar, "CatalogId" varchar, "SampleId" varchar, CONSTRAINT "REL_fb246beee7540052e424a3a282" UNIQUE ("ResourceId"))`);
        await queryRunner.query(`CREATE TABLE "catalogrecord" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "conformsTo" text, "description" text, "issued" varchar, "modified" varchar, "title" varchar, "extraProps" text, "CatalogId" varchar, "PrimaryTopicId" varchar, CONSTRAINT "REL_d07d296415ee6b72ba38eb2cf0" UNIQUE ("PrimaryTopicId"))`);
        await queryRunner.query(`CREATE TABLE "catalog" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "themeTaxonomy" varchar, "homepage" varchar, "extraProps" text, "DatasetId" varchar, CONSTRAINT "REL_ae4c17c4f58d88f715d979ffc7" UNIQUE ("DatasetId"))`);
        await queryRunner.query(`CREATE TABLE "constraint_dao" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "type" varchar CHECK( "type" IN ('ATOMIC','LOGICAL') ) NOT NULL, "title" varchar NOT NULL, "description" varchar, "logicalOperator" varchar, "leftOperand" varchar, "operator" varchar, "contextPath" varchar, "evaluable" text, "dataType" varchar CHECK( "dataType" IN ('STRING','URI','NUMBER','DATE','DATETIME','DIF_INPUT_DESCRIPTOR') ), CONSTRAINT "UQ_d487a181b8f56c170a86fe53c87" UNIQUE ("leftOperand"))`);
        await queryRunner.query(`CREATE TABLE "rule_dao" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "action" text NOT NULL, "assignee" text)`);
        await queryRunner.query(`CREATE TABLE "agreement_dao" ("id" varchar PRIMARY KEY NOT NULL, "agreement" text NOT NULL, "negotiationId" varchar NOT NULL, "localSignature" text, "remoteSignature" text)`);
        await queryRunner.query(`CREATE TABLE "transfer_monitor_dao" ("id" varchar PRIMARY KEY NOT NULL, "lastContext" text NOT NULL, "lastDecision" text NOT NULL, "agreementId" varchar)`);
        await queryRunner.query(`CREATE TABLE "negotationProcessEvent" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "_id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "time" varchar NOT NULL, "state" varchar CHECK( "state" IN ('dspace:REQUESTED','dspace:OFFERED','dspace:ACCEPTED','dspace:AGREED','dspace:VERIFIED','dspace:FINALIZED','dspace:TERMINATED') ) NOT NULL, "localMessage" varchar, "code" varchar, "reason" text, "agreementMessage" varchar, "verification" text, "hashedMessage" text, "type" varchar NOT NULL, "DetailLocalId" varchar)`);
        await queryRunner.query(`CREATE TABLE "negotiationDetail" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "localId" varchar PRIMARY KEY NOT NULL, "remoteId" varchar NOT NULL, "remoteParty" varchar NOT NULL, "role" varchar NOT NULL, "remoteAddress" varchar NOT NULL, "state" varchar CHECK( "state" IN ('dspace:REQUESTED','dspace:OFFERED','dspace:ACCEPTED','dspace:AGREED','dspace:VERIFIED','dspace:FINALIZED','dspace:TERMINATED') ) NOT NULL, "dataSet" varchar NOT NULL, "offer" text, "agreementDaoId" varchar)`);
        await queryRunner.query(`CREATE TABLE "dataservice__serves_dataset_dataset" ("dataserviceId" varchar NOT NULL, "datasetId" varchar NOT NULL, PRIMARY KEY ("dataserviceId", "datasetId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ddeeddd6e960fcfeb7f6b12eff" ON "dataservice__serves_dataset_dataset" ("dataserviceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bdc1c1c31507d335ef1c55b70b" ON "dataservice__serves_dataset_dataset" ("datasetId") `);
        await queryRunner.query(`CREATE TABLE "distribution__access_service_dataservice" ("distributionId" varchar NOT NULL, "dataserviceId" varchar NOT NULL, PRIMARY KEY ("distributionId", "dataserviceId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d7768a9486fef84e78f7082e70" ON "distribution__access_service_dataservice" ("distributionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_715a34ea9e42548a9b4042935b" ON "distribution__access_service_dataservice" ("dataserviceId") `);
        await queryRunner.query(`CREATE TABLE "dataset__distribution_distribution" ("datasetId" varchar NOT NULL, "distributionId" varchar NOT NULL, PRIMARY KEY ("datasetId", "distributionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4327472fe98329bc616b92c878" ON "dataset__distribution_distribution" ("datasetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8fe4fc6ef86e884d7bdd3182b2" ON "dataset__distribution_distribution" ("distributionId") `);
        await queryRunner.query(`CREATE TABLE "constraint_dao_constraints_constraint_dao" ("constraintDaoId_1" integer NOT NULL, "constraintDaoId_2" integer NOT NULL, PRIMARY KEY ("constraintDaoId_1", "constraintDaoId_2"))`);
        await queryRunner.query(`CREATE INDEX "IDX_82fbec3376bb07d5cbb8662d78" ON "constraint_dao_constraints_constraint_dao" ("constraintDaoId_1") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d597d53dd5c069cdc109e572f" ON "constraint_dao_constraints_constraint_dao" ("constraintDaoId_2") `);
        await queryRunner.query(`CREATE TABLE "rule_dao_constraints_constraint_dao" ("ruleDaoId" integer NOT NULL, "constraintDaoId" integer NOT NULL, PRIMARY KEY ("ruleDaoId", "constraintDaoId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e6a3aa44c390430df2c95aba98" ON "rule_dao_constraints_constraint_dao" ("ruleDaoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b5aa628f646e589f9bd217572c" ON "rule_dao_constraints_constraint_dao" ("constraintDaoId") `);
        await queryRunner.query(`CREATE TABLE "rule_dao_duties_rule_dao" ("ruleDaoId_1" integer NOT NULL, "ruleDaoId_2" integer NOT NULL, PRIMARY KEY ("ruleDaoId_1", "ruleDaoId_2"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4e4f03d5f894766ea199f8a881" ON "rule_dao_duties_rule_dao" ("ruleDaoId_1") `);
        await queryRunner.query(`CREATE INDEX "IDX_26bd571fe9f49193e621fbb19e" ON "rule_dao_duties_rule_dao" ("ruleDaoId_2") `);
        await queryRunner.query(`CREATE TABLE "temporary_transfer_event_dao" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "_id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "time" varchar NOT NULL, "state" varchar CHECK( "state" IN ('dspace:REQUESTED','dspace:STARTED','dspace:TERMINATED','dspace:COMPLETED','dspace:SUSPENDED') ) NOT NULL, "localMessage" varchar, "code" varchar, "reason" text, "type" varchar NOT NULL, "StatusLocalId" varchar, CONSTRAINT "FK_aa9f090675dd25f4eda56555e10" FOREIGN KEY ("StatusLocalId") REFERENCES "transfer_detail_dao" ("localId") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_transfer_event_dao"("createdDate", "modifiedDate", "deletedDate", "_id", "time", "state", "localMessage", "code", "reason", "type", "StatusLocalId") SELECT "createdDate", "modifiedDate", "deletedDate", "_id", "time", "state", "localMessage", "code", "reason", "type", "StatusLocalId" FROM "transfer_event_dao"`);
        await queryRunner.query(`DROP TABLE "transfer_event_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_transfer_event_dao" RENAME TO "transfer_event_dao"`);
        await queryRunner.query(`CREATE TABLE "temporary_dataservice" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "endpointDescription" varchar, "endpointURL" varchar, "extraProps" text, "CatalogId" varchar, "ResourceId" varchar, CONSTRAINT "REL_edb6e4ec31e7b2b836b2557ae8" UNIQUE ("ResourceId"), CONSTRAINT "FK_b643e08c658adf8d62d6cb1aa60" FOREIGN KEY ("CatalogId") REFERENCES "catalog" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_edb6e4ec31e7b2b836b2557ae85" FOREIGN KEY ("ResourceId") REFERENCES "resource" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_dataservice"("createdDate", "modifiedDate", "deletedDate", "id", "endpointDescription", "endpointURL", "extraProps", "CatalogId", "ResourceId") SELECT "createdDate", "modifiedDate", "deletedDate", "id", "endpointDescription", "endpointURL", "extraProps", "CatalogId", "ResourceId" FROM "dataservice"`);
        await queryRunner.query(`DROP TABLE "dataservice"`);
        await queryRunner.query(`ALTER TABLE "temporary_dataservice" RENAME TO "dataservice"`);
        await queryRunner.query(`CREATE TABLE "temporary_dataset" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "spatialResolutionInMeters" varchar, "temporalResolution" varchar, "accrualPeriodicity" varchar, "spatial" varchar, "temporal" varchar, "wasGeneratedBy" text, "hasCodingSystem" text, "numberOfRecords" integer, "numberOfUniqueIndividuals" integer, "healthTheme" text, "extraProps" text, "ResourceId" varchar, "DataPlaneIdentifier" varchar, "CatalogId" varchar, "SampleId" varchar, CONSTRAINT "REL_fb246beee7540052e424a3a282" UNIQUE ("ResourceId"), CONSTRAINT "FK_fb246beee7540052e424a3a2826" FOREIGN KEY ("ResourceId") REFERENCES "resource" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_5ffc12673c1b713c2f00e7ed722" FOREIGN KEY ("DataPlaneIdentifier") REFERENCES "dataplanedetails" ("identifier") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f9caedee7cda920ac231bcd10d3" FOREIGN KEY ("CatalogId") REFERENCES "catalog" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_74a6000c286b98882c56ab34833" FOREIGN KEY ("SampleId") REFERENCES "distribution" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_dataset"("createdDate", "modifiedDate", "deletedDate", "id", "spatialResolutionInMeters", "temporalResolution", "accrualPeriodicity", "spatial", "temporal", "wasGeneratedBy", "hasCodingSystem", "numberOfRecords", "numberOfUniqueIndividuals", "healthTheme", "extraProps", "ResourceId", "DataPlaneIdentifier", "CatalogId", "SampleId") SELECT "createdDate", "modifiedDate", "deletedDate", "id", "spatialResolutionInMeters", "temporalResolution", "accrualPeriodicity", "spatial", "temporal", "wasGeneratedBy", "hasCodingSystem", "numberOfRecords", "numberOfUniqueIndividuals", "healthTheme", "extraProps", "ResourceId", "DataPlaneIdentifier", "CatalogId", "SampleId" FROM "dataset"`);
        await queryRunner.query(`DROP TABLE "dataset"`);
        await queryRunner.query(`ALTER TABLE "temporary_dataset" RENAME TO "dataset"`);
        await queryRunner.query(`CREATE TABLE "temporary_catalogrecord" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "conformsTo" text, "description" text, "issued" varchar, "modified" varchar, "title" varchar, "extraProps" text, "CatalogId" varchar, "PrimaryTopicId" varchar, CONSTRAINT "REL_d07d296415ee6b72ba38eb2cf0" UNIQUE ("PrimaryTopicId"), CONSTRAINT "FK_9f2fe30d4d7c2dcb6eb0bc3bfe5" FOREIGN KEY ("CatalogId") REFERENCES "catalog" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_d07d296415ee6b72ba38eb2cf0a" FOREIGN KEY ("PrimaryTopicId") REFERENCES "resource" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_catalogrecord"("createdDate", "modifiedDate", "deletedDate", "id", "conformsTo", "description", "issued", "modified", "title", "extraProps", "CatalogId", "PrimaryTopicId") SELECT "createdDate", "modifiedDate", "deletedDate", "id", "conformsTo", "description", "issued", "modified", "title", "extraProps", "CatalogId", "PrimaryTopicId" FROM "catalogrecord"`);
        await queryRunner.query(`DROP TABLE "catalogrecord"`);
        await queryRunner.query(`ALTER TABLE "temporary_catalogrecord" RENAME TO "catalogrecord"`);
        await queryRunner.query(`CREATE TABLE "temporary_catalog" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "themeTaxonomy" varchar, "homepage" varchar, "extraProps" text, "DatasetId" varchar, CONSTRAINT "REL_ae4c17c4f58d88f715d979ffc7" UNIQUE ("DatasetId"), CONSTRAINT "FK_ae4c17c4f58d88f715d979ffc72" FOREIGN KEY ("DatasetId") REFERENCES "dataset" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_catalog"("createdDate", "modifiedDate", "deletedDate", "id", "themeTaxonomy", "homepage", "extraProps", "DatasetId") SELECT "createdDate", "modifiedDate", "deletedDate", "id", "themeTaxonomy", "homepage", "extraProps", "DatasetId" FROM "catalog"`);
        await queryRunner.query(`DROP TABLE "catalog"`);
        await queryRunner.query(`ALTER TABLE "temporary_catalog" RENAME TO "catalog"`);
        await queryRunner.query(`CREATE TABLE "temporary_transfer_monitor_dao" ("id" varchar PRIMARY KEY NOT NULL, "lastContext" text NOT NULL, "lastDecision" text NOT NULL, "agreementId" varchar, CONSTRAINT "FK_e37c1bed0f0095adfa2ccd76c4c" FOREIGN KEY ("agreementId") REFERENCES "agreement_dao" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_transfer_monitor_dao"("id", "lastContext", "lastDecision", "agreementId") SELECT "id", "lastContext", "lastDecision", "agreementId" FROM "transfer_monitor_dao"`);
        await queryRunner.query(`DROP TABLE "transfer_monitor_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_transfer_monitor_dao" RENAME TO "transfer_monitor_dao"`);
        await queryRunner.query(`CREATE TABLE "temporary_negotationProcessEvent" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "_id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "time" varchar NOT NULL, "state" varchar CHECK( "state" IN ('dspace:REQUESTED','dspace:OFFERED','dspace:ACCEPTED','dspace:AGREED','dspace:VERIFIED','dspace:FINALIZED','dspace:TERMINATED') ) NOT NULL, "localMessage" varchar, "code" varchar, "reason" text, "agreementMessage" varchar, "verification" text, "hashedMessage" text, "type" varchar NOT NULL, "DetailLocalId" varchar, CONSTRAINT "FK_421acc1dc8622808e8c99c527f2" FOREIGN KEY ("DetailLocalId") REFERENCES "negotiationDetail" ("localId") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_negotationProcessEvent"("createdDate", "modifiedDate", "deletedDate", "_id", "time", "state", "localMessage", "code", "reason", "agreementMessage", "verification", "hashedMessage", "type", "DetailLocalId") SELECT "createdDate", "modifiedDate", "deletedDate", "_id", "time", "state", "localMessage", "code", "reason", "agreementMessage", "verification", "hashedMessage", "type", "DetailLocalId" FROM "negotationProcessEvent"`);
        await queryRunner.query(`DROP TABLE "negotationProcessEvent"`);
        await queryRunner.query(`ALTER TABLE "temporary_negotationProcessEvent" RENAME TO "negotationProcessEvent"`);
        await queryRunner.query(`CREATE TABLE "temporary_negotiationDetail" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "localId" varchar PRIMARY KEY NOT NULL, "remoteId" varchar NOT NULL, "remoteParty" varchar NOT NULL, "role" varchar NOT NULL, "remoteAddress" varchar NOT NULL, "state" varchar CHECK( "state" IN ('dspace:REQUESTED','dspace:OFFERED','dspace:ACCEPTED','dspace:AGREED','dspace:VERIFIED','dspace:FINALIZED','dspace:TERMINATED') ) NOT NULL, "dataSet" varchar NOT NULL, "offer" text, "agreementDaoId" varchar, CONSTRAINT "FK_9891d479b99e1fa7f5eaace22b7" FOREIGN KEY ("agreementDaoId") REFERENCES "agreement_dao" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_negotiationDetail"("createdDate", "modifiedDate", "deletedDate", "localId", "remoteId", "remoteParty", "role", "remoteAddress", "state", "dataSet", "offer", "agreementDaoId") SELECT "createdDate", "modifiedDate", "deletedDate", "localId", "remoteId", "remoteParty", "role", "remoteAddress", "state", "dataSet", "offer", "agreementDaoId" FROM "negotiationDetail"`);
        await queryRunner.query(`DROP TABLE "negotiationDetail"`);
        await queryRunner.query(`ALTER TABLE "temporary_negotiationDetail" RENAME TO "negotiationDetail"`);
        await queryRunner.query(`DROP INDEX "IDX_ddeeddd6e960fcfeb7f6b12eff"`);
        await queryRunner.query(`DROP INDEX "IDX_bdc1c1c31507d335ef1c55b70b"`);
        await queryRunner.query(`CREATE TABLE "temporary_dataservice__serves_dataset_dataset" ("dataserviceId" varchar NOT NULL, "datasetId" varchar NOT NULL, CONSTRAINT "FK_ddeeddd6e960fcfeb7f6b12eff3" FOREIGN KEY ("dataserviceId") REFERENCES "dataservice" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_bdc1c1c31507d335ef1c55b70ba" FOREIGN KEY ("datasetId") REFERENCES "dataset" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("dataserviceId", "datasetId"))`);
        await queryRunner.query(`INSERT INTO "temporary_dataservice__serves_dataset_dataset"("dataserviceId", "datasetId") SELECT "dataserviceId", "datasetId" FROM "dataservice__serves_dataset_dataset"`);
        await queryRunner.query(`DROP TABLE "dataservice__serves_dataset_dataset"`);
        await queryRunner.query(`ALTER TABLE "temporary_dataservice__serves_dataset_dataset" RENAME TO "dataservice__serves_dataset_dataset"`);
        await queryRunner.query(`CREATE INDEX "IDX_ddeeddd6e960fcfeb7f6b12eff" ON "dataservice__serves_dataset_dataset" ("dataserviceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bdc1c1c31507d335ef1c55b70b" ON "dataservice__serves_dataset_dataset" ("datasetId") `);
        await queryRunner.query(`DROP INDEX "IDX_d7768a9486fef84e78f7082e70"`);
        await queryRunner.query(`DROP INDEX "IDX_715a34ea9e42548a9b4042935b"`);
        await queryRunner.query(`CREATE TABLE "temporary_distribution__access_service_dataservice" ("distributionId" varchar NOT NULL, "dataserviceId" varchar NOT NULL, CONSTRAINT "FK_d7768a9486fef84e78f7082e70f" FOREIGN KEY ("distributionId") REFERENCES "distribution" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_715a34ea9e42548a9b4042935b1" FOREIGN KEY ("dataserviceId") REFERENCES "dataservice" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("distributionId", "dataserviceId"))`);
        await queryRunner.query(`INSERT INTO "temporary_distribution__access_service_dataservice"("distributionId", "dataserviceId") SELECT "distributionId", "dataserviceId" FROM "distribution__access_service_dataservice"`);
        await queryRunner.query(`DROP TABLE "distribution__access_service_dataservice"`);
        await queryRunner.query(`ALTER TABLE "temporary_distribution__access_service_dataservice" RENAME TO "distribution__access_service_dataservice"`);
        await queryRunner.query(`CREATE INDEX "IDX_d7768a9486fef84e78f7082e70" ON "distribution__access_service_dataservice" ("distributionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_715a34ea9e42548a9b4042935b" ON "distribution__access_service_dataservice" ("dataserviceId") `);
        await queryRunner.query(`DROP INDEX "IDX_4327472fe98329bc616b92c878"`);
        await queryRunner.query(`DROP INDEX "IDX_8fe4fc6ef86e884d7bdd3182b2"`);
        await queryRunner.query(`CREATE TABLE "temporary_dataset__distribution_distribution" ("datasetId" varchar NOT NULL, "distributionId" varchar NOT NULL, CONSTRAINT "FK_4327472fe98329bc616b92c8781" FOREIGN KEY ("datasetId") REFERENCES "dataset" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_8fe4fc6ef86e884d7bdd3182b2d" FOREIGN KEY ("distributionId") REFERENCES "distribution" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("datasetId", "distributionId"))`);
        await queryRunner.query(`INSERT INTO "temporary_dataset__distribution_distribution"("datasetId", "distributionId") SELECT "datasetId", "distributionId" FROM "dataset__distribution_distribution"`);
        await queryRunner.query(`DROP TABLE "dataset__distribution_distribution"`);
        await queryRunner.query(`ALTER TABLE "temporary_dataset__distribution_distribution" RENAME TO "dataset__distribution_distribution"`);
        await queryRunner.query(`CREATE INDEX "IDX_4327472fe98329bc616b92c878" ON "dataset__distribution_distribution" ("datasetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8fe4fc6ef86e884d7bdd3182b2" ON "dataset__distribution_distribution" ("distributionId") `);
        await queryRunner.query(`DROP INDEX "IDX_82fbec3376bb07d5cbb8662d78"`);
        await queryRunner.query(`DROP INDEX "IDX_0d597d53dd5c069cdc109e572f"`);
        await queryRunner.query(`CREATE TABLE "temporary_constraint_dao_constraints_constraint_dao" ("constraintDaoId_1" integer NOT NULL, "constraintDaoId_2" integer NOT NULL, CONSTRAINT "FK_82fbec3376bb07d5cbb8662d78b" FOREIGN KEY ("constraintDaoId_1") REFERENCES "constraint_dao" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_0d597d53dd5c069cdc109e572f7" FOREIGN KEY ("constraintDaoId_2") REFERENCES "constraint_dao" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("constraintDaoId_1", "constraintDaoId_2"))`);
        await queryRunner.query(`INSERT INTO "temporary_constraint_dao_constraints_constraint_dao"("constraintDaoId_1", "constraintDaoId_2") SELECT "constraintDaoId_1", "constraintDaoId_2" FROM "constraint_dao_constraints_constraint_dao"`);
        await queryRunner.query(`DROP TABLE "constraint_dao_constraints_constraint_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_constraint_dao_constraints_constraint_dao" RENAME TO "constraint_dao_constraints_constraint_dao"`);
        await queryRunner.query(`CREATE INDEX "IDX_82fbec3376bb07d5cbb8662d78" ON "constraint_dao_constraints_constraint_dao" ("constraintDaoId_1") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d597d53dd5c069cdc109e572f" ON "constraint_dao_constraints_constraint_dao" ("constraintDaoId_2") `);
        await queryRunner.query(`DROP INDEX "IDX_e6a3aa44c390430df2c95aba98"`);
        await queryRunner.query(`DROP INDEX "IDX_b5aa628f646e589f9bd217572c"`);
        await queryRunner.query(`CREATE TABLE "temporary_rule_dao_constraints_constraint_dao" ("ruleDaoId" integer NOT NULL, "constraintDaoId" integer NOT NULL, CONSTRAINT "FK_e6a3aa44c390430df2c95aba980" FOREIGN KEY ("ruleDaoId") REFERENCES "rule_dao" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_b5aa628f646e589f9bd217572c3" FOREIGN KEY ("constraintDaoId") REFERENCES "constraint_dao" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("ruleDaoId", "constraintDaoId"))`);
        await queryRunner.query(`INSERT INTO "temporary_rule_dao_constraints_constraint_dao"("ruleDaoId", "constraintDaoId") SELECT "ruleDaoId", "constraintDaoId" FROM "rule_dao_constraints_constraint_dao"`);
        await queryRunner.query(`DROP TABLE "rule_dao_constraints_constraint_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_rule_dao_constraints_constraint_dao" RENAME TO "rule_dao_constraints_constraint_dao"`);
        await queryRunner.query(`CREATE INDEX "IDX_e6a3aa44c390430df2c95aba98" ON "rule_dao_constraints_constraint_dao" ("ruleDaoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b5aa628f646e589f9bd217572c" ON "rule_dao_constraints_constraint_dao" ("constraintDaoId") `);
        await queryRunner.query(`DROP INDEX "IDX_4e4f03d5f894766ea199f8a881"`);
        await queryRunner.query(`DROP INDEX "IDX_26bd571fe9f49193e621fbb19e"`);
        await queryRunner.query(`CREATE TABLE "temporary_rule_dao_duties_rule_dao" ("ruleDaoId_1" integer NOT NULL, "ruleDaoId_2" integer NOT NULL, CONSTRAINT "FK_4e4f03d5f894766ea199f8a8813" FOREIGN KEY ("ruleDaoId_1") REFERENCES "rule_dao" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_26bd571fe9f49193e621fbb19e8" FOREIGN KEY ("ruleDaoId_2") REFERENCES "rule_dao" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("ruleDaoId_1", "ruleDaoId_2"))`);
        await queryRunner.query(`INSERT INTO "temporary_rule_dao_duties_rule_dao"("ruleDaoId_1", "ruleDaoId_2") SELECT "ruleDaoId_1", "ruleDaoId_2" FROM "rule_dao_duties_rule_dao"`);
        await queryRunner.query(`DROP TABLE "rule_dao_duties_rule_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_rule_dao_duties_rule_dao" RENAME TO "rule_dao_duties_rule_dao"`);
        await queryRunner.query(`CREATE INDEX "IDX_4e4f03d5f894766ea199f8a881" ON "rule_dao_duties_rule_dao" ("ruleDaoId_1") `);
        await queryRunner.query(`CREATE INDEX "IDX_26bd571fe9f49193e621fbb19e" ON "rule_dao_duties_rule_dao" ("ruleDaoId_2") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_26bd571fe9f49193e621fbb19e"`);
        await queryRunner.query(`DROP INDEX "IDX_4e4f03d5f894766ea199f8a881"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" RENAME TO "temporary_rule_dao_duties_rule_dao"`);
        await queryRunner.query(`CREATE TABLE "rule_dao_duties_rule_dao" ("ruleDaoId_1" integer NOT NULL, "ruleDaoId_2" integer NOT NULL, PRIMARY KEY ("ruleDaoId_1", "ruleDaoId_2"))`);
        await queryRunner.query(`INSERT INTO "rule_dao_duties_rule_dao"("ruleDaoId_1", "ruleDaoId_2") SELECT "ruleDaoId_1", "ruleDaoId_2" FROM "temporary_rule_dao_duties_rule_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_rule_dao_duties_rule_dao"`);
        await queryRunner.query(`CREATE INDEX "IDX_26bd571fe9f49193e621fbb19e" ON "rule_dao_duties_rule_dao" ("ruleDaoId_2") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e4f03d5f894766ea199f8a881" ON "rule_dao_duties_rule_dao" ("ruleDaoId_1") `);
        await queryRunner.query(`DROP INDEX "IDX_b5aa628f646e589f9bd217572c"`);
        await queryRunner.query(`DROP INDEX "IDX_e6a3aa44c390430df2c95aba98"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" RENAME TO "temporary_rule_dao_constraints_constraint_dao"`);
        await queryRunner.query(`CREATE TABLE "rule_dao_constraints_constraint_dao" ("ruleDaoId" integer NOT NULL, "constraintDaoId" integer NOT NULL, PRIMARY KEY ("ruleDaoId", "constraintDaoId"))`);
        await queryRunner.query(`INSERT INTO "rule_dao_constraints_constraint_dao"("ruleDaoId", "constraintDaoId") SELECT "ruleDaoId", "constraintDaoId" FROM "temporary_rule_dao_constraints_constraint_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_rule_dao_constraints_constraint_dao"`);
        await queryRunner.query(`CREATE INDEX "IDX_b5aa628f646e589f9bd217572c" ON "rule_dao_constraints_constraint_dao" ("constraintDaoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6a3aa44c390430df2c95aba98" ON "rule_dao_constraints_constraint_dao" ("ruleDaoId") `);
        await queryRunner.query(`DROP INDEX "IDX_0d597d53dd5c069cdc109e572f"`);
        await queryRunner.query(`DROP INDEX "IDX_82fbec3376bb07d5cbb8662d78"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" RENAME TO "temporary_constraint_dao_constraints_constraint_dao"`);
        await queryRunner.query(`CREATE TABLE "constraint_dao_constraints_constraint_dao" ("constraintDaoId_1" integer NOT NULL, "constraintDaoId_2" integer NOT NULL, PRIMARY KEY ("constraintDaoId_1", "constraintDaoId_2"))`);
        await queryRunner.query(`INSERT INTO "constraint_dao_constraints_constraint_dao"("constraintDaoId_1", "constraintDaoId_2") SELECT "constraintDaoId_1", "constraintDaoId_2" FROM "temporary_constraint_dao_constraints_constraint_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_constraint_dao_constraints_constraint_dao"`);
        await queryRunner.query(`CREATE INDEX "IDX_0d597d53dd5c069cdc109e572f" ON "constraint_dao_constraints_constraint_dao" ("constraintDaoId_2") `);
        await queryRunner.query(`CREATE INDEX "IDX_82fbec3376bb07d5cbb8662d78" ON "constraint_dao_constraints_constraint_dao" ("constraintDaoId_1") `);
        await queryRunner.query(`DROP INDEX "IDX_8fe4fc6ef86e884d7bdd3182b2"`);
        await queryRunner.query(`DROP INDEX "IDX_4327472fe98329bc616b92c878"`);
        await queryRunner.query(`ALTER TABLE "dataset__distribution_distribution" RENAME TO "temporary_dataset__distribution_distribution"`);
        await queryRunner.query(`CREATE TABLE "dataset__distribution_distribution" ("datasetId" varchar NOT NULL, "distributionId" varchar NOT NULL, PRIMARY KEY ("datasetId", "distributionId"))`);
        await queryRunner.query(`INSERT INTO "dataset__distribution_distribution"("datasetId", "distributionId") SELECT "datasetId", "distributionId" FROM "temporary_dataset__distribution_distribution"`);
        await queryRunner.query(`DROP TABLE "temporary_dataset__distribution_distribution"`);
        await queryRunner.query(`CREATE INDEX "IDX_8fe4fc6ef86e884d7bdd3182b2" ON "dataset__distribution_distribution" ("distributionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4327472fe98329bc616b92c878" ON "dataset__distribution_distribution" ("datasetId") `);
        await queryRunner.query(`DROP INDEX "IDX_715a34ea9e42548a9b4042935b"`);
        await queryRunner.query(`DROP INDEX "IDX_d7768a9486fef84e78f7082e70"`);
        await queryRunner.query(`ALTER TABLE "distribution__access_service_dataservice" RENAME TO "temporary_distribution__access_service_dataservice"`);
        await queryRunner.query(`CREATE TABLE "distribution__access_service_dataservice" ("distributionId" varchar NOT NULL, "dataserviceId" varchar NOT NULL, PRIMARY KEY ("distributionId", "dataserviceId"))`);
        await queryRunner.query(`INSERT INTO "distribution__access_service_dataservice"("distributionId", "dataserviceId") SELECT "distributionId", "dataserviceId" FROM "temporary_distribution__access_service_dataservice"`);
        await queryRunner.query(`DROP TABLE "temporary_distribution__access_service_dataservice"`);
        await queryRunner.query(`CREATE INDEX "IDX_715a34ea9e42548a9b4042935b" ON "distribution__access_service_dataservice" ("dataserviceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d7768a9486fef84e78f7082e70" ON "distribution__access_service_dataservice" ("distributionId") `);
        await queryRunner.query(`DROP INDEX "IDX_bdc1c1c31507d335ef1c55b70b"`);
        await queryRunner.query(`DROP INDEX "IDX_ddeeddd6e960fcfeb7f6b12eff"`);
        await queryRunner.query(`ALTER TABLE "dataservice__serves_dataset_dataset" RENAME TO "temporary_dataservice__serves_dataset_dataset"`);
        await queryRunner.query(`CREATE TABLE "dataservice__serves_dataset_dataset" ("dataserviceId" varchar NOT NULL, "datasetId" varchar NOT NULL, PRIMARY KEY ("dataserviceId", "datasetId"))`);
        await queryRunner.query(`INSERT INTO "dataservice__serves_dataset_dataset"("dataserviceId", "datasetId") SELECT "dataserviceId", "datasetId" FROM "temporary_dataservice__serves_dataset_dataset"`);
        await queryRunner.query(`DROP TABLE "temporary_dataservice__serves_dataset_dataset"`);
        await queryRunner.query(`CREATE INDEX "IDX_bdc1c1c31507d335ef1c55b70b" ON "dataservice__serves_dataset_dataset" ("datasetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ddeeddd6e960fcfeb7f6b12eff" ON "dataservice__serves_dataset_dataset" ("dataserviceId") `);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" RENAME TO "temporary_negotiationDetail"`);
        await queryRunner.query(`CREATE TABLE "negotiationDetail" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "localId" varchar PRIMARY KEY NOT NULL, "remoteId" varchar NOT NULL, "remoteParty" varchar NOT NULL, "role" varchar NOT NULL, "remoteAddress" varchar NOT NULL, "state" varchar CHECK( "state" IN ('dspace:REQUESTED','dspace:OFFERED','dspace:ACCEPTED','dspace:AGREED','dspace:VERIFIED','dspace:FINALIZED','dspace:TERMINATED') ) NOT NULL, "dataSet" varchar NOT NULL, "offer" text, "agreementDaoId" varchar)`);
        await queryRunner.query(`INSERT INTO "negotiationDetail"("createdDate", "modifiedDate", "deletedDate", "localId", "remoteId", "remoteParty", "role", "remoteAddress", "state", "dataSet", "offer", "agreementDaoId") SELECT "createdDate", "modifiedDate", "deletedDate", "localId", "remoteId", "remoteParty", "role", "remoteAddress", "state", "dataSet", "offer", "agreementDaoId" FROM "temporary_negotiationDetail"`);
        await queryRunner.query(`DROP TABLE "temporary_negotiationDetail"`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" RENAME TO "temporary_negotationProcessEvent"`);
        await queryRunner.query(`CREATE TABLE "negotationProcessEvent" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "_id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "time" varchar NOT NULL, "state" varchar CHECK( "state" IN ('dspace:REQUESTED','dspace:OFFERED','dspace:ACCEPTED','dspace:AGREED','dspace:VERIFIED','dspace:FINALIZED','dspace:TERMINATED') ) NOT NULL, "localMessage" varchar, "code" varchar, "reason" text, "agreementMessage" varchar, "verification" text, "hashedMessage" text, "type" varchar NOT NULL, "DetailLocalId" varchar)`);
        await queryRunner.query(`INSERT INTO "negotationProcessEvent"("createdDate", "modifiedDate", "deletedDate", "_id", "time", "state", "localMessage", "code", "reason", "agreementMessage", "verification", "hashedMessage", "type", "DetailLocalId") SELECT "createdDate", "modifiedDate", "deletedDate", "_id", "time", "state", "localMessage", "code", "reason", "agreementMessage", "verification", "hashedMessage", "type", "DetailLocalId" FROM "temporary_negotationProcessEvent"`);
        await queryRunner.query(`DROP TABLE "temporary_negotationProcessEvent"`);
        await queryRunner.query(`ALTER TABLE "transfer_monitor_dao" RENAME TO "temporary_transfer_monitor_dao"`);
        await queryRunner.query(`CREATE TABLE "transfer_monitor_dao" ("id" varchar PRIMARY KEY NOT NULL, "lastContext" text NOT NULL, "lastDecision" text NOT NULL, "agreementId" varchar)`);
        await queryRunner.query(`INSERT INTO "transfer_monitor_dao"("id", "lastContext", "lastDecision", "agreementId") SELECT "id", "lastContext", "lastDecision", "agreementId" FROM "temporary_transfer_monitor_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_transfer_monitor_dao"`);
        await queryRunner.query(`ALTER TABLE "catalog" RENAME TO "temporary_catalog"`);
        await queryRunner.query(`CREATE TABLE "catalog" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "themeTaxonomy" varchar, "homepage" varchar, "extraProps" text, "DatasetId" varchar, CONSTRAINT "REL_ae4c17c4f58d88f715d979ffc7" UNIQUE ("DatasetId"))`);
        await queryRunner.query(`INSERT INTO "catalog"("createdDate", "modifiedDate", "deletedDate", "id", "themeTaxonomy", "homepage", "extraProps", "DatasetId") SELECT "createdDate", "modifiedDate", "deletedDate", "id", "themeTaxonomy", "homepage", "extraProps", "DatasetId" FROM "temporary_catalog"`);
        await queryRunner.query(`DROP TABLE "temporary_catalog"`);
        await queryRunner.query(`ALTER TABLE "catalogrecord" RENAME TO "temporary_catalogrecord"`);
        await queryRunner.query(`CREATE TABLE "catalogrecord" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "conformsTo" text, "description" text, "issued" varchar, "modified" varchar, "title" varchar, "extraProps" text, "CatalogId" varchar, "PrimaryTopicId" varchar, CONSTRAINT "REL_d07d296415ee6b72ba38eb2cf0" UNIQUE ("PrimaryTopicId"))`);
        await queryRunner.query(`INSERT INTO "catalogrecord"("createdDate", "modifiedDate", "deletedDate", "id", "conformsTo", "description", "issued", "modified", "title", "extraProps", "CatalogId", "PrimaryTopicId") SELECT "createdDate", "modifiedDate", "deletedDate", "id", "conformsTo", "description", "issued", "modified", "title", "extraProps", "CatalogId", "PrimaryTopicId" FROM "temporary_catalogrecord"`);
        await queryRunner.query(`DROP TABLE "temporary_catalogrecord"`);
        await queryRunner.query(`ALTER TABLE "dataset" RENAME TO "temporary_dataset"`);
        await queryRunner.query(`CREATE TABLE "dataset" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "spatialResolutionInMeters" varchar, "temporalResolution" varchar, "accrualPeriodicity" varchar, "spatial" varchar, "temporal" varchar, "wasGeneratedBy" text, "hasCodingSystem" text, "numberOfRecords" integer, "numberOfUniqueIndividuals" integer, "healthTheme" text, "extraProps" text, "ResourceId" varchar, "DataPlaneIdentifier" varchar, "CatalogId" varchar, "SampleId" varchar, CONSTRAINT "REL_fb246beee7540052e424a3a282" UNIQUE ("ResourceId"))`);
        await queryRunner.query(`INSERT INTO "dataset"("createdDate", "modifiedDate", "deletedDate", "id", "spatialResolutionInMeters", "temporalResolution", "accrualPeriodicity", "spatial", "temporal", "wasGeneratedBy", "hasCodingSystem", "numberOfRecords", "numberOfUniqueIndividuals", "healthTheme", "extraProps", "ResourceId", "DataPlaneIdentifier", "CatalogId", "SampleId") SELECT "createdDate", "modifiedDate", "deletedDate", "id", "spatialResolutionInMeters", "temporalResolution", "accrualPeriodicity", "spatial", "temporal", "wasGeneratedBy", "hasCodingSystem", "numberOfRecords", "numberOfUniqueIndividuals", "healthTheme", "extraProps", "ResourceId", "DataPlaneIdentifier", "CatalogId", "SampleId" FROM "temporary_dataset"`);
        await queryRunner.query(`DROP TABLE "temporary_dataset"`);
        await queryRunner.query(`ALTER TABLE "dataservice" RENAME TO "temporary_dataservice"`);
        await queryRunner.query(`CREATE TABLE "dataservice" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "endpointDescription" varchar, "endpointURL" varchar, "extraProps" text, "CatalogId" varchar, "ResourceId" varchar, CONSTRAINT "REL_edb6e4ec31e7b2b836b2557ae8" UNIQUE ("ResourceId"))`);
        await queryRunner.query(`INSERT INTO "dataservice"("createdDate", "modifiedDate", "deletedDate", "id", "endpointDescription", "endpointURL", "extraProps", "CatalogId", "ResourceId") SELECT "createdDate", "modifiedDate", "deletedDate", "id", "endpointDescription", "endpointURL", "extraProps", "CatalogId", "ResourceId" FROM "temporary_dataservice"`);
        await queryRunner.query(`DROP TABLE "temporary_dataservice"`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" RENAME TO "temporary_transfer_event_dao"`);
        await queryRunner.query(`CREATE TABLE "transfer_event_dao" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "_id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "time" varchar NOT NULL, "state" varchar CHECK( "state" IN ('dspace:REQUESTED','dspace:STARTED','dspace:TERMINATED','dspace:COMPLETED','dspace:SUSPENDED') ) NOT NULL, "localMessage" varchar, "code" varchar, "reason" text, "type" varchar NOT NULL, "StatusLocalId" varchar)`);
        await queryRunner.query(`INSERT INTO "transfer_event_dao"("createdDate", "modifiedDate", "deletedDate", "_id", "time", "state", "localMessage", "code", "reason", "type", "StatusLocalId") SELECT "createdDate", "modifiedDate", "deletedDate", "_id", "time", "state", "localMessage", "code", "reason", "type", "StatusLocalId" FROM "temporary_transfer_event_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_transfer_event_dao"`);
        await queryRunner.query(`DROP INDEX "IDX_26bd571fe9f49193e621fbb19e"`);
        await queryRunner.query(`DROP INDEX "IDX_4e4f03d5f894766ea199f8a881"`);
        await queryRunner.query(`DROP TABLE "rule_dao_duties_rule_dao"`);
        await queryRunner.query(`DROP INDEX "IDX_b5aa628f646e589f9bd217572c"`);
        await queryRunner.query(`DROP INDEX "IDX_e6a3aa44c390430df2c95aba98"`);
        await queryRunner.query(`DROP TABLE "rule_dao_constraints_constraint_dao"`);
        await queryRunner.query(`DROP INDEX "IDX_0d597d53dd5c069cdc109e572f"`);
        await queryRunner.query(`DROP INDEX "IDX_82fbec3376bb07d5cbb8662d78"`);
        await queryRunner.query(`DROP TABLE "constraint_dao_constraints_constraint_dao"`);
        await queryRunner.query(`DROP INDEX "IDX_8fe4fc6ef86e884d7bdd3182b2"`);
        await queryRunner.query(`DROP INDEX "IDX_4327472fe98329bc616b92c878"`);
        await queryRunner.query(`DROP TABLE "dataset__distribution_distribution"`);
        await queryRunner.query(`DROP INDEX "IDX_715a34ea9e42548a9b4042935b"`);
        await queryRunner.query(`DROP INDEX "IDX_d7768a9486fef84e78f7082e70"`);
        await queryRunner.query(`DROP TABLE "distribution__access_service_dataservice"`);
        await queryRunner.query(`DROP INDEX "IDX_bdc1c1c31507d335ef1c55b70b"`);
        await queryRunner.query(`DROP INDEX "IDX_ddeeddd6e960fcfeb7f6b12eff"`);
        await queryRunner.query(`DROP TABLE "dataservice__serves_dataset_dataset"`);
        await queryRunner.query(`DROP TABLE "negotiationDetail"`);
        await queryRunner.query(`DROP TABLE "negotationProcessEvent"`);
        await queryRunner.query(`DROP TABLE "transfer_monitor_dao"`);
        await queryRunner.query(`DROP TABLE "agreement_dao"`);
        await queryRunner.query(`DROP TABLE "rule_dao"`);
        await queryRunner.query(`DROP TABLE "constraint_dao"`);
        await queryRunner.query(`DROP TABLE "catalog"`);
        await queryRunner.query(`DROP TABLE "catalogrecord"`);
        await queryRunner.query(`DROP TABLE "dataset"`);
        await queryRunner.query(`DROP TABLE "distribution"`);
        await queryRunner.query(`DROP TABLE "dataservice"`);
        await queryRunner.query(`DROP TABLE "resource"`);
        await queryRunner.query(`DROP TABLE "dataplanedetails"`);
        await queryRunner.query(`DROP TABLE "registry"`);
        await queryRunner.query(`DROP TABLE "transfer_detail_dao"`);
        await queryRunner.query(`DROP TABLE "transfer_event_dao"`);
    }

}
