import { MigrationInterface, QueryRunner } from "typeorm";

export class Postgres20241112151859 implements MigrationInterface {
    name = 'Postgres20241112151859'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."transfer_event_dao_state_enum" AS ENUM('dspace:REQUESTED', 'dspace:STARTED', 'dspace:TERMINATED', 'dspace:COMPLETED', 'dspace:SUSPENDED')`);
        await queryRunner.query(`CREATE TABLE "transfer_event_dao" ("createdDate" TIMESTAMP NOT NULL DEFAULT now(), "modifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "deletedDate" TIMESTAMP, "_id" SERIAL NOT NULL, "time" character varying NOT NULL, "state" "public"."transfer_event_dao_state_enum" NOT NULL, "localMessage" character varying, "code" character varying, "reason" text, "type" character varying NOT NULL, "StatusLocalId" character varying, CONSTRAINT "PK_312cf9b90f13412429277e788cc" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."transfer_detail_dao_state_enum" AS ENUM('dspace:REQUESTED', 'dspace:STARTED', 'dspace:TERMINATED', 'dspace:COMPLETED', 'dspace:SUSPENDED')`);
        await queryRunner.query(`CREATE TABLE "transfer_detail_dao" ("createdDate" TIMESTAMP NOT NULL DEFAULT now(), "modifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "deletedDate" TIMESTAMP, "localId" character varying NOT NULL, "remoteId" character varying, "role" character varying NOT NULL, "remoteAddress" character varying NOT NULL, "remoteParty" character varying NOT NULL, "state" "public"."transfer_detail_dao_state_enum" NOT NULL, "process" text NOT NULL, "agreementId" character varying NOT NULL, "format" character varying, "dataAddress" text, "dataPlaneTransfer" text NOT NULL, CONSTRAINT "PK_cdd0938967466ddfea5dc2400df" PRIMARY KEY ("localId"))`);
        await queryRunner.query(`CREATE TABLE "registry" ("createdDate" TIMESTAMP NOT NULL DEFAULT now(), "modifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "deletedDate" TIMESTAMP, "id" SERIAL NOT NULL, "catalogId" character varying NOT NULL, "catalogJson" text NOT NULL, CONSTRAINT "PK_2eca29d55a9556d854416df8ce5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."dataplanedetails_health_enum" AS ENUM('0', '1', '2', '3', '4')`);
        await queryRunner.query(`CREATE TABLE "dataplanedetails" ("createdDate" TIMESTAMP NOT NULL DEFAULT now(), "modifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "deletedDate" TIMESTAMP, "identifier" character varying NOT NULL, "created" character varying, "modified" character varying, "health" "public"."dataplanedetails_health_enum" NOT NULL, "missedHealthChecks" integer NOT NULL, "etag" character varying, "dataplaneType" character varying NOT NULL, "endpointPrefix" character varying NOT NULL, "callbackAddress" character varying NOT NULL, "managementAddress" character varying NOT NULL, "managementToken" character varying NOT NULL, "catalogSynchronization" character varying NOT NULL, "role" character varying NOT NULL, CONSTRAINT "PK_a47df13049c0a46016d2475cc58" PRIMARY KEY ("identifier"))`);
        await queryRunner.query(`CREATE TABLE "resource" ("createdDate" TIMESTAMP NOT NULL DEFAULT now(), "modifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "deletedDate" TIMESTAMP, "id" character varying NOT NULL, "contactPoint" character varying, "keyword" text, "landingPage" character varying, "theme" text, "conformsTo" text, "creator" character varying, "description" text, "identifier" character varying, "isReferencedBy" character varying, "issued" character varying, "language" character varying, "license" character varying, "modified" character varying, "publisher" character varying, "relation" character varying, "title" character varying, "type" character varying, "hasVersion" text, "isVersionOf" character varying, "version" character varying, "hasCurrentVersion" character varying, "previousVersion" character varying, "extraProps" text, "hasPolicy" text, CONSTRAINT "PK_e2894a5867e06ae2e8889f1173f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dataservice" ("createdDate" TIMESTAMP NOT NULL DEFAULT now(), "modifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "deletedDate" TIMESTAMP, "id" character varying NOT NULL, "endpointDescription" character varying, "endpointURL" character varying, "extraProps" text, "CatalogId" character varying, "ResourceId" character varying, CONSTRAINT "REL_edb6e4ec31e7b2b836b2557ae8" UNIQUE ("ResourceId"), CONSTRAINT "PK_2be5f6bd81de18c097c66b9dcf9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "distribution" ("createdDate" TIMESTAMP NOT NULL DEFAULT now(), "modifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "deletedDate" TIMESTAMP, "id" character varying NOT NULL, "accessURL" character varying, "byteSize" character varying, "compressFormat" character varying, "downloadURL" character varying, "mediaType" character varying, "packageFormat" character varying, "spatialResolutionInMeters" character varying, "temporalResolution" character varying, "conformsTo" text, "description" text, "format" character varying, "issued" character varying, "modified" character varying, "title" character varying, "extraProps" text, "hasPolicy" text, CONSTRAINT "PK_187eaf203ccf9018df51b40108c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dataset" ("createdDate" TIMESTAMP NOT NULL DEFAULT now(), "modifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "deletedDate" TIMESTAMP, "id" character varying NOT NULL, "spatialResolutionInMeters" character varying, "temporalResolution" character varying, "accrualPeriodicity" character varying, "spatial" character varying, "temporal" character varying, "wasGeneratedBy" text, "hasCodingSystem" text, "numberOfRecords" integer, "numberOfUniqueIndividuals" integer, "healthTheme" text, "extraProps" text, "ResourceId" character varying, "DataPlaneIdentifier" character varying, "CatalogId" character varying, "SampleId" character varying, CONSTRAINT "REL_fb246beee7540052e424a3a282" UNIQUE ("ResourceId"), CONSTRAINT "PK_36c1c67adb3d1dd69ae57f18913" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "catalogrecord" ("createdDate" TIMESTAMP NOT NULL DEFAULT now(), "modifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "deletedDate" TIMESTAMP, "id" character varying NOT NULL, "conformsTo" text, "description" text, "issued" character varying, "modified" character varying, "title" character varying, "extraProps" text, "CatalogId" character varying, "PrimaryTopicId" character varying, CONSTRAINT "REL_d07d296415ee6b72ba38eb2cf0" UNIQUE ("PrimaryTopicId"), CONSTRAINT "PK_c6864aa0dc06fa1818c836a4f5f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "catalog" ("createdDate" TIMESTAMP NOT NULL DEFAULT now(), "modifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "deletedDate" TIMESTAMP, "id" character varying NOT NULL, "themeTaxonomy" character varying, "homepage" character varying, "extraProps" text, "DatasetId" character varying, CONSTRAINT "REL_ae4c17c4f58d88f715d979ffc7" UNIQUE ("DatasetId"), CONSTRAINT "PK_782754bded12b4e75ad4afff913" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."constraint_dao_type_enum" AS ENUM('ATOMIC', 'LOGICAL')`);
        await queryRunner.query(`CREATE TYPE "public"."constraint_dao_datatype_enum" AS ENUM('STRING', 'URI', 'NUMBER', 'DATE', 'DATETIME', 'DIF_INPUT_DESCRIPTOR')`);
        await queryRunner.query(`CREATE TABLE "constraint_dao" ("id" SERIAL NOT NULL, "type" "public"."constraint_dao_type_enum" NOT NULL, "title" character varying NOT NULL, "description" character varying, "logicalOperator" character varying, "leftOperand" character varying, "operator" character varying, "contextPath" character varying, "evaluable" text, "dataType" "public"."constraint_dao_datatype_enum", CONSTRAINT "UQ_d487a181b8f56c170a86fe53c87" UNIQUE ("leftOperand"), CONSTRAINT "PK_90364c4023769e9a14b9a868640" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rule_dao" ("createdDate" TIMESTAMP NOT NULL DEFAULT now(), "modifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "deletedDate" TIMESTAMP, "id" SERIAL NOT NULL, "action" text NOT NULL, "assignee" text, CONSTRAINT "PK_f63ea04682f2cdec3f1dc76ea08" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "agreement_dao" ("id" character varying NOT NULL, "agreement" text NOT NULL, "negotiationId" character varying NOT NULL, "localSignature" text, "remoteSignature" text, CONSTRAINT "PK_dac74ae3fa6abc50d68adfc8213" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "transfer_monitor_dao" ("id" character varying NOT NULL, "lastContext" text NOT NULL, "lastDecision" text NOT NULL, "agreementId" character varying, CONSTRAINT "PK_ed523ae79dfa36953ea93b1dbe0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."negotationProcessEvent_state_enum" AS ENUM('dspace:REQUESTED', 'dspace:OFFERED', 'dspace:ACCEPTED', 'dspace:AGREED', 'dspace:VERIFIED', 'dspace:FINALIZED', 'dspace:TERMINATED')`);
        await queryRunner.query(`CREATE TABLE "negotationProcessEvent" ("createdDate" TIMESTAMP NOT NULL DEFAULT now(), "modifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "deletedDate" TIMESTAMP, "_id" SERIAL NOT NULL, "time" character varying NOT NULL, "state" "public"."negotationProcessEvent_state_enum" NOT NULL, "localMessage" character varying, "code" character varying, "reason" text, "agreementMessage" character varying, "verification" text, "hashedMessage" text, "type" character varying NOT NULL, "DetailLocalId" character varying, CONSTRAINT "PK_ccf8fe5b23ac78ec5fd9a516702" PRIMARY KEY ("_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."negotiationDetail_state_enum" AS ENUM('dspace:REQUESTED', 'dspace:OFFERED', 'dspace:ACCEPTED', 'dspace:AGREED', 'dspace:VERIFIED', 'dspace:FINALIZED', 'dspace:TERMINATED')`);
        await queryRunner.query(`CREATE TABLE "negotiationDetail" ("createdDate" TIMESTAMP NOT NULL DEFAULT now(), "modifiedDate" TIMESTAMP NOT NULL DEFAULT now(), "deletedDate" TIMESTAMP, "localId" character varying NOT NULL, "remoteId" character varying NOT NULL, "remoteParty" character varying NOT NULL, "role" character varying NOT NULL, "remoteAddress" character varying NOT NULL, "state" "public"."negotiationDetail_state_enum" NOT NULL, "dataSet" character varying NOT NULL, "offer" text, "agreementDaoId" character varying, CONSTRAINT "PK_027d8af43342f22e75cc3a9a379" PRIMARY KEY ("localId"))`);
        await queryRunner.query(`CREATE TABLE "dataservice__serves_dataset_dataset" ("dataserviceId" character varying NOT NULL, "datasetId" character varying NOT NULL, CONSTRAINT "PK_db23d3971eb068955148e7271c9" PRIMARY KEY ("dataserviceId", "datasetId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ddeeddd6e960fcfeb7f6b12eff" ON "dataservice__serves_dataset_dataset" ("dataserviceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bdc1c1c31507d335ef1c55b70b" ON "dataservice__serves_dataset_dataset" ("datasetId") `);
        await queryRunner.query(`CREATE TABLE "distribution__access_service_dataservice" ("distributionId" character varying NOT NULL, "dataserviceId" character varying NOT NULL, CONSTRAINT "PK_bef03027266710343566eb1a2ee" PRIMARY KEY ("distributionId", "dataserviceId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d7768a9486fef84e78f7082e70" ON "distribution__access_service_dataservice" ("distributionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_715a34ea9e42548a9b4042935b" ON "distribution__access_service_dataservice" ("dataserviceId") `);
        await queryRunner.query(`CREATE TABLE "dataset__distribution_distribution" ("datasetId" character varying NOT NULL, "distributionId" character varying NOT NULL, CONSTRAINT "PK_961853a4d89e19dbb00eebdf228" PRIMARY KEY ("datasetId", "distributionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4327472fe98329bc616b92c878" ON "dataset__distribution_distribution" ("datasetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8fe4fc6ef86e884d7bdd3182b2" ON "dataset__distribution_distribution" ("distributionId") `);
        await queryRunner.query(`CREATE TABLE "constraint_dao_constraints_constraint_dao" ("constraintDaoId_1" integer NOT NULL, "constraintDaoId_2" integer NOT NULL, CONSTRAINT "PK_c2d69ae87555fd4d1aa3e54afb6" PRIMARY KEY ("constraintDaoId_1", "constraintDaoId_2"))`);
        await queryRunner.query(`CREATE INDEX "IDX_82fbec3376bb07d5cbb8662d78" ON "constraint_dao_constraints_constraint_dao" ("constraintDaoId_1") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d597d53dd5c069cdc109e572f" ON "constraint_dao_constraints_constraint_dao" ("constraintDaoId_2") `);
        await queryRunner.query(`CREATE TABLE "rule_dao_constraints_constraint_dao" ("ruleDaoId" integer NOT NULL, "constraintDaoId" integer NOT NULL, CONSTRAINT "PK_5265f7f31a82b9f805e6ff06f64" PRIMARY KEY ("ruleDaoId", "constraintDaoId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e6a3aa44c390430df2c95aba98" ON "rule_dao_constraints_constraint_dao" ("ruleDaoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b5aa628f646e589f9bd217572c" ON "rule_dao_constraints_constraint_dao" ("constraintDaoId") `);
        await queryRunner.query(`CREATE TABLE "rule_dao_duties_rule_dao" ("ruleDaoId_1" integer NOT NULL, "ruleDaoId_2" integer NOT NULL, CONSTRAINT "PK_a9674f67c4fe8bf283ad0bb319a" PRIMARY KEY ("ruleDaoId_1", "ruleDaoId_2"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4e4f03d5f894766ea199f8a881" ON "rule_dao_duties_rule_dao" ("ruleDaoId_1") `);
        await queryRunner.query(`CREATE INDEX "IDX_26bd571fe9f49193e621fbb19e" ON "rule_dao_duties_rule_dao" ("ruleDaoId_2") `);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" ADD CONSTRAINT "FK_aa9f090675dd25f4eda56555e10" FOREIGN KEY ("StatusLocalId") REFERENCES "transfer_detail_dao"("localId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dataservice" ADD CONSTRAINT "FK_b643e08c658adf8d62d6cb1aa60" FOREIGN KEY ("CatalogId") REFERENCES "catalog"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dataservice" ADD CONSTRAINT "FK_edb6e4ec31e7b2b836b2557ae85" FOREIGN KEY ("ResourceId") REFERENCES "resource"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dataset" ADD CONSTRAINT "FK_fb246beee7540052e424a3a2826" FOREIGN KEY ("ResourceId") REFERENCES "resource"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dataset" ADD CONSTRAINT "FK_5ffc12673c1b713c2f00e7ed722" FOREIGN KEY ("DataPlaneIdentifier") REFERENCES "dataplanedetails"("identifier") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dataset" ADD CONSTRAINT "FK_f9caedee7cda920ac231bcd10d3" FOREIGN KEY ("CatalogId") REFERENCES "catalog"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dataset" ADD CONSTRAINT "FK_74a6000c286b98882c56ab34833" FOREIGN KEY ("SampleId") REFERENCES "distribution"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalogrecord" ADD CONSTRAINT "FK_9f2fe30d4d7c2dcb6eb0bc3bfe5" FOREIGN KEY ("CatalogId") REFERENCES "catalog"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalogrecord" ADD CONSTRAINT "FK_d07d296415ee6b72ba38eb2cf0a" FOREIGN KEY ("PrimaryTopicId") REFERENCES "resource"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "catalog" ADD CONSTRAINT "FK_ae4c17c4f58d88f715d979ffc72" FOREIGN KEY ("DatasetId") REFERENCES "dataset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_monitor_dao" ADD CONSTRAINT "FK_e37c1bed0f0095adfa2ccd76c4c" FOREIGN KEY ("agreementId") REFERENCES "agreement_dao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" ADD CONSTRAINT "FK_421acc1dc8622808e8c99c527f2" FOREIGN KEY ("DetailLocalId") REFERENCES "negotiationDetail"("localId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" ADD CONSTRAINT "FK_9891d479b99e1fa7f5eaace22b7" FOREIGN KEY ("agreementDaoId") REFERENCES "agreement_dao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dataservice__serves_dataset_dataset" ADD CONSTRAINT "FK_ddeeddd6e960fcfeb7f6b12eff3" FOREIGN KEY ("dataserviceId") REFERENCES "dataservice"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "dataservice__serves_dataset_dataset" ADD CONSTRAINT "FK_bdc1c1c31507d335ef1c55b70ba" FOREIGN KEY ("datasetId") REFERENCES "dataset"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "distribution__access_service_dataservice" ADD CONSTRAINT "FK_d7768a9486fef84e78f7082e70f" FOREIGN KEY ("distributionId") REFERENCES "distribution"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "distribution__access_service_dataservice" ADD CONSTRAINT "FK_715a34ea9e42548a9b4042935b1" FOREIGN KEY ("dataserviceId") REFERENCES "dataservice"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "dataset__distribution_distribution" ADD CONSTRAINT "FK_4327472fe98329bc616b92c8781" FOREIGN KEY ("datasetId") REFERENCES "dataset"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "dataset__distribution_distribution" ADD CONSTRAINT "FK_8fe4fc6ef86e884d7bdd3182b2d" FOREIGN KEY ("distributionId") REFERENCES "distribution"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD CONSTRAINT "FK_82fbec3376bb07d5cbb8662d78b" FOREIGN KEY ("constraintDaoId_1") REFERENCES "constraint_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD CONSTRAINT "FK_0d597d53dd5c069cdc109e572f7" FOREIGN KEY ("constraintDaoId_2") REFERENCES "constraint_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD CONSTRAINT "FK_e6a3aa44c390430df2c95aba980" FOREIGN KEY ("ruleDaoId") REFERENCES "rule_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD CONSTRAINT "FK_b5aa628f646e589f9bd217572c3" FOREIGN KEY ("constraintDaoId") REFERENCES "constraint_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "FK_4e4f03d5f894766ea199f8a8813" FOREIGN KEY ("ruleDaoId_1") REFERENCES "rule_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "FK_26bd571fe9f49193e621fbb19e8" FOREIGN KEY ("ruleDaoId_2") REFERENCES "rule_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "FK_26bd571fe9f49193e621fbb19e8"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "FK_4e4f03d5f894766ea199f8a8813"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP CONSTRAINT "FK_b5aa628f646e589f9bd217572c3"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP CONSTRAINT "FK_e6a3aa44c390430df2c95aba980"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP CONSTRAINT "FK_0d597d53dd5c069cdc109e572f7"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP CONSTRAINT "FK_82fbec3376bb07d5cbb8662d78b"`);
        await queryRunner.query(`ALTER TABLE "dataset__distribution_distribution" DROP CONSTRAINT "FK_8fe4fc6ef86e884d7bdd3182b2d"`);
        await queryRunner.query(`ALTER TABLE "dataset__distribution_distribution" DROP CONSTRAINT "FK_4327472fe98329bc616b92c8781"`);
        await queryRunner.query(`ALTER TABLE "distribution__access_service_dataservice" DROP CONSTRAINT "FK_715a34ea9e42548a9b4042935b1"`);
        await queryRunner.query(`ALTER TABLE "distribution__access_service_dataservice" DROP CONSTRAINT "FK_d7768a9486fef84e78f7082e70f"`);
        await queryRunner.query(`ALTER TABLE "dataservice__serves_dataset_dataset" DROP CONSTRAINT "FK_bdc1c1c31507d335ef1c55b70ba"`);
        await queryRunner.query(`ALTER TABLE "dataservice__serves_dataset_dataset" DROP CONSTRAINT "FK_ddeeddd6e960fcfeb7f6b12eff3"`);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" DROP CONSTRAINT "FK_9891d479b99e1fa7f5eaace22b7"`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" DROP CONSTRAINT "FK_421acc1dc8622808e8c99c527f2"`);
        await queryRunner.query(`ALTER TABLE "transfer_monitor_dao" DROP CONSTRAINT "FK_e37c1bed0f0095adfa2ccd76c4c"`);
        await queryRunner.query(`ALTER TABLE "catalog" DROP CONSTRAINT "FK_ae4c17c4f58d88f715d979ffc72"`);
        await queryRunner.query(`ALTER TABLE "catalogrecord" DROP CONSTRAINT "FK_d07d296415ee6b72ba38eb2cf0a"`);
        await queryRunner.query(`ALTER TABLE "catalogrecord" DROP CONSTRAINT "FK_9f2fe30d4d7c2dcb6eb0bc3bfe5"`);
        await queryRunner.query(`ALTER TABLE "dataset" DROP CONSTRAINT "FK_74a6000c286b98882c56ab34833"`);
        await queryRunner.query(`ALTER TABLE "dataset" DROP CONSTRAINT "FK_f9caedee7cda920ac231bcd10d3"`);
        await queryRunner.query(`ALTER TABLE "dataset" DROP CONSTRAINT "FK_5ffc12673c1b713c2f00e7ed722"`);
        await queryRunner.query(`ALTER TABLE "dataset" DROP CONSTRAINT "FK_fb246beee7540052e424a3a2826"`);
        await queryRunner.query(`ALTER TABLE "dataservice" DROP CONSTRAINT "FK_edb6e4ec31e7b2b836b2557ae85"`);
        await queryRunner.query(`ALTER TABLE "dataservice" DROP CONSTRAINT "FK_b643e08c658adf8d62d6cb1aa60"`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" DROP CONSTRAINT "FK_aa9f090675dd25f4eda56555e10"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26bd571fe9f49193e621fbb19e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e4f03d5f894766ea199f8a881"`);
        await queryRunner.query(`DROP TABLE "rule_dao_duties_rule_dao"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5aa628f646e589f9bd217572c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6a3aa44c390430df2c95aba98"`);
        await queryRunner.query(`DROP TABLE "rule_dao_constraints_constraint_dao"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d597d53dd5c069cdc109e572f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82fbec3376bb07d5cbb8662d78"`);
        await queryRunner.query(`DROP TABLE "constraint_dao_constraints_constraint_dao"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8fe4fc6ef86e884d7bdd3182b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4327472fe98329bc616b92c878"`);
        await queryRunner.query(`DROP TABLE "dataset__distribution_distribution"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_715a34ea9e42548a9b4042935b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7768a9486fef84e78f7082e70"`);
        await queryRunner.query(`DROP TABLE "distribution__access_service_dataservice"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bdc1c1c31507d335ef1c55b70b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ddeeddd6e960fcfeb7f6b12eff"`);
        await queryRunner.query(`DROP TABLE "dataservice__serves_dataset_dataset"`);
        await queryRunner.query(`DROP TABLE "negotiationDetail"`);
        await queryRunner.query(`DROP TYPE "public"."negotiationDetail_state_enum"`);
        await queryRunner.query(`DROP TABLE "negotationProcessEvent"`);
        await queryRunner.query(`DROP TYPE "public"."negotationProcessEvent_state_enum"`);
        await queryRunner.query(`DROP TABLE "transfer_monitor_dao"`);
        await queryRunner.query(`DROP TABLE "agreement_dao"`);
        await queryRunner.query(`DROP TABLE "rule_dao"`);
        await queryRunner.query(`DROP TABLE "constraint_dao"`);
        await queryRunner.query(`DROP TYPE "public"."constraint_dao_datatype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."constraint_dao_type_enum"`);
        await queryRunner.query(`DROP TABLE "catalog"`);
        await queryRunner.query(`DROP TABLE "catalogrecord"`);
        await queryRunner.query(`DROP TABLE "dataset"`);
        await queryRunner.query(`DROP TABLE "distribution"`);
        await queryRunner.query(`DROP TABLE "dataservice"`);
        await queryRunner.query(`DROP TABLE "resource"`);
        await queryRunner.query(`DROP TABLE "dataplanedetails"`);
        await queryRunner.query(`DROP TYPE "public"."dataplanedetails_health_enum"`);
        await queryRunner.query(`DROP TABLE "registry"`);
        await queryRunner.query(`DROP TABLE "transfer_detail_dao"`);
        await queryRunner.query(`DROP TYPE "public"."transfer_detail_dao_state_enum"`);
        await queryRunner.query(`DROP TABLE "transfer_event_dao"`);
        await queryRunner.query(`DROP TYPE "public"."transfer_event_dao_state_enum"`);
    }

}
