import { MigrationInterface, QueryRunner } from "typeorm";

export class Sqlite20250509141230 implements MigrationInterface {
    name = 'Sqlite20250509141230'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_transfer_event_dao" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "_id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "time" varchar NOT NULL, "state" varchar CHECK( "state" IN ('REQUESTED','STARTED','TERMINATED','COMPLETED','SUSPENDED') ) NOT NULL, "localMessage" varchar, "code" varchar, "reason" text, "type" varchar NOT NULL, "StatusLocalId" varchar, CONSTRAINT "FK_aa9f090675dd25f4eda56555e10" FOREIGN KEY ("StatusLocalId") REFERENCES "transfer_detail_dao" ("localId") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_transfer_event_dao"("createdDate", "modifiedDate", "deletedDate", "_id", "time", "state", "localMessage", "code", "reason", "type", "StatusLocalId") SELECT "createdDate", "modifiedDate", "deletedDate", "_id", "time", "state", "localMessage", "code", "reason", "type", "StatusLocalId" FROM "transfer_event_dao"`);
        await queryRunner.query(`DROP TABLE "transfer_event_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_transfer_event_dao" RENAME TO "transfer_event_dao"`);
        await queryRunner.query(`CREATE TABLE "temporary_transfer_detail_dao" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "localId" varchar PRIMARY KEY NOT NULL, "remoteId" varchar, "role" varchar NOT NULL, "remoteAddress" varchar NOT NULL, "remoteParty" varchar NOT NULL, "state" varchar CHECK( "state" IN ('REQUESTED','STARTED','TERMINATED','COMPLETED','SUSPENDED') ) NOT NULL, "process" text NOT NULL, "agreementId" varchar NOT NULL, "format" varchar, "dataAddress" text, "dataPlaneTransfer" text NOT NULL)`);
        await queryRunner.query(`INSERT INTO "temporary_transfer_detail_dao"("createdDate", "modifiedDate", "deletedDate", "localId", "remoteId", "role", "remoteAddress", "remoteParty", "state", "process", "agreementId", "format", "dataAddress", "dataPlaneTransfer") SELECT "createdDate", "modifiedDate", "deletedDate", "localId", "remoteId", "role", "remoteAddress", "remoteParty", "state", "process", "agreementId", "format", "dataAddress", "dataPlaneTransfer" FROM "transfer_detail_dao"`);
        await queryRunner.query(`DROP TABLE "transfer_detail_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_transfer_detail_dao" RENAME TO "transfer_detail_dao"`);
        await queryRunner.query(`CREATE TABLE "temporary_negotationProcessEvent" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "_id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "time" varchar NOT NULL, "state" varchar CHECK( "state" IN ('REQUESTED','OFFERED','ACCEPTED','AGREED','VERIFIED','FINALIZED','TERMINATED') ) NOT NULL, "localMessage" varchar, "code" varchar, "reason" text, "agreementMessage" varchar, "verification" text, "hashedMessage" text, "type" varchar NOT NULL, "DetailLocalId" varchar, CONSTRAINT "FK_421acc1dc8622808e8c99c527f2" FOREIGN KEY ("DetailLocalId") REFERENCES "negotiationDetail" ("localId") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_negotationProcessEvent"("createdDate", "modifiedDate", "deletedDate", "_id", "time", "state", "localMessage", "code", "reason", "agreementMessage", "verification", "hashedMessage", "type", "DetailLocalId") SELECT "createdDate", "modifiedDate", "deletedDate", "_id", "time", "state", "localMessage", "code", "reason", "agreementMessage", "verification", "hashedMessage", "type", "DetailLocalId" FROM "negotationProcessEvent"`);
        await queryRunner.query(`DROP TABLE "negotationProcessEvent"`);
        await queryRunner.query(`ALTER TABLE "temporary_negotationProcessEvent" RENAME TO "negotationProcessEvent"`);
        await queryRunner.query(`CREATE TABLE "temporary_negotiationDetail" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "localId" varchar PRIMARY KEY NOT NULL, "remoteId" varchar NOT NULL, "remoteParty" varchar NOT NULL, "role" varchar NOT NULL, "remoteAddress" varchar NOT NULL, "state" varchar CHECK( "state" IN ('REQUESTED','OFFERED','ACCEPTED','AGREED','VERIFIED','FINALIZED','TERMINATED') ) NOT NULL, "dataSet" varchar NOT NULL, "offer" text, "agreementDaoId" varchar, CONSTRAINT "FK_9891d479b99e1fa7f5eaace22b7" FOREIGN KEY ("agreementDaoId") REFERENCES "agreement_dao" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_negotiationDetail"("createdDate", "modifiedDate", "deletedDate", "localId", "remoteId", "remoteParty", "role", "remoteAddress", "state", "dataSet", "offer", "agreementDaoId") SELECT "createdDate", "modifiedDate", "deletedDate", "localId", "remoteId", "remoteParty", "role", "remoteAddress", "state", "dataSet", "offer", "agreementDaoId" FROM "negotiationDetail"`);
        await queryRunner.query(`DROP TABLE "negotiationDetail"`);
        await queryRunner.query(`ALTER TABLE "temporary_negotiationDetail" RENAME TO "negotiationDetail"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "negotiationDetail" RENAME TO "temporary_negotiationDetail"`);
        await queryRunner.query(`CREATE TABLE "negotiationDetail" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "localId" varchar PRIMARY KEY NOT NULL, "remoteId" varchar NOT NULL, "remoteParty" varchar NOT NULL, "role" varchar NOT NULL, "remoteAddress" varchar NOT NULL, "state" varchar CHECK( "state" IN ('dspace:REQUESTED','dspace:OFFERED','dspace:ACCEPTED','dspace:AGREED','dspace:VERIFIED','dspace:FINALIZED','dspace:TERMINATED') ) NOT NULL, "dataSet" varchar NOT NULL, "offer" text, "agreementDaoId" varchar, CONSTRAINT "FK_9891d479b99e1fa7f5eaace22b7" FOREIGN KEY ("agreementDaoId") REFERENCES "agreement_dao" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "negotiationDetail"("createdDate", "modifiedDate", "deletedDate", "localId", "remoteId", "remoteParty", "role", "remoteAddress", "state", "dataSet", "offer", "agreementDaoId") SELECT "createdDate", "modifiedDate", "deletedDate", "localId", "remoteId", "remoteParty", "role", "remoteAddress", "state", "dataSet", "offer", "agreementDaoId" FROM "temporary_negotiationDetail"`);
        await queryRunner.query(`DROP TABLE "temporary_negotiationDetail"`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" RENAME TO "temporary_negotationProcessEvent"`);
        await queryRunner.query(`CREATE TABLE "negotationProcessEvent" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "_id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "time" varchar NOT NULL, "state" varchar CHECK( "state" IN ('dspace:REQUESTED','dspace:OFFERED','dspace:ACCEPTED','dspace:AGREED','dspace:VERIFIED','dspace:FINALIZED','dspace:TERMINATED') ) NOT NULL, "localMessage" varchar, "code" varchar, "reason" text, "agreementMessage" varchar, "verification" text, "hashedMessage" text, "type" varchar NOT NULL, "DetailLocalId" varchar, CONSTRAINT "FK_421acc1dc8622808e8c99c527f2" FOREIGN KEY ("DetailLocalId") REFERENCES "negotiationDetail" ("localId") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "negotationProcessEvent"("createdDate", "modifiedDate", "deletedDate", "_id", "time", "state", "localMessage", "code", "reason", "agreementMessage", "verification", "hashedMessage", "type", "DetailLocalId") SELECT "createdDate", "modifiedDate", "deletedDate", "_id", "time", "state", "localMessage", "code", "reason", "agreementMessage", "verification", "hashedMessage", "type", "DetailLocalId" FROM "temporary_negotationProcessEvent"`);
        await queryRunner.query(`DROP TABLE "temporary_negotationProcessEvent"`);
        await queryRunner.query(`ALTER TABLE "transfer_detail_dao" RENAME TO "temporary_transfer_detail_dao"`);
        await queryRunner.query(`CREATE TABLE "transfer_detail_dao" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "localId" varchar PRIMARY KEY NOT NULL, "remoteId" varchar, "role" varchar NOT NULL, "remoteAddress" varchar NOT NULL, "remoteParty" varchar NOT NULL, "state" varchar CHECK( "state" IN ('dspace:REQUESTED','dspace:STARTED','dspace:TERMINATED','dspace:COMPLETED','dspace:SUSPENDED') ) NOT NULL, "process" text NOT NULL, "agreementId" varchar NOT NULL, "format" varchar, "dataAddress" text, "dataPlaneTransfer" text NOT NULL)`);
        await queryRunner.query(`INSERT INTO "transfer_detail_dao"("createdDate", "modifiedDate", "deletedDate", "localId", "remoteId", "role", "remoteAddress", "remoteParty", "state", "process", "agreementId", "format", "dataAddress", "dataPlaneTransfer") SELECT "createdDate", "modifiedDate", "deletedDate", "localId", "remoteId", "role", "remoteAddress", "remoteParty", "state", "process", "agreementId", "format", "dataAddress", "dataPlaneTransfer" FROM "temporary_transfer_detail_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_transfer_detail_dao"`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" RENAME TO "temporary_transfer_event_dao"`);
        await queryRunner.query(`CREATE TABLE "transfer_event_dao" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "_id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "time" varchar NOT NULL, "state" varchar CHECK( "state" IN ('dspace:REQUESTED','dspace:STARTED','dspace:TERMINATED','dspace:COMPLETED','dspace:SUSPENDED') ) NOT NULL, "localMessage" varchar, "code" varchar, "reason" text, "type" varchar NOT NULL, "StatusLocalId" varchar, CONSTRAINT "FK_aa9f090675dd25f4eda56555e10" FOREIGN KEY ("StatusLocalId") REFERENCES "transfer_detail_dao" ("localId") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "transfer_event_dao"("createdDate", "modifiedDate", "deletedDate", "_id", "time", "state", "localMessage", "code", "reason", "type", "StatusLocalId") SELECT "createdDate", "modifiedDate", "deletedDate", "_id", "time", "state", "localMessage", "code", "reason", "type", "StatusLocalId" FROM "temporary_transfer_event_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_transfer_event_dao"`);
    }

}
