import { MigrationInterface, QueryRunner } from "typeorm";

export class Sqlite20250523130328 implements MigrationInterface {
    name = 'Sqlite20250523130328'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_transfer_detail_dao" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "localId" varchar PRIMARY KEY NOT NULL, "remoteId" varchar, "role" varchar NOT NULL, "remoteAddress" varchar NOT NULL, "remoteParty" varchar NOT NULL, "state" varchar CHECK( "state" IN ('REQUESTED','STARTED','TERMINATED','COMPLETED','SUSPENDED') ) NOT NULL, "agreementId" varchar NOT NULL, "format" varchar, "dataAddress" text, "dataPlaneTransfer" text NOT NULL)`);
        await queryRunner.query(`INSERT INTO "temporary_transfer_detail_dao"("createdDate", "modifiedDate", "deletedDate", "localId", "remoteId", "role", "remoteAddress", "remoteParty", "state", "agreementId", "format", "dataAddress", "dataPlaneTransfer") SELECT "createdDate", "modifiedDate", "deletedDate", "localId", "remoteId", "role", "remoteAddress", "remoteParty", "state", "agreementId", "format", "dataAddress", "dataPlaneTransfer" FROM "transfer_detail_dao"`);
        await queryRunner.query(`DROP TABLE "transfer_detail_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_transfer_detail_dao" RENAME TO "transfer_detail_dao"`);
        await queryRunner.query(`CREATE TABLE "temporary_distribution" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "accessURL" varchar, "byteSize" varchar, "compressFormat" varchar, "downloadURL" varchar, "mediaType" varchar, "packageFormat" varchar, "spatialResolutionInMeters" varchar, "temporalResolution" varchar, "conformsTo" text, "description" text, "format" varchar, "issued" varchar, "modified" varchar, "title" varchar, "extraProps" text, "hasPolicy" text, "AccessServiceId" varchar)`);
        await queryRunner.query(`INSERT INTO "temporary_distribution"("createdDate", "modifiedDate", "deletedDate", "id", "accessURL", "byteSize", "compressFormat", "downloadURL", "mediaType", "packageFormat", "spatialResolutionInMeters", "temporalResolution", "conformsTo", "description", "format", "issued", "modified", "title", "extraProps", "hasPolicy") SELECT "createdDate", "modifiedDate", "deletedDate", "id", "accessURL", "byteSize", "compressFormat", "downloadURL", "mediaType", "packageFormat", "spatialResolutionInMeters", "temporalResolution", "conformsTo", "description", "format", "issued", "modified", "title", "extraProps", "hasPolicy" FROM "distribution"`);
        await queryRunner.query(`DROP TABLE "distribution"`);
        await queryRunner.query(`ALTER TABLE "temporary_distribution" RENAME TO "distribution"`);
        await queryRunner.query(`CREATE TABLE "temporary_catalog" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "themeTaxonomy" varchar, "homepage" varchar, "extraProps" text, "DatasetId" varchar, "participantId" varchar, CONSTRAINT "REL_ae4c17c4f58d88f715d979ffc7" UNIQUE ("DatasetId"), CONSTRAINT "FK_ae4c17c4f58d88f715d979ffc72" FOREIGN KEY ("DatasetId") REFERENCES "dataset" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_catalog"("createdDate", "modifiedDate", "deletedDate", "id", "themeTaxonomy", "homepage", "extraProps", "DatasetId") SELECT "createdDate", "modifiedDate", "deletedDate", "id", "themeTaxonomy", "homepage", "extraProps", "DatasetId" FROM "catalog"`);
        await queryRunner.query(`DROP TABLE "catalog"`);
        await queryRunner.query(`ALTER TABLE "temporary_catalog" RENAME TO "catalog"`);
        await queryRunner.query(`CREATE TABLE "temporary_distribution" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "accessURL" varchar, "byteSize" varchar, "compressFormat" varchar, "downloadURL" varchar, "mediaType" varchar, "packageFormat" varchar, "spatialResolutionInMeters" varchar, "temporalResolution" varchar, "conformsTo" text, "description" text, "format" varchar, "issued" varchar, "modified" varchar, "title" varchar, "extraProps" text, "hasPolicy" text, "AccessServiceId" varchar, CONSTRAINT "FK_f9e82f5a8f847de7347594104e9" FOREIGN KEY ("AccessServiceId") REFERENCES "dataservice" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_distribution"("createdDate", "modifiedDate", "deletedDate", "id", "accessURL", "byteSize", "compressFormat", "downloadURL", "mediaType", "packageFormat", "spatialResolutionInMeters", "temporalResolution", "conformsTo", "description", "format", "issued", "modified", "title", "extraProps", "hasPolicy", "AccessServiceId") SELECT "createdDate", "modifiedDate", "deletedDate", "id", "accessURL", "byteSize", "compressFormat", "downloadURL", "mediaType", "packageFormat", "spatialResolutionInMeters", "temporalResolution", "conformsTo", "description", "format", "issued", "modified", "title", "extraProps", "hasPolicy", "AccessServiceId" FROM "distribution"`);
        await queryRunner.query(`DROP TABLE "distribution"`);
        await queryRunner.query(`ALTER TABLE "temporary_distribution" RENAME TO "distribution"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "distribution" RENAME TO "temporary_distribution"`);
        await queryRunner.query(`CREATE TABLE "distribution" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "accessURL" varchar, "byteSize" varchar, "compressFormat" varchar, "downloadURL" varchar, "mediaType" varchar, "packageFormat" varchar, "spatialResolutionInMeters" varchar, "temporalResolution" varchar, "conformsTo" text, "description" text, "format" varchar, "issued" varchar, "modified" varchar, "title" varchar, "extraProps" text, "hasPolicy" text, "AccessServiceId" varchar)`);
        await queryRunner.query(`INSERT INTO "distribution"("createdDate", "modifiedDate", "deletedDate", "id", "accessURL", "byteSize", "compressFormat", "downloadURL", "mediaType", "packageFormat", "spatialResolutionInMeters", "temporalResolution", "conformsTo", "description", "format", "issued", "modified", "title", "extraProps", "hasPolicy", "AccessServiceId") SELECT "createdDate", "modifiedDate", "deletedDate", "id", "accessURL", "byteSize", "compressFormat", "downloadURL", "mediaType", "packageFormat", "spatialResolutionInMeters", "temporalResolution", "conformsTo", "description", "format", "issued", "modified", "title", "extraProps", "hasPolicy", "AccessServiceId" FROM "temporary_distribution"`);
        await queryRunner.query(`DROP TABLE "temporary_distribution"`);
        await queryRunner.query(`ALTER TABLE "catalog" RENAME TO "temporary_catalog"`);
        await queryRunner.query(`CREATE TABLE "catalog" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "themeTaxonomy" varchar, "homepage" varchar, "extraProps" text, "DatasetId" varchar, CONSTRAINT "REL_ae4c17c4f58d88f715d979ffc7" UNIQUE ("DatasetId"), CONSTRAINT "FK_ae4c17c4f58d88f715d979ffc72" FOREIGN KEY ("DatasetId") REFERENCES "dataset" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "catalog"("createdDate", "modifiedDate", "deletedDate", "id", "themeTaxonomy", "homepage", "extraProps", "DatasetId") SELECT "createdDate", "modifiedDate", "deletedDate", "id", "themeTaxonomy", "homepage", "extraProps", "DatasetId" FROM "temporary_catalog"`);
        await queryRunner.query(`DROP TABLE "temporary_catalog"`);
        await queryRunner.query(`ALTER TABLE "distribution" RENAME TO "temporary_distribution"`);
        await queryRunner.query(`CREATE TABLE "distribution" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "id" varchar PRIMARY KEY NOT NULL, "accessURL" varchar, "byteSize" varchar, "compressFormat" varchar, "downloadURL" varchar, "mediaType" varchar, "packageFormat" varchar, "spatialResolutionInMeters" varchar, "temporalResolution" varchar, "conformsTo" text, "description" text, "format" varchar, "issued" varchar, "modified" varchar, "title" varchar, "extraProps" text, "hasPolicy" text)`);
        await queryRunner.query(`INSERT INTO "distribution"("createdDate", "modifiedDate", "deletedDate", "id", "accessURL", "byteSize", "compressFormat", "downloadURL", "mediaType", "packageFormat", "spatialResolutionInMeters", "temporalResolution", "conformsTo", "description", "format", "issued", "modified", "title", "extraProps", "hasPolicy") SELECT "createdDate", "modifiedDate", "deletedDate", "id", "accessURL", "byteSize", "compressFormat", "downloadURL", "mediaType", "packageFormat", "spatialResolutionInMeters", "temporalResolution", "conformsTo", "description", "format", "issued", "modified", "title", "extraProps", "hasPolicy" FROM "temporary_distribution"`);
        await queryRunner.query(`DROP TABLE "temporary_distribution"`);
        await queryRunner.query(`ALTER TABLE "transfer_detail_dao" RENAME TO "temporary_transfer_detail_dao"`);
        await queryRunner.query(`CREATE TABLE "transfer_detail_dao" ("createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "localId" varchar PRIMARY KEY NOT NULL, "remoteId" varchar, "role" varchar NOT NULL, "remoteAddress" varchar NOT NULL, "remoteParty" varchar NOT NULL, "state" varchar CHECK( "state" IN ('REQUESTED','STARTED','TERMINATED','COMPLETED','SUSPENDED') ) NOT NULL, "process" text NOT NULL, "agreementId" varchar NOT NULL, "format" varchar, "dataAddress" text, "dataPlaneTransfer" text NOT NULL)`);
        await queryRunner.query(`INSERT INTO "transfer_detail_dao"("createdDate", "modifiedDate", "deletedDate", "localId", "remoteId", "role", "remoteAddress", "remoteParty", "state", "agreementId", "format", "dataAddress", "dataPlaneTransfer") SELECT "createdDate", "modifiedDate", "deletedDate", "localId", "remoteId", "role", "remoteAddress", "remoteParty", "state", "agreementId", "format", "dataAddress", "dataPlaneTransfer" FROM "temporary_transfer_detail_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_transfer_detail_dao"`);
    }

}
