import { MigrationInterface, QueryRunner } from "typeorm";

export class Postgres20260202164735 implements MigrationInterface {
    name = 'Postgres20260202164735'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "dataset" DROP CONSTRAINT "FK_5ffc12673c1b713c2f00e7ed722"`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" DROP CONSTRAINT "FK_aa9f090675dd25f4eda56555e10"`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" DROP CONSTRAINT "FK_421acc1dc8622808e8c99c527f2"`);
        await queryRunner.query(`ALTER TABLE "dataset" RENAME COLUMN "DataPlaneIdentifier" TO "DataPlaneId"`);
        await queryRunner.query(`ALTER TABLE "dataplanedetails" DROP CONSTRAINT "PK_a47df13049c0a46016d2475cc58"`);
        // await queryRunner.query(`ALTER TABLE "dataplanedetails" DROP COLUMN "identifier"`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" DROP CONSTRAINT "PK_312cf9b90f13412429277e788cc"`);
        // await queryRunner.query(`ALTER TABLE "transfer_event_dao" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" DROP COLUMN "StatusLocalId"`);
        await queryRunner.query(`ALTER TABLE "transfer_detail_dao" DROP CONSTRAINT "PK_cdd0938967466ddfea5dc2400df"`);
        // await queryRunner.query(`ALTER TABLE "transfer_detail_dao" DROP COLUMN "localId"`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" DROP CONSTRAINT "PK_ccf8fe5b23ac78ec5fd9a516702"`);
        // await queryRunner.query(`ALTER TABLE "negotationProcessEvent" DROP COLUMN "_id"`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" DROP COLUMN "DetailLocalId"`);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" DROP CONSTRAINT "PK_027d8af43342f22e75cc3a9a379"`);
        // await queryRunner.query(`ALTER TABLE "negotiationDetail" DROP COLUMN "localId"`);
        // await queryRunner.query(`ALTER TABLE "dataplanedetails" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dataplanedetails" RENAME COLUMN "identifier" to "id"`);
        await queryRunner.query(`ALTER TABLE "dataplanedetails" ADD CONSTRAINT "PK_2a55a2a06ab936c80617690a239" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "dataplanedetails" ADD "ownerId" character varying`);
        await queryRunner.query(`ALTER TABLE "dataplanedetails" ADD "ownerIdentifier" character varying`);
        await queryRunner.query(`ALTER TABLE "dataplanedetails" ADD "createdBy" character varying`);
        await queryRunner.query(`ALTER TABLE "dataplanedetails" ADD "tenantId" character varying`);
        // await queryRunner.query(`ALTER TABLE "transfer_event_dao" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" RENAME COLUMN "_id" to "id"`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" ALTER COLUMN "id" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" ADD CONSTRAINT "PK_8a4e6a313a343a174a34db85cf2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" ADD "StatusId" character varying`);
        // await queryRunner.query(`ALTER TABLE "transfer_detail_dao" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transfer_detail_dao" RENAME COLUMN "localId" to "id"`);
        await queryRunner.query(`ALTER TABLE "transfer_detail_dao" ADD CONSTRAINT "PK_857a6eeae43c58e72020f542232" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "transfer_detail_dao" ADD "ownerId" character varying`);
        await queryRunner.query(`ALTER TABLE "transfer_detail_dao" ADD "ownerIdentifier" character varying`);
        await queryRunner.query(`ALTER TABLE "transfer_detail_dao" ADD "createdBy" character varying`);
        await queryRunner.query(`ALTER TABLE "transfer_detail_dao" ADD "tenantId" character varying`);
        await queryRunner.query(`ALTER TABLE "agreement_dao" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "agreement_dao" ADD "modifiedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "agreement_dao" ADD "deletedDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "agreement_dao" ADD "ownerId" character varying`);
        await queryRunner.query(`ALTER TABLE "agreement_dao" ADD "ownerIdentifier" character varying`);
        await queryRunner.query(`ALTER TABLE "agreement_dao" ADD "createdBy" character varying`);
        await queryRunner.query(`ALTER TABLE "agreement_dao" ADD "tenantId" character varying`);
        // await queryRunner.query(`ALTER TABLE "negotationProcessEvent" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" RENAME COLUMN "_id" to "id"`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" ALTER COLUMN "id" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" ADD CONSTRAINT "PK_89d401c15d5490a8e531198bdb5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" ADD "DetailId" character varying`);
        // await queryRunner.query(`ALTER TABLE "negotiationDetail" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" RENAME COLUMN "localId" to "id"`);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" ADD CONSTRAINT "PK_58ba597dd26065f3e65c29520fd" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" ADD "ownerId" character varying`);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" ADD "ownerIdentifier" character varying`);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" ADD "createdBy" character varying`);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" ADD "tenantId" character varying`);
        // Remove rows in "registry" due to incopatible primary key change
        await queryRunner.query(`TRUNCATE "registry"`);
        await queryRunner.query(`ALTER TABLE "registry" DROP CONSTRAINT "PK_2eca29d55a9556d854416df8ce5"`);
        // await queryRunner.query(`ALTER TABLE "registry" DROP COLUMN "id"`);
        // await queryRunner.query(`ALTER TABLE "registry" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "registry" ALTER COLUMN "id" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "registry" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "registry" ADD CONSTRAINT "PK_2eca29d55a9556d854416df8ce5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP CONSTRAINT "FK_82fbec3376bb07d5cbb8662d78b"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP CONSTRAINT "FK_0d597d53dd5c069cdc109e572f7"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP CONSTRAINT "FK_b5aa628f646e589f9bd217572c3"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao" DROP CONSTRAINT "PK_90364c4023769e9a14b9a868640"`);
        // await queryRunner.query(`ALTER TABLE "constraint_dao" DROP COLUMN "id"`);
        // await queryRunner.query(`ALTER TABLE "constraint_dao" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "constraint_dao" ALTER COLUMN "id" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "constraint_dao" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "constraint_dao" ADD CONSTRAINT "PK_90364c4023769e9a14b9a868640" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP CONSTRAINT "FK_e6a3aa44c390430df2c95aba980"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "FK_4e4f03d5f894766ea199f8a8813"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "FK_26bd571fe9f49193e621fbb19e8"`);
        await queryRunner.query(`ALTER TABLE "rule_dao" DROP CONSTRAINT "PK_f63ea04682f2cdec3f1dc76ea08"`);
        // await queryRunner.query(`ALTER TABLE "rule_dao" DROP COLUMN "id"`);
        // await queryRunner.query(`ALTER TABLE "rule_dao" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rule_dao" ALTER COLUMN "id" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "rule_dao" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "rule_dao" ADD CONSTRAINT "PK_f63ea04682f2cdec3f1dc76ea08" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP CONSTRAINT "PK_c2d69ae87555fd4d1aa3e54afb6"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD CONSTRAINT "PK_0d597d53dd5c069cdc109e572f7" PRIMARY KEY ("constraintDaoId_2")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82fbec3376bb07d5cbb8662d78"`);
        // await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP COLUMN "constraintDaoId_1"`);
        // await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD "constraintDaoId_1" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ALTER COLUMN "constraintDaoId_1" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP CONSTRAINT "PK_0d597d53dd5c069cdc109e572f7"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD CONSTRAINT "PK_c2d69ae87555fd4d1aa3e54afb6" PRIMARY KEY ("constraintDaoId_2", "constraintDaoId_1")`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP CONSTRAINT "PK_c2d69ae87555fd4d1aa3e54afb6"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD CONSTRAINT "PK_82fbec3376bb07d5cbb8662d78b" PRIMARY KEY ("constraintDaoId_1")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d597d53dd5c069cdc109e572f"`);
        // await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP COLUMN "constraintDaoId_2"`);
        // await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD "constraintDaoId_2" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ALTER COLUMN "constraintDaoId_2" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP CONSTRAINT "PK_82fbec3376bb07d5cbb8662d78b"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD CONSTRAINT "PK_c2d69ae87555fd4d1aa3e54afb6" PRIMARY KEY ("constraintDaoId_1", "constraintDaoId_2")`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP CONSTRAINT "PK_5265f7f31a82b9f805e6ff06f64"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD CONSTRAINT "PK_b5aa628f646e589f9bd217572c3" PRIMARY KEY ("constraintDaoId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6a3aa44c390430df2c95aba98"`);
        // await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP COLUMN "ruleDaoId"`);
        // await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD "ruleDaoId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ALTER COLUMN "ruleDaoId" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP CONSTRAINT "PK_b5aa628f646e589f9bd217572c3"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD CONSTRAINT "PK_5265f7f31a82b9f805e6ff06f64" PRIMARY KEY ("constraintDaoId", "ruleDaoId")`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP CONSTRAINT "PK_5265f7f31a82b9f805e6ff06f64"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD CONSTRAINT "PK_e6a3aa44c390430df2c95aba980" PRIMARY KEY ("ruleDaoId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5aa628f646e589f9bd217572c"`);
        // await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP COLUMN "constraintDaoId"`);
        // await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD "constraintDaoId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ALTER COLUMN "constraintDaoId" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP CONSTRAINT "PK_e6a3aa44c390430df2c95aba980"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD CONSTRAINT "PK_5265f7f31a82b9f805e6ff06f64" PRIMARY KEY ("ruleDaoId", "constraintDaoId")`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "PK_a9674f67c4fe8bf283ad0bb319a"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "PK_26bd571fe9f49193e621fbb19e8" PRIMARY KEY ("ruleDaoId_2")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e4f03d5f894766ea199f8a881"`);
        // await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP COLUMN "ruleDaoId_1"`);
        // await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD "ruleDaoId_1" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ALTER COLUMN "ruleDaoId_1" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "PK_26bd571fe9f49193e621fbb19e8"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "PK_a9674f67c4fe8bf283ad0bb319a" PRIMARY KEY ("ruleDaoId_2", "ruleDaoId_1")`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "PK_a9674f67c4fe8bf283ad0bb319a"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "PK_4e4f03d5f894766ea199f8a8813" PRIMARY KEY ("ruleDaoId_1")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26bd571fe9f49193e621fbb19e"`);
        // await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP COLUMN "ruleDaoId_2"`);
        // await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD "ruleDaoId_2" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ALTER COLUMN "ruleDaoId_2" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "PK_4e4f03d5f894766ea199f8a8813"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "PK_a9674f67c4fe8bf283ad0bb319a" PRIMARY KEY ("ruleDaoId_1", "ruleDaoId_2")`);
        await queryRunner.query(`CREATE INDEX "IDX_82fbec3376bb07d5cbb8662d78" ON "constraint_dao_constraints_constraint_dao" ("constraintDaoId_1") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d597d53dd5c069cdc109e572f" ON "constraint_dao_constraints_constraint_dao" ("constraintDaoId_2") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6a3aa44c390430df2c95aba98" ON "rule_dao_constraints_constraint_dao" ("ruleDaoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b5aa628f646e589f9bd217572c" ON "rule_dao_constraints_constraint_dao" ("constraintDaoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e4f03d5f894766ea199f8a881" ON "rule_dao_duties_rule_dao" ("ruleDaoId_1") `);
        await queryRunner.query(`CREATE INDEX "IDX_26bd571fe9f49193e621fbb19e" ON "rule_dao_duties_rule_dao" ("ruleDaoId_2") `);
        await queryRunner.query(`ALTER TABLE "dataset" ADD CONSTRAINT "FK_761c5a05ade66b5e5d91b81271c" FOREIGN KEY ("DataPlaneId") REFERENCES "dataplanedetails"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" ADD CONSTRAINT "FK_4c9054a96e0428c673c7d0976fe" FOREIGN KEY ("StatusId") REFERENCES "transfer_detail_dao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" ADD CONSTRAINT "FK_90cfde7fcb7b8ac01d2206b4b1a" FOREIGN KEY ("DetailId") REFERENCES "negotiationDetail"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD CONSTRAINT "FK_82fbec3376bb07d5cbb8662d78b" FOREIGN KEY ("constraintDaoId_1") REFERENCES "constraint_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD CONSTRAINT "FK_0d597d53dd5c069cdc109e572f7" FOREIGN KEY ("constraintDaoId_2") REFERENCES "constraint_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD CONSTRAINT "FK_e6a3aa44c390430df2c95aba980" FOREIGN KEY ("ruleDaoId") REFERENCES "rule_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD CONSTRAINT "FK_b5aa628f646e589f9bd217572c3" FOREIGN KEY ("constraintDaoId") REFERENCES "constraint_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "FK_4e4f03d5f894766ea199f8a8813" FOREIGN KEY ("ruleDaoId_1") REFERENCES "rule_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "FK_26bd571fe9f49193e621fbb19e8" FOREIGN KEY ("ruleDaoId_2") REFERENCES "rule_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);

        await queryRunner.query(`DROP SEQUENCE "registry_id_seq"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP CONSTRAINT "FK_e6a3aa44c390430df2c95aba980"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "FK_4e4f03d5f894766ea199f8a8813"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "FK_26bd571fe9f49193e621fbb19e8"`);
        await queryRunner.query(`DROP SEQUENCE "rule_dao_id_seq"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD CONSTRAINT "FK_e6a3aa44c390430df2c95aba980" FOREIGN KEY ("ruleDaoId") REFERENCES "rule_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "FK_4e4f03d5f894766ea199f8a8813" FOREIGN KEY ("ruleDaoId_1") REFERENCES "rule_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "FK_26bd571fe9f49193e621fbb19e8" FOREIGN KEY ("ruleDaoId_2") REFERENCES "rule_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "FK_26bd571fe9f49193e621fbb19e8"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "FK_4e4f03d5f894766ea199f8a8813"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP CONSTRAINT "FK_b5aa628f646e589f9bd217572c3"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP CONSTRAINT "FK_e6a3aa44c390430df2c95aba980"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP CONSTRAINT "FK_0d597d53dd5c069cdc109e572f7"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP CONSTRAINT "FK_82fbec3376bb07d5cbb8662d78b"`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" DROP CONSTRAINT "FK_90cfde7fcb7b8ac01d2206b4b1a"`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" DROP CONSTRAINT "FK_4c9054a96e0428c673c7d0976fe"`);
        await queryRunner.query(`ALTER TABLE "dataset" DROP CONSTRAINT "FK_761c5a05ade66b5e5d91b81271c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26bd571fe9f49193e621fbb19e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e4f03d5f894766ea199f8a881"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5aa628f646e589f9bd217572c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6a3aa44c390430df2c95aba98"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d597d53dd5c069cdc109e572f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82fbec3376bb07d5cbb8662d78"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "PK_a9674f67c4fe8bf283ad0bb319a"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "PK_4e4f03d5f894766ea199f8a8813" PRIMARY KEY ("ruleDaoId_1")`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP COLUMN "ruleDaoId_2"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD "ruleDaoId_2" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_26bd571fe9f49193e621fbb19e" ON "rule_dao_duties_rule_dao" ("ruleDaoId_2") `);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "PK_4e4f03d5f894766ea199f8a8813"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "PK_a9674f67c4fe8bf283ad0bb319a" PRIMARY KEY ("ruleDaoId_2", "ruleDaoId_1")`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "PK_a9674f67c4fe8bf283ad0bb319a"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "PK_26bd571fe9f49193e621fbb19e8" PRIMARY KEY ("ruleDaoId_2")`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP COLUMN "ruleDaoId_1"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD "ruleDaoId_1" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_4e4f03d5f894766ea199f8a881" ON "rule_dao_duties_rule_dao" ("ruleDaoId_1") `);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "PK_26bd571fe9f49193e621fbb19e8"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "PK_a9674f67c4fe8bf283ad0bb319a" PRIMARY KEY ("ruleDaoId_1", "ruleDaoId_2")`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP CONSTRAINT "PK_5265f7f31a82b9f805e6ff06f64"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD CONSTRAINT "PK_e6a3aa44c390430df2c95aba980" PRIMARY KEY ("ruleDaoId")`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP COLUMN "constraintDaoId"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD "constraintDaoId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_b5aa628f646e589f9bd217572c" ON "rule_dao_constraints_constraint_dao" ("constraintDaoId") `);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP CONSTRAINT "PK_e6a3aa44c390430df2c95aba980"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD CONSTRAINT "PK_5265f7f31a82b9f805e6ff06f64" PRIMARY KEY ("constraintDaoId", "ruleDaoId")`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP CONSTRAINT "PK_5265f7f31a82b9f805e6ff06f64"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD CONSTRAINT "PK_b5aa628f646e589f9bd217572c3" PRIMARY KEY ("constraintDaoId")`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP COLUMN "ruleDaoId"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD "ruleDaoId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_e6a3aa44c390430df2c95aba98" ON "rule_dao_constraints_constraint_dao" ("ruleDaoId") `);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP CONSTRAINT "PK_b5aa628f646e589f9bd217572c3"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD CONSTRAINT "PK_5265f7f31a82b9f805e6ff06f64" PRIMARY KEY ("ruleDaoId", "constraintDaoId")`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP CONSTRAINT "PK_c2d69ae87555fd4d1aa3e54afb6"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD CONSTRAINT "PK_82fbec3376bb07d5cbb8662d78b" PRIMARY KEY ("constraintDaoId_1")`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP COLUMN "constraintDaoId_2"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD "constraintDaoId_2" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_0d597d53dd5c069cdc109e572f" ON "constraint_dao_constraints_constraint_dao" ("constraintDaoId_2") `);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP CONSTRAINT "PK_82fbec3376bb07d5cbb8662d78b"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD CONSTRAINT "PK_c2d69ae87555fd4d1aa3e54afb6" PRIMARY KEY ("constraintDaoId_2", "constraintDaoId_1")`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP CONSTRAINT "PK_c2d69ae87555fd4d1aa3e54afb6"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD CONSTRAINT "PK_0d597d53dd5c069cdc109e572f7" PRIMARY KEY ("constraintDaoId_2")`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP COLUMN "constraintDaoId_1"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD "constraintDaoId_1" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_82fbec3376bb07d5cbb8662d78" ON "constraint_dao_constraints_constraint_dao" ("constraintDaoId_1") `);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" DROP CONSTRAINT "PK_0d597d53dd5c069cdc109e572f7"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD CONSTRAINT "PK_c2d69ae87555fd4d1aa3e54afb6" PRIMARY KEY ("constraintDaoId_1", "constraintDaoId_2")`);
        await queryRunner.query(`ALTER TABLE "rule_dao" DROP CONSTRAINT "PK_f63ea04682f2cdec3f1dc76ea08"`);
        await queryRunner.query(`ALTER TABLE "rule_dao" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "rule_dao" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rule_dao" ADD CONSTRAINT "PK_f63ea04682f2cdec3f1dc76ea08" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "FK_26bd571fe9f49193e621fbb19e8" FOREIGN KEY ("ruleDaoId_2") REFERENCES "rule_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "FK_4e4f03d5f894766ea199f8a8813" FOREIGN KEY ("ruleDaoId_1") REFERENCES "rule_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD CONSTRAINT "FK_e6a3aa44c390430df2c95aba980" FOREIGN KEY ("ruleDaoId") REFERENCES "rule_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "constraint_dao" DROP CONSTRAINT "PK_90364c4023769e9a14b9a868640"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "constraint_dao" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "constraint_dao" ADD CONSTRAINT "PK_90364c4023769e9a14b9a868640" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD CONSTRAINT "FK_b5aa628f646e589f9bd217572c3" FOREIGN KEY ("constraintDaoId") REFERENCES "constraint_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD CONSTRAINT "FK_0d597d53dd5c069cdc109e572f7" FOREIGN KEY ("constraintDaoId_2") REFERENCES "constraint_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "constraint_dao_constraints_constraint_dao" ADD CONSTRAINT "FK_82fbec3376bb07d5cbb8662d78b" FOREIGN KEY ("constraintDaoId_1") REFERENCES "constraint_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "registry" DROP CONSTRAINT "PK_2eca29d55a9556d854416df8ce5"`);
        await queryRunner.query(`ALTER TABLE "registry" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "registry" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "registry" ADD CONSTRAINT "PK_2eca29d55a9556d854416df8ce5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" DROP COLUMN "ownerIdentifier"`);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" DROP CONSTRAINT "PK_58ba597dd26065f3e65c29520fd"`);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" DROP COLUMN "DetailId"`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" DROP CONSTRAINT "PK_89d401c15d5490a8e531198bdb5"`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "agreement_dao" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "agreement_dao" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "agreement_dao" DROP COLUMN "ownerIdentifier"`);
        await queryRunner.query(`ALTER TABLE "agreement_dao" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "agreement_dao" DROP COLUMN "deletedDate"`);
        await queryRunner.query(`ALTER TABLE "agreement_dao" DROP COLUMN "modifiedDate"`);
        await queryRunner.query(`ALTER TABLE "agreement_dao" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "transfer_detail_dao" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "transfer_detail_dao" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "transfer_detail_dao" DROP COLUMN "ownerIdentifier"`);
        await queryRunner.query(`ALTER TABLE "transfer_detail_dao" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "transfer_detail_dao" DROP CONSTRAINT "PK_857a6eeae43c58e72020f542232"`);
        await queryRunner.query(`ALTER TABLE "transfer_detail_dao" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" DROP COLUMN "StatusId"`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" DROP CONSTRAINT "PK_8a4e6a313a343a174a34db85cf2"`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "dataplanedetails" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "dataplanedetails" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "dataplanedetails" DROP COLUMN "ownerIdentifier"`);
        await queryRunner.query(`ALTER TABLE "dataplanedetails" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "dataplanedetails" DROP CONSTRAINT "PK_2a55a2a06ab936c80617690a239"`);
        await queryRunner.query(`ALTER TABLE "dataplanedetails" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" ADD "localId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "negotiationDetail" ADD CONSTRAINT "PK_027d8af43342f22e75cc3a9a379" PRIMARY KEY ("localId")`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" ADD "DetailLocalId" character varying`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" ADD CONSTRAINT "PK_ccf8fe5b23ac78ec5fd9a516702" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "transfer_detail_dao" ADD "localId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transfer_detail_dao" ADD CONSTRAINT "PK_cdd0938967466ddfea5dc2400df" PRIMARY KEY ("localId")`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" ADD "StatusLocalId" character varying`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" ADD "_id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" ADD CONSTRAINT "PK_312cf9b90f13412429277e788cc" PRIMARY KEY ("_id")`);
        await queryRunner.query(`ALTER TABLE "dataplanedetails" ADD "identifier" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dataplanedetails" ADD CONSTRAINT "PK_a47df13049c0a46016d2475cc58" PRIMARY KEY ("identifier")`);
        await queryRunner.query(`ALTER TABLE "dataset" RENAME COLUMN "DataPlaneId" TO "DataPlaneIdentifier"`);
        await queryRunner.query(`ALTER TABLE "negotationProcessEvent" ADD CONSTRAINT "FK_421acc1dc8622808e8c99c527f2" FOREIGN KEY ("DetailLocalId") REFERENCES "negotiationDetail"("localId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transfer_event_dao" ADD CONSTRAINT "FK_aa9f090675dd25f4eda56555e10" FOREIGN KEY ("StatusLocalId") REFERENCES "transfer_detail_dao"("localId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dataset" ADD CONSTRAINT "FK_5ffc12673c1b713c2f00e7ed722" FOREIGN KEY ("DataPlaneIdentifier") REFERENCES "dataplanedetails"("identifier") ON DELETE NO ACTION ON UPDATE NO ACTION`);

        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "FK_26bd571fe9f49193e621fbb19e8"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" DROP CONSTRAINT "FK_4e4f03d5f894766ea199f8a8813"`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" DROP CONSTRAINT "FK_e6a3aa44c390430df2c95aba980"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "rule_dao_id_seq" OWNED BY "rule_dao"."id"`);
        await queryRunner.query(`ALTER TABLE "rule_dao" ALTER COLUMN "id" SET DEFAULT nextval('"rule_dao_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "FK_26bd571fe9f49193e621fbb19e8" FOREIGN KEY ("ruleDaoId_2") REFERENCES "rule_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rule_dao_duties_rule_dao" ADD CONSTRAINT "FK_4e4f03d5f894766ea199f8a8813" FOREIGN KEY ("ruleDaoId_1") REFERENCES "rule_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "rule_dao_constraints_constraint_dao" ADD CONSTRAINT "FK_e6a3aa44c390430df2c95aba980" FOREIGN KEY ("ruleDaoId") REFERENCES "rule_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "registry_id_seq" OWNED BY "registry"."id"`);
        await queryRunner.query(`ALTER TABLE "registry" ALTER COLUMN "id" SET DEFAULT nextval('"registry_id_seq"')`);
    }

}
