apiVersion: v2
name: casdoor-init
description: Casdoor umbrella
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: casdoor-helm-charts
    alias: casdoor
    version: "v1.511.0"
    repository: "oci://registry-1.docker.io/casbin"