db:
  type: sqlite
  database: ":memory:"

server:
  port: "3000"
  listen: "0.0.0.0"
  publicDomain: localhost:3000
  publicAddress: http://localhost:3000

iam:
  type: tsg
  didId: did:web:localhost%3A3001
  tokenUrl: http://localhost:3001/api/auth/login
  presentationUrl: http://localhost:3001/api/presentations
  validationUrl: http://localhost:3001/api/presentations/validate
  clientId: client
  clientSecret: secret
  credentialId: did:web:localhost%3A3001#00000000-0000-0000-0000-000000000000
  validations:
    - valid

users:
  - username: admin
    password: $2a$12$/1aqZWSslSi8E556dpChNOxOyEv3hPA.k8asnRk9iIN2bxH6VGUE6

initCatalog:
  creator: did:web:localhost%3A3001
  publisher: did:web:localhost%3A3001
  title: TSG Test Connector
  description: TSG Test Connector testing Data Space Protocol support
  datasets:
    - '{"@context":"https://w3id.org/dspace/v0.8/context.json","@id":"urn:uuid:3afeadd8-ed2d-569e-d634-8394a8836d57","@type":"dcat:Dataset","dct:title":"Traffic Data","dct:description":[{"@value":"Traffic data sample extract","@language":"en"}],"dcat:keyword":[{"@value":"traffic","@language":"en"}],"odrl:hasPolicy":{"@type":"odrl:Offer","@id":"urn:uuid:2828282:3dd1add8-4d2d-569e-d634-8394a8836a88","odrl:permission":[{"odrl:action":"odrl:use","odrl:constraint":[{"odrl:leftOperand":"odrl:spatial","odrl:rightOperand":"_:EU","odrl:operator":"odrl:eq"}]}]},"dcat:distribution":[{"@type":"dcat:Distribution","dct:format":{"@id":"dspace:s3+push"},"dcat:accessService":[{"@id":"urn:uuid:4aa2dcc8-4d2d-569e-d634-8394a8834d77","@type":"dcat:DataService","dcat:endpointDescription":{"@id":"dspace:connector"},"dcat:endpointURL":"https://provder-a.com/connector"}]}]}'
    - '{"@context":"https://w3id.org/dspace/v0.8/context.json","@id":"urn:uuid:3afeadd8-ed2d-569e-d634-8394a8836d58","@type":"dcat:Dataset","dct:title":"Traffic Data","dct:description":[{"@value":"Traffic data sample extract","@language":"en"}],"dcat:keyword":[{"@value":"traffic","@language":"en"}],"odrl:hasPolicy":{"@type":"odrl:Offer","@id":"urn:uuid:2828282:3dd1add8-4d2d-569e-d634-8394a8836a89","odrl:permission":[{"odrl:action":"odrl:use","odrl:constraint":[{"odrl:leftOperand":"odrl:spatial","odrl:rightOperand":"_:EU","odrl:operator":"odrl:eq"}]}]},"dcat:distribution":[{"@type":"dcat:Distribution","dct:format":{"@id":"dspace:s3+push"},"dcat:accessService":[{"@id":"urn:uuid:4aa2dcc8-4d2d-569e-d634-8394a8834d55","@type":"dcat:DataService","dcat:endpointDescription":{"@id":"dspace:connector"},"dcat:endpointURL":"https://provder-a.com/connector"}]}]}'
    - '{"@context":"https://w3id.org/dspace/v0.8/context.json","@id":"urn:uuid:3afeadd8-ed2d-569e-d634-8394a8836d22","@type":"dcat:Dataset","dct:title":"Traffic Data","dct:description":[{"@value":"Traffic data sample extract","@language":"en"}],"dcat:keyword":[{"@value":"traffic","@language":"en"}],"odrl:hasPolicy":{"@type":"odrl:Offer","@id":"urn:uuid:2828282:3dd1add8-4d2d-569e-d634-8394a8836a12","odrl:permission":[{"odrl:action":"odrl:use","odrl:constraint":[{"odrl:leftOperand":"odrl:spatial","odrl:rightOperand":"_:EU","odrl:operator":"odrl:eq"}]}]},"dcat:distribution":[{"@type":"dcat:Distribution","dct:format":{"@id":"dspace:s3+push"},"dcat:accessService":[{"@id":"urn:uuid:4aa2dcc8-4d2d-569e-d634-8394a8834d23","@type":"dcat:DataService","dcat:endpointDescription":{"@id":"dspace:connector"},"dcat:endpointURL":"https://provder-a.com/connector"}]}]}'
    - '{"@context":"https://w3id.org/dspace/v0.8/context.json","@id":"urn:uuid:3afeadd8-ed2d-569e-d634-8394a8836d11","@type":"dcat:Dataset","dct:title":"Traffic Data","dct:description":[{"@value":"Traffic data sample extract","@language":"en"}],"dcat:keyword":[{"@value":"traffic","@language":"en"}],"odrl:hasPolicy":{"@type":"odrl:Offer","@id":"urn:uuid:2828282:3dd1add8-4d2d-569e-d634-8394a8836a11","odrl:permission":[{"odrl:action":"odrl:use","odrl:constraint":[{"odrl:leftOperand":"odrl:spatial","odrl:rightOperand":"_:EU","odrl:operator":"odrl:eq"}]}]},"dcat:distribution":[{"@type":"dcat:Distribution","dct:format":{"@id":"dspace:s3+push"},"dcat:accessService":[{"@id":"urn:uuid:4aa2dcc8-4d2d-569e-d634-8394a8834d99","@type":"dcat:DataService","dcat:endpointDescription":{"@id":"dspace:connector"},"dcat:endpointURL":"https://provder-a.com/connector"}]}]}'
