stages:
  - release

.helm_devel:
  stage: release
  image: dtzar/helm-kubectl:3.14
  tags:
    - saas-linux-small-amd64
  script:
    - cd helm-charts/$FOLDER
    - helm dep update
    - VERSION=$(grep -m 1 '^version:' Chart.yaml | awk '{ print $2}')
    # replace / with -
    - BRANCH_NAME=${CI_COMMIT_REF_NAME/\//-}
    - helm package --version "$VERSION-$BRANCH_NAME" .
    - curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@$( ls *.tgz | head -n1 )" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/devel/charts"
  rules:
    - if: $CI_COMMIT_BRANCH != "main"
      changes:
        - "helm-charts/$FOLDER/**/*"
        - helm-charts/.gitlab-ci.yml

.helm_stable:
  stage: release
  image: dtzar/helm-kubectl:3.14
  tags:
    - saas-linux-small-amd64
  script:
    - cd helm-charts/$FOLDER
    - helm dep update
    - helm package .
    - curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@$( ls *.tgz | head -n1 )" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - "helm-charts/$FOLDER/**/*"
        - helm-charts/.gitlab-ci.yml

helm-devel:control-plane:
  extends: .helm_devel
  variables:
    FOLDER: control-plane

helm-stable:control-plane:
  extends: .helm_stable
  variables:
    FOLDER: control-plane

helm-devel:wallet:
  extends: .helm_devel
  variables:
    FOLDER: wallet

helm-stable:wallet:
  extends: .helm_stable
  variables:
    FOLDER: wallet

helm-devel:http-data-plane:
  extends: .helm_devel
  variables:
    FOLDER: http-data-plane

helm-stable:http-data-plane:
  extends: .helm_stable
  variables:
    FOLDER: http-data-plane

helm-devel:casdoor:
  extends: .helm_devel
  variables:
    FOLDER: casdoor

helm-stable:casdoor:
  extends: .helm_stable
  variables:
    FOLDER: casdoor
