.helm-devel:
  stage: package
  image: dtzar/helm-kubectl:3.17
  tags:
    - saas-linux-small-amd64
  needs: []
  script:
    - cd helm-charts/$FOLDER
    - helm dep update
    - VERSION=$(grep -m 1 '^version:' Chart.yaml | awk '{ print $2}')
    - helm package --version "$VERSION-$CI_COMMIT_REF_SLUG" .
    - curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@$( ls *.tgz | head -n1 )" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/devel/charts"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: '$RELEASE_NOW == "true"'
      when: never
    - if: "$CI_COMMIT_TAG"
      when: never
    - if: $CI_COMMIT_BRANCH != "main"
      changes:
        - "helm-charts/$FOLDER/**/*"
        - helm-charts/helm.gitlab-ci.yml
    - if: $CI_COMMIT_BRANCH == "main"

.helm-stable:
  stage: release
  image: dtzar/helm-kubectl:3.17
  tags:
    - saas-linux-small-amd64
  needs: []
  script:
    - cd helm-charts/$FOLDER
    - helm dep update
    - helm package .
    - curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@$( ls *.tgz | head -n1 )" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"
  rules:
    - if: "$CI_COMMIT_TAG"

helm-devel:control-plane:
  extends: .helm-devel
  variables:
    FOLDER: control-plane

helm-stable:control-plane:
  extends: .helm-stable
  variables:
    FOLDER: control-plane

helm-devel:wallet:
  extends: .helm-devel
  variables:
    FOLDER: wallet

helm-stable:wallet:
  extends: .helm-stable
  variables:
    FOLDER: wallet

helm-devel:sso-bridge:
  extends: .helm-devel
  variables:
    FOLDER: sso-bridge

helm-stable:sso-bridge:
  extends: .helm-stable
  variables:
    FOLDER: sso-bridge

helm-devel:analytics-data-plane:
  extends: .helm-devel
  variables:
    FOLDER: analytics-data-plane

helm-stable:analytics-data-plane:
  extends: .helm-stable
  variables:
    FOLDER: analytics-data-plane

helm-devel:http-data-plane:
  extends: .helm-devel
  variables:
    FOLDER: http-data-plane

helm-stable:http-data-plane:
  extends: .helm-stable
  variables:
    FOLDER: http-data-plane
