import { MigrationInterface, QueryRunner } from "typeorm";

export class Postgres20250227130723 implements MigrationInterface {
    name = 'Postgres20250227130723'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" DROP COLUMN "modified"`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" DROP COLUMN "deleted"`);
        await queryRunner.query(`ALTER TABLE "credential_issuance" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "credential_issuance" DROP COLUMN "modified"`);
        await queryRunner.query(`ALTER TABLE "credential_issuance" DROP COLUMN "deleted"`);
        await queryRunner.query(`ALTER TABLE "ci_access_token" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "ci_access_token" DROP COLUMN "modified"`);
        await queryRunner.query(`ALTER TABLE "ci_access_token" DROP COLUMN "deleted"`);
        await queryRunner.query(`ALTER TABLE "did_documents" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "did_documents" DROP COLUMN "modified"`);
        await queryRunner.query(`ALTER TABLE "did_documents" DROP COLUMN "deleted"`);
        await queryRunner.query(`ALTER TABLE "did_service" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "did_service" DROP COLUMN "modified"`);
        await queryRunner.query(`ALTER TABLE "did_service" DROP COLUMN "deleted"`);
        await queryRunner.query(`ALTER TABLE "did_logs" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "did_logs" DROP COLUMN "modified"`);
        await queryRunner.query(`ALTER TABLE "did_logs" DROP COLUMN "deleted"`);
        await queryRunner.query(`ALTER TABLE "si_token" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "si_token" DROP COLUMN "modified"`);
        await queryRunner.query(`ALTER TABLE "si_token" DROP COLUMN "deleted"`);
        await queryRunner.query(`ALTER TABLE "key_materials" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "key_materials" DROP COLUMN "modified"`);
        await queryRunner.query(`ALTER TABLE "key_materials" DROP COLUMN "deleted"`);
        await queryRunner.query(`ALTER TABLE "credentials" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "credentials" DROP COLUMN "modified"`);
        await queryRunner.query(`ALTER TABLE "credentials" DROP COLUMN "deleted"`);
        await queryRunner.query(`ALTER TABLE "status_list_credential_dao" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "status_list_credential_dao" DROP COLUMN "modified"`);
        await queryRunner.query(`ALTER TABLE "status_list_credential_dao" DROP COLUMN "deleted"`);
        await queryRunner.query(`ALTER TABLE "jsonld_context" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "jsonld_context" DROP COLUMN "modified"`);
        await queryRunner.query(`ALTER TABLE "jsonld_context" DROP COLUMN "deleted"`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" ADD "modifiedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" ADD "deletedDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "credential_issuance" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "credential_issuance" ADD "modifiedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "credential_issuance" ADD "deletedDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ci_access_token" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ci_access_token" ADD "modifiedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ci_access_token" ADD "deletedDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "did_documents" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "did_documents" ADD "modifiedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "did_documents" ADD "deletedDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "did_service" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "did_service" ADD "modifiedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "did_service" ADD "deletedDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "did_logs" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "did_logs" ADD "modifiedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "did_logs" ADD "deletedDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "si_token" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "si_token" ADD "modifiedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "si_token" ADD "deletedDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "key_materials" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "key_materials" ADD "modifiedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "key_materials" ADD "deletedDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "credentials" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "credentials" ADD "modifiedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "credentials" ADD "deletedDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "status_list_credential_dao" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "status_list_credential_dao" ADD "modifiedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "status_list_credential_dao" ADD "deletedDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "jsonld_context" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "jsonld_context" ADD "modifiedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "jsonld_context" ADD "deletedDate" TIMESTAMP`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "jsonld_context" DROP COLUMN "deletedDate"`);
        await queryRunner.query(`ALTER TABLE "jsonld_context" DROP COLUMN "modifiedDate"`);
        await queryRunner.query(`ALTER TABLE "jsonld_context" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "status_list_credential_dao" DROP COLUMN "deletedDate"`);
        await queryRunner.query(`ALTER TABLE "status_list_credential_dao" DROP COLUMN "modifiedDate"`);
        await queryRunner.query(`ALTER TABLE "status_list_credential_dao" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "credentials" DROP COLUMN "deletedDate"`);
        await queryRunner.query(`ALTER TABLE "credentials" DROP COLUMN "modifiedDate"`);
        await queryRunner.query(`ALTER TABLE "credentials" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "key_materials" DROP COLUMN "deletedDate"`);
        await queryRunner.query(`ALTER TABLE "key_materials" DROP COLUMN "modifiedDate"`);
        await queryRunner.query(`ALTER TABLE "key_materials" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "si_token" DROP COLUMN "deletedDate"`);
        await queryRunner.query(`ALTER TABLE "si_token" DROP COLUMN "modifiedDate"`);
        await queryRunner.query(`ALTER TABLE "si_token" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "did_logs" DROP COLUMN "deletedDate"`);
        await queryRunner.query(`ALTER TABLE "did_logs" DROP COLUMN "modifiedDate"`);
        await queryRunner.query(`ALTER TABLE "did_logs" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "did_service" DROP COLUMN "deletedDate"`);
        await queryRunner.query(`ALTER TABLE "did_service" DROP COLUMN "modifiedDate"`);
        await queryRunner.query(`ALTER TABLE "did_service" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "did_documents" DROP COLUMN "deletedDate"`);
        await queryRunner.query(`ALTER TABLE "did_documents" DROP COLUMN "modifiedDate"`);
        await queryRunner.query(`ALTER TABLE "did_documents" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "ci_access_token" DROP COLUMN "deletedDate"`);
        await queryRunner.query(`ALTER TABLE "ci_access_token" DROP COLUMN "modifiedDate"`);
        await queryRunner.query(`ALTER TABLE "ci_access_token" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "credential_issuance" DROP COLUMN "deletedDate"`);
        await queryRunner.query(`ALTER TABLE "credential_issuance" DROP COLUMN "modifiedDate"`);
        await queryRunner.query(`ALTER TABLE "credential_issuance" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" DROP COLUMN "deletedDate"`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" DROP COLUMN "modifiedDate"`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "jsonld_context" ADD "deleted" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "jsonld_context" ADD "modified" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "jsonld_context" ADD "created" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "status_list_credential_dao" ADD "deleted" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "status_list_credential_dao" ADD "modified" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "status_list_credential_dao" ADD "created" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "credentials" ADD "deleted" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "credentials" ADD "modified" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "credentials" ADD "created" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "key_materials" ADD "deleted" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "key_materials" ADD "modified" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "key_materials" ADD "created" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "si_token" ADD "deleted" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "si_token" ADD "modified" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "si_token" ADD "created" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "did_logs" ADD "deleted" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "did_logs" ADD "modified" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "did_logs" ADD "created" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "did_service" ADD "deleted" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "did_service" ADD "modified" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "did_service" ADD "created" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "did_documents" ADD "deleted" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "did_documents" ADD "modified" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "did_documents" ADD "created" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ci_access_token" ADD "deleted" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ci_access_token" ADD "modified" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ci_access_token" ADD "created" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "credential_issuance" ADD "deleted" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "credential_issuance" ADD "modified" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "credential_issuance" ADD "created" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" ADD "deleted" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" ADD "modified" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" ADD "created" TIMESTAMP NOT NULL DEFAULT now()`);
    }

}
