import { MigrationInterface, QueryRunner } from "typeorm";

export class Sqlite20250605131310 implements MigrationInterface {
    name = 'Sqlite20250605131310'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_credential_issuance" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "preAuthorizedCode" varchar NOT NULL, "holderId" varchar, "credentialType" varchar NOT NULL, "credentialId" varchar, "revoked" boolean NOT NULL, "credentialSubject" text NOT NULL, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "remoteId" varchar, CONSTRAINT "UQ_bbf0dd236b76f0665f5352c6a29" UNIQUE ("preAuthorizedCode"))`);
        await queryRunner.query(`INSERT INTO "temporary_credential_issuance"("id", "preAuthorizedCode", "holderId", "credentialType", "credentialId", "revoked", "credentialSubject", "createdDate", "modifiedDate", "deletedDate", "remoteId") SELECT "id", "preAuthorizedCode", "holderId", "credentialType", "credentialId", "revoked", "credentialSubject", "createdDate", "modifiedDate", "deletedDate", "remoteId" FROM "credential_issuance"`);
        await queryRunner.query(`DROP TABLE "credential_issuance"`);
        await queryRunner.query(`ALTER TABLE "temporary_credential_issuance" RENAME TO "credential_issuance"`);
        await queryRunner.query(`CREATE TABLE "temporary_ci_access_token" ("access_token" varchar PRIMARY KEY NOT NULL, "expires_at" datetime NOT NULL, "refresh_token" varchar NOT NULL, "nonce" varchar NOT NULL, "issuanceId" integer, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, CONSTRAINT "FK_961e5cfd0bd678f6c91ce658848" FOREIGN KEY ("issuanceId") REFERENCES "credential_issuance" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ci_access_token"("access_token", "expires_at", "refresh_token", "nonce", "issuanceId", "createdDate", "modifiedDate", "deletedDate") SELECT "access_token", "expires_at", "refresh_token", "nonce", "issuanceId", "createdDate", "modifiedDate", "deletedDate" FROM "ci_access_token"`);
        await queryRunner.query(`DROP TABLE "ci_access_token"`);
        await queryRunner.query(`ALTER TABLE "temporary_ci_access_token" RENAME TO "ci_access_token"`);
        await queryRunner.query(`CREATE TABLE "temporary_ci_access_token" ("access_token" varchar PRIMARY KEY NOT NULL, "expires_at" datetime NOT NULL, "refresh_token" varchar NOT NULL, "nonce" varchar NOT NULL, "issuanceId" integer, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime)`);
        await queryRunner.query(`INSERT INTO "temporary_ci_access_token"("access_token", "expires_at", "refresh_token", "nonce", "issuanceId", "createdDate", "modifiedDate", "deletedDate") SELECT "access_token", "expires_at", "refresh_token", "nonce", "issuanceId", "createdDate", "modifiedDate", "deletedDate" FROM "ci_access_token"`);
        await queryRunner.query(`DROP TABLE "ci_access_token"`);
        await queryRunner.query(`ALTER TABLE "temporary_ci_access_token" RENAME TO "ci_access_token"`);
        await queryRunner.query(`CREATE TABLE "temporary_credential_issuance" ("id" varchar PRIMARY KEY NOT NULL, "preAuthorizedCode" varchar NOT NULL, "holderId" varchar, "credentialType" varchar NOT NULL, "credentialId" varchar, "revoked" boolean NOT NULL, "credentialSubject" text NOT NULL, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "remoteId" varchar, CONSTRAINT "UQ_bbf0dd236b76f0665f5352c6a29" UNIQUE ("preAuthorizedCode"))`);
        await queryRunner.query(`INSERT INTO "temporary_credential_issuance"("id", "preAuthorizedCode", "holderId", "credentialType", "credentialId", "revoked", "credentialSubject", "createdDate", "modifiedDate", "deletedDate", "remoteId") SELECT "id", "preAuthorizedCode", "holderId", "credentialType", "credentialId", "revoked", "credentialSubject", "createdDate", "modifiedDate", "deletedDate", "remoteId" FROM "credential_issuance"`);
        await queryRunner.query(`DROP TABLE "credential_issuance"`);
        await queryRunner.query(`ALTER TABLE "temporary_credential_issuance" RENAME TO "credential_issuance"`);
        await queryRunner.query(`CREATE TABLE "temporary_ci_access_token" ("access_token" varchar PRIMARY KEY NOT NULL, "expires_at" datetime NOT NULL, "refresh_token" varchar NOT NULL, "nonce" varchar NOT NULL, "issuanceId" varchar, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime)`);
        await queryRunner.query(`INSERT INTO "temporary_ci_access_token"("access_token", "expires_at", "refresh_token", "nonce", "issuanceId", "createdDate", "modifiedDate", "deletedDate") SELECT "access_token", "expires_at", "refresh_token", "nonce", "issuanceId", "createdDate", "modifiedDate", "deletedDate" FROM "ci_access_token"`);
        await queryRunner.query(`DROP TABLE "ci_access_token"`);
        await queryRunner.query(`ALTER TABLE "temporary_ci_access_token" RENAME TO "ci_access_token"`);
        await queryRunner.query(`CREATE TABLE "temporary_ci_access_token" ("access_token" varchar PRIMARY KEY NOT NULL, "expires_at" datetime NOT NULL, "refresh_token" varchar NOT NULL, "nonce" varchar NOT NULL, "issuanceId" varchar, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, CONSTRAINT "FK_961e5cfd0bd678f6c91ce658848" FOREIGN KEY ("issuanceId") REFERENCES "credential_issuance" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ci_access_token"("access_token", "expires_at", "refresh_token", "nonce", "issuanceId", "createdDate", "modifiedDate", "deletedDate") SELECT "access_token", "expires_at", "refresh_token", "nonce", "issuanceId", "createdDate", "modifiedDate", "deletedDate" FROM "ci_access_token"`);
        await queryRunner.query(`DROP TABLE "ci_access_token"`);
        await queryRunner.query(`ALTER TABLE "temporary_ci_access_token" RENAME TO "ci_access_token"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ci_access_token" RENAME TO "temporary_ci_access_token"`);
        await queryRunner.query(`CREATE TABLE "ci_access_token" ("access_token" varchar PRIMARY KEY NOT NULL, "expires_at" datetime NOT NULL, "refresh_token" varchar NOT NULL, "nonce" varchar NOT NULL, "issuanceId" varchar, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime)`);
        await queryRunner.query(`INSERT INTO "ci_access_token"("access_token", "expires_at", "refresh_token", "nonce", "issuanceId", "createdDate", "modifiedDate", "deletedDate") SELECT "access_token", "expires_at", "refresh_token", "nonce", "issuanceId", "createdDate", "modifiedDate", "deletedDate" FROM "temporary_ci_access_token"`);
        await queryRunner.query(`DROP TABLE "temporary_ci_access_token"`);
        await queryRunner.query(`ALTER TABLE "ci_access_token" RENAME TO "temporary_ci_access_token"`);
        await queryRunner.query(`CREATE TABLE "ci_access_token" ("access_token" varchar PRIMARY KEY NOT NULL, "expires_at" datetime NOT NULL, "refresh_token" varchar NOT NULL, "nonce" varchar NOT NULL, "issuanceId" integer, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime)`);
        await queryRunner.query(`INSERT INTO "ci_access_token"("access_token", "expires_at", "refresh_token", "nonce", "issuanceId", "createdDate", "modifiedDate", "deletedDate") SELECT "access_token", "expires_at", "refresh_token", "nonce", "issuanceId", "createdDate", "modifiedDate", "deletedDate" FROM "temporary_ci_access_token"`);
        await queryRunner.query(`DROP TABLE "temporary_ci_access_token"`);
        await queryRunner.query(`ALTER TABLE "credential_issuance" RENAME TO "temporary_credential_issuance"`);
        await queryRunner.query(`CREATE TABLE "credential_issuance" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "preAuthorizedCode" varchar NOT NULL, "holderId" varchar, "credentialType" varchar NOT NULL, "credentialId" varchar, "revoked" boolean NOT NULL, "credentialSubject" text NOT NULL, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "remoteId" varchar, CONSTRAINT "UQ_bbf0dd236b76f0665f5352c6a29" UNIQUE ("preAuthorizedCode"))`);
        await queryRunner.query(`INSERT INTO "credential_issuance"("id", "preAuthorizedCode", "holderId", "credentialType", "credentialId", "revoked", "credentialSubject", "createdDate", "modifiedDate", "deletedDate", "remoteId") SELECT "id", "preAuthorizedCode", "holderId", "credentialType", "credentialId", "revoked", "credentialSubject", "createdDate", "modifiedDate", "deletedDate", "remoteId" FROM "temporary_credential_issuance"`);
        await queryRunner.query(`DROP TABLE "temporary_credential_issuance"`);
        await queryRunner.query(`ALTER TABLE "ci_access_token" RENAME TO "temporary_ci_access_token"`);
        await queryRunner.query(`CREATE TABLE "ci_access_token" ("access_token" varchar PRIMARY KEY NOT NULL, "expires_at" datetime NOT NULL, "refresh_token" varchar NOT NULL, "nonce" varchar NOT NULL, "issuanceId" integer, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, CONSTRAINT "FK_961e5cfd0bd678f6c91ce658848" FOREIGN KEY ("issuanceId") REFERENCES "credential_issuance" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "ci_access_token"("access_token", "expires_at", "refresh_token", "nonce", "issuanceId", "createdDate", "modifiedDate", "deletedDate") SELECT "access_token", "expires_at", "refresh_token", "nonce", "issuanceId", "createdDate", "modifiedDate", "deletedDate" FROM "temporary_ci_access_token"`);
        await queryRunner.query(`DROP TABLE "temporary_ci_access_token"`);
        await queryRunner.query(`ALTER TABLE "ci_access_token" RENAME TO "temporary_ci_access_token"`);
        await queryRunner.query(`CREATE TABLE "ci_access_token" ("access_token" varchar PRIMARY KEY NOT NULL, "expires_at" datetime NOT NULL, "refresh_token" varchar NOT NULL, "nonce" varchar NOT NULL, "issuanceId" integer, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, CONSTRAINT "FK_961e5cfd0bd678f6c91ce658848" FOREIGN KEY ("issuanceId") REFERENCES "credential_issuance" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "ci_access_token"("access_token", "expires_at", "refresh_token", "nonce", "issuanceId", "createdDate", "modifiedDate", "deletedDate") SELECT "access_token", "expires_at", "refresh_token", "nonce", "issuanceId", "createdDate", "modifiedDate", "deletedDate" FROM "temporary_ci_access_token"`);
        await queryRunner.query(`DROP TABLE "temporary_ci_access_token"`);
        await queryRunner.query(`ALTER TABLE "credential_issuance" RENAME TO "temporary_credential_issuance"`);
        await queryRunner.query(`CREATE TABLE "credential_issuance" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "preAuthorizedCode" varchar NOT NULL, "holderId" varchar, "credentialType" varchar NOT NULL, "credentialId" varchar, "revoked" boolean NOT NULL, "credentialSubject" text NOT NULL, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "remoteId" varchar, CONSTRAINT "UQ_bbf0dd236b76f0665f5352c6a29" UNIQUE ("preAuthorizedCode"))`);
        await queryRunner.query(`INSERT INTO "credential_issuance"("id", "preAuthorizedCode", "holderId", "credentialType", "credentialId", "revoked", "credentialSubject", "createdDate", "modifiedDate", "deletedDate", "remoteId") SELECT "id", "preAuthorizedCode", "holderId", "credentialType", "credentialId", "revoked", "credentialSubject", "createdDate", "modifiedDate", "deletedDate", "remoteId" FROM "temporary_credential_issuance"`);
        await queryRunner.query(`DROP TABLE "temporary_credential_issuance"`);
    }

}
