import { MigrationInterface, QueryRunner } from "typeorm";

export class Sqlite20250227130723 implements MigrationInterface {
    name = 'Sqlite20250227130723'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_authorization_request_dao" ("identifier" varchar PRIMARY KEY NOT NULL, "presentationDefinition" text NOT NULL, "nonce" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "temporary_authorization_request_dao"("identifier", "presentationDefinition", "nonce") SELECT "identifier", "presentationDefinition", "nonce" FROM "authorization_request_dao"`);
        await queryRunner.query(`DROP TABLE "authorization_request_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_authorization_request_dao" RENAME TO "authorization_request_dao"`);
        await queryRunner.query(`CREATE TABLE "temporary_credential_issuance" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "preAuthorizedCode" varchar NOT NULL, "holderId" varchar, "credentialType" varchar NOT NULL, "credentialId" varchar, "revoked" boolean NOT NULL, "credentialSubject" text NOT NULL, CONSTRAINT "UQ_bbf0dd236b76f0665f5352c6a29" UNIQUE ("preAuthorizedCode"))`);
        await queryRunner.query(`INSERT INTO "temporary_credential_issuance"("id", "preAuthorizedCode", "holderId", "credentialType", "credentialId", "revoked", "credentialSubject") SELECT "id", "preAuthorizedCode", "holderId", "credentialType", "credentialId", "revoked", "credentialSubject" FROM "credential_issuance"`);
        await queryRunner.query(`DROP TABLE "credential_issuance"`);
        await queryRunner.query(`ALTER TABLE "temporary_credential_issuance" RENAME TO "credential_issuance"`);
        await queryRunner.query(`CREATE TABLE "temporary_ci_access_token" ("access_token" varchar PRIMARY KEY NOT NULL, "expires_at" datetime NOT NULL, "refresh_token" varchar NOT NULL, "nonce" varchar NOT NULL, "issuanceId" integer, CONSTRAINT "FK_961e5cfd0bd678f6c91ce658848" FOREIGN KEY ("issuanceId") REFERENCES "credential_issuance" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ci_access_token"("access_token", "expires_at", "refresh_token", "nonce", "issuanceId") SELECT "access_token", "expires_at", "refresh_token", "nonce", "issuanceId" FROM "ci_access_token"`);
        await queryRunner.query(`DROP TABLE "ci_access_token"`);
        await queryRunner.query(`ALTER TABLE "temporary_ci_access_token" RENAME TO "ci_access_token"`);
        await queryRunner.query(`CREATE TABLE "temporary_did_documents" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "document" text NOT NULL)`);
        await queryRunner.query(`INSERT INTO "temporary_did_documents"("id", "document") SELECT "id", "document" FROM "did_documents"`);
        await queryRunner.query(`DROP TABLE "did_documents"`);
        await queryRunner.query(`ALTER TABLE "temporary_did_documents" RENAME TO "did_documents"`);
        await queryRunner.query(`CREATE TABLE "temporary_did_service" ("id" varchar PRIMARY KEY NOT NULL, "type" varchar NOT NULL, "serviceEndpoint" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "temporary_did_service"("id", "type", "serviceEndpoint") SELECT "id", "type", "serviceEndpoint" FROM "did_service"`);
        await queryRunner.query(`DROP TABLE "did_service"`);
        await queryRunner.query(`ALTER TABLE "temporary_did_service" RENAME TO "did_service"`);
        await queryRunner.query(`CREATE TABLE "temporary_did_logs" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "scid" varchar NOT NULL, "logEntry" text NOT NULL)`);
        await queryRunner.query(`INSERT INTO "temporary_did_logs"("id", "scid", "logEntry") SELECT "id", "scid", "logEntry" FROM "did_logs"`);
        await queryRunner.query(`DROP TABLE "did_logs"`);
        await queryRunner.query(`ALTER TABLE "temporary_did_logs" RENAME TO "did_logs"`);
        await queryRunner.query(`CREATE TABLE "temporary_si_token" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "accessToken" varchar, "audience" varchar NOT NULL, "scope" varchar)`);
        await queryRunner.query(`INSERT INTO "temporary_si_token"("id", "accessToken", "audience", "scope") SELECT "id", "accessToken", "audience", "scope" FROM "si_token"`);
        await queryRunner.query(`DROP TABLE "si_token"`);
        await queryRunner.query(`ALTER TABLE "temporary_si_token" RENAME TO "si_token"`);
        await queryRunner.query(`CREATE TABLE "temporary_key_materials" ("id" varchar PRIMARY KEY NOT NULL, "type" varchar NOT NULL, "default" boolean NOT NULL, "privateKey" text NOT NULL, "publicKey" text NOT NULL, "caChain" varchar)`);
        await queryRunner.query(`INSERT INTO "temporary_key_materials"("id", "type", "default", "privateKey", "publicKey", "caChain") SELECT "id", "type", "default", "privateKey", "publicKey", "caChain" FROM "key_materials"`);
        await queryRunner.query(`DROP TABLE "key_materials"`);
        await queryRunner.query(`ALTER TABLE "temporary_key_materials" RENAME TO "key_materials"`);
        await queryRunner.query(`CREATE TABLE "temporary_credentials" ("id" varchar PRIMARY KEY NOT NULL, "targetDid" varchar NOT NULL, "credential" text NOT NULL, "selfIssued" boolean NOT NULL, "revoked" boolean NOT NULL DEFAULT (0), "statusListIndex" integer, "statusListCredentialId" varchar, CONSTRAINT "FK_9bf957e3dd684407894be5c912b" FOREIGN KEY ("statusListCredentialId") REFERENCES "status_list_credential_dao" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_credentials"("id", "targetDid", "credential", "selfIssued", "revoked", "statusListIndex", "statusListCredentialId") SELECT "id", "targetDid", "credential", "selfIssued", "revoked", "statusListIndex", "statusListCredentialId" FROM "credentials"`);
        await queryRunner.query(`DROP TABLE "credentials"`);
        await queryRunner.query(`ALTER TABLE "temporary_credentials" RENAME TO "credentials"`);
        await queryRunner.query(`CREATE TABLE "temporary_status_list_credential_dao" ("id" varchar PRIMARY KEY NOT NULL, "revoked" text NOT NULL, "full" boolean NOT NULL, "credentialId" varchar, CONSTRAINT "REL_20ce7613497c20b7cceabe6815" UNIQUE ("credentialId"), CONSTRAINT "FK_20ce7613497c20b7cceabe68154" FOREIGN KEY ("credentialId") REFERENCES "credentials" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_status_list_credential_dao"("id", "revoked", "full", "credentialId") SELECT "id", "revoked", "full", "credentialId" FROM "status_list_credential_dao"`);
        await queryRunner.query(`DROP TABLE "status_list_credential_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_status_list_credential_dao" RENAME TO "status_list_credential_dao"`);
        await queryRunner.query(`CREATE TABLE "temporary_jsonld_context" ("id" varchar PRIMARY KEY NOT NULL, "credentialType" varchar NOT NULL, "issuable" boolean NOT NULL, "documentUrl" varchar, "document" text, "schema" text)`);
        await queryRunner.query(`INSERT INTO "temporary_jsonld_context"("id", "credentialType", "issuable", "documentUrl", "document", "schema") SELECT "id", "credentialType", "issuable", "documentUrl", "document", "schema" FROM "jsonld_context"`);
        await queryRunner.query(`DROP TABLE "jsonld_context"`);
        await queryRunner.query(`ALTER TABLE "temporary_jsonld_context" RENAME TO "jsonld_context"`);
        await queryRunner.query(`CREATE TABLE "temporary_authorization_request_dao" ("identifier" varchar PRIMARY KEY NOT NULL, "presentationDefinition" text NOT NULL, "nonce" varchar NOT NULL, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime)`);
        await queryRunner.query(`INSERT INTO "temporary_authorization_request_dao"("identifier", "presentationDefinition", "nonce") SELECT "identifier", "presentationDefinition", "nonce" FROM "authorization_request_dao"`);
        await queryRunner.query(`DROP TABLE "authorization_request_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_authorization_request_dao" RENAME TO "authorization_request_dao"`);
        await queryRunner.query(`CREATE TABLE "temporary_credential_issuance" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "preAuthorizedCode" varchar NOT NULL, "holderId" varchar, "credentialType" varchar NOT NULL, "credentialId" varchar, "revoked" boolean NOT NULL, "credentialSubject" text NOT NULL, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, CONSTRAINT "UQ_bbf0dd236b76f0665f5352c6a29" UNIQUE ("preAuthorizedCode"))`);
        await queryRunner.query(`INSERT INTO "temporary_credential_issuance"("id", "preAuthorizedCode", "holderId", "credentialType", "credentialId", "revoked", "credentialSubject") SELECT "id", "preAuthorizedCode", "holderId", "credentialType", "credentialId", "revoked", "credentialSubject" FROM "credential_issuance"`);
        await queryRunner.query(`DROP TABLE "credential_issuance"`);
        await queryRunner.query(`ALTER TABLE "temporary_credential_issuance" RENAME TO "credential_issuance"`);
        await queryRunner.query(`CREATE TABLE "temporary_ci_access_token" ("access_token" varchar PRIMARY KEY NOT NULL, "expires_at" datetime NOT NULL, "refresh_token" varchar NOT NULL, "nonce" varchar NOT NULL, "issuanceId" integer, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, CONSTRAINT "FK_961e5cfd0bd678f6c91ce658848" FOREIGN KEY ("issuanceId") REFERENCES "credential_issuance" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ci_access_token"("access_token", "expires_at", "refresh_token", "nonce", "issuanceId") SELECT "access_token", "expires_at", "refresh_token", "nonce", "issuanceId" FROM "ci_access_token"`);
        await queryRunner.query(`DROP TABLE "ci_access_token"`);
        await queryRunner.query(`ALTER TABLE "temporary_ci_access_token" RENAME TO "ci_access_token"`);
        await queryRunner.query(`CREATE TABLE "temporary_did_documents" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "document" text NOT NULL, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime)`);
        await queryRunner.query(`INSERT INTO "temporary_did_documents"("id", "document") SELECT "id", "document" FROM "did_documents"`);
        await queryRunner.query(`DROP TABLE "did_documents"`);
        await queryRunner.query(`ALTER TABLE "temporary_did_documents" RENAME TO "did_documents"`);
        await queryRunner.query(`CREATE TABLE "temporary_did_service" ("id" varchar PRIMARY KEY NOT NULL, "type" varchar NOT NULL, "serviceEndpoint" varchar NOT NULL, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime)`);
        await queryRunner.query(`INSERT INTO "temporary_did_service"("id", "type", "serviceEndpoint") SELECT "id", "type", "serviceEndpoint" FROM "did_service"`);
        await queryRunner.query(`DROP TABLE "did_service"`);
        await queryRunner.query(`ALTER TABLE "temporary_did_service" RENAME TO "did_service"`);
        await queryRunner.query(`CREATE TABLE "temporary_did_logs" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "scid" varchar NOT NULL, "logEntry" text NOT NULL, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime)`);
        await queryRunner.query(`INSERT INTO "temporary_did_logs"("id", "scid", "logEntry") SELECT "id", "scid", "logEntry" FROM "did_logs"`);
        await queryRunner.query(`DROP TABLE "did_logs"`);
        await queryRunner.query(`ALTER TABLE "temporary_did_logs" RENAME TO "did_logs"`);
        await queryRunner.query(`CREATE TABLE "temporary_si_token" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "accessToken" varchar, "audience" varchar NOT NULL, "scope" varchar, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime)`);
        await queryRunner.query(`INSERT INTO "temporary_si_token"("id", "accessToken", "audience", "scope") SELECT "id", "accessToken", "audience", "scope" FROM "si_token"`);
        await queryRunner.query(`DROP TABLE "si_token"`);
        await queryRunner.query(`ALTER TABLE "temporary_si_token" RENAME TO "si_token"`);
        await queryRunner.query(`CREATE TABLE "temporary_key_materials" ("id" varchar PRIMARY KEY NOT NULL, "type" varchar NOT NULL, "default" boolean NOT NULL, "privateKey" text NOT NULL, "publicKey" text NOT NULL, "caChain" varchar, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime)`);
        await queryRunner.query(`INSERT INTO "temporary_key_materials"("id", "type", "default", "privateKey", "publicKey", "caChain") SELECT "id", "type", "default", "privateKey", "publicKey", "caChain" FROM "key_materials"`);
        await queryRunner.query(`DROP TABLE "key_materials"`);
        await queryRunner.query(`ALTER TABLE "temporary_key_materials" RENAME TO "key_materials"`);
        await queryRunner.query(`CREATE TABLE "temporary_credentials" ("id" varchar PRIMARY KEY NOT NULL, "targetDid" varchar NOT NULL, "credential" text NOT NULL, "selfIssued" boolean NOT NULL, "revoked" boolean NOT NULL DEFAULT (0), "statusListIndex" integer, "statusListCredentialId" varchar, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, CONSTRAINT "FK_9bf957e3dd684407894be5c912b" FOREIGN KEY ("statusListCredentialId") REFERENCES "status_list_credential_dao" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_credentials"("id", "targetDid", "credential", "selfIssued", "revoked", "statusListIndex", "statusListCredentialId") SELECT "id", "targetDid", "credential", "selfIssued", "revoked", "statusListIndex", "statusListCredentialId" FROM "credentials"`);
        await queryRunner.query(`DROP TABLE "credentials"`);
        await queryRunner.query(`ALTER TABLE "temporary_credentials" RENAME TO "credentials"`);
        await queryRunner.query(`CREATE TABLE "temporary_status_list_credential_dao" ("id" varchar PRIMARY KEY NOT NULL, "revoked" text NOT NULL, "full" boolean NOT NULL, "credentialId" varchar, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, CONSTRAINT "REL_20ce7613497c20b7cceabe6815" UNIQUE ("credentialId"), CONSTRAINT "FK_20ce7613497c20b7cceabe68154" FOREIGN KEY ("credentialId") REFERENCES "credentials" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_status_list_credential_dao"("id", "revoked", "full", "credentialId") SELECT "id", "revoked", "full", "credentialId" FROM "status_list_credential_dao"`);
        await queryRunner.query(`DROP TABLE "status_list_credential_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_status_list_credential_dao" RENAME TO "status_list_credential_dao"`);
        await queryRunner.query(`CREATE TABLE "temporary_jsonld_context" ("id" varchar PRIMARY KEY NOT NULL, "credentialType" varchar NOT NULL, "issuable" boolean NOT NULL, "documentUrl" varchar, "document" text, "schema" text, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime)`);
        await queryRunner.query(`INSERT INTO "temporary_jsonld_context"("id", "credentialType", "issuable", "documentUrl", "document", "schema") SELECT "id", "credentialType", "issuable", "documentUrl", "document", "schema" FROM "jsonld_context"`);
        await queryRunner.query(`DROP TABLE "jsonld_context"`);
        await queryRunner.query(`ALTER TABLE "temporary_jsonld_context" RENAME TO "jsonld_context"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "jsonld_context" RENAME TO "temporary_jsonld_context"`);
        await queryRunner.query(`CREATE TABLE "jsonld_context" ("id" varchar PRIMARY KEY NOT NULL, "credentialType" varchar NOT NULL, "issuable" boolean NOT NULL, "documentUrl" varchar, "document" text, "schema" text)`);
        await queryRunner.query(`INSERT INTO "jsonld_context"("id", "credentialType", "issuable", "documentUrl", "document", "schema") SELECT "id", "credentialType", "issuable", "documentUrl", "document", "schema" FROM "temporary_jsonld_context"`);
        await queryRunner.query(`DROP TABLE "temporary_jsonld_context"`);
        await queryRunner.query(`ALTER TABLE "status_list_credential_dao" RENAME TO "temporary_status_list_credential_dao"`);
        await queryRunner.query(`CREATE TABLE "status_list_credential_dao" ("id" varchar PRIMARY KEY NOT NULL, "revoked" text NOT NULL, "full" boolean NOT NULL, "credentialId" varchar, CONSTRAINT "REL_20ce7613497c20b7cceabe6815" UNIQUE ("credentialId"), CONSTRAINT "FK_20ce7613497c20b7cceabe68154" FOREIGN KEY ("credentialId") REFERENCES "credentials" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "status_list_credential_dao"("id", "revoked", "full", "credentialId") SELECT "id", "revoked", "full", "credentialId" FROM "temporary_status_list_credential_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_status_list_credential_dao"`);
        await queryRunner.query(`ALTER TABLE "credentials" RENAME TO "temporary_credentials"`);
        await queryRunner.query(`CREATE TABLE "credentials" ("id" varchar PRIMARY KEY NOT NULL, "targetDid" varchar NOT NULL, "credential" text NOT NULL, "selfIssued" boolean NOT NULL, "revoked" boolean NOT NULL DEFAULT (0), "statusListIndex" integer, "statusListCredentialId" varchar, CONSTRAINT "FK_9bf957e3dd684407894be5c912b" FOREIGN KEY ("statusListCredentialId") REFERENCES "status_list_credential_dao" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "credentials"("id", "targetDid", "credential", "selfIssued", "revoked", "statusListIndex", "statusListCredentialId") SELECT "id", "targetDid", "credential", "selfIssued", "revoked", "statusListIndex", "statusListCredentialId" FROM "temporary_credentials"`);
        await queryRunner.query(`DROP TABLE "temporary_credentials"`);
        await queryRunner.query(`ALTER TABLE "key_materials" RENAME TO "temporary_key_materials"`);
        await queryRunner.query(`CREATE TABLE "key_materials" ("id" varchar PRIMARY KEY NOT NULL, "type" varchar NOT NULL, "default" boolean NOT NULL, "privateKey" text NOT NULL, "publicKey" text NOT NULL, "caChain" varchar)`);
        await queryRunner.query(`INSERT INTO "key_materials"("id", "type", "default", "privateKey", "publicKey", "caChain") SELECT "id", "type", "default", "privateKey", "publicKey", "caChain" FROM "temporary_key_materials"`);
        await queryRunner.query(`DROP TABLE "temporary_key_materials"`);
        await queryRunner.query(`ALTER TABLE "si_token" RENAME TO "temporary_si_token"`);
        await queryRunner.query(`CREATE TABLE "si_token" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "accessToken" varchar, "audience" varchar NOT NULL, "scope" varchar)`);
        await queryRunner.query(`INSERT INTO "si_token"("id", "accessToken", "audience", "scope") SELECT "id", "accessToken", "audience", "scope" FROM "temporary_si_token"`);
        await queryRunner.query(`DROP TABLE "temporary_si_token"`);
        await queryRunner.query(`ALTER TABLE "did_logs" RENAME TO "temporary_did_logs"`);
        await queryRunner.query(`CREATE TABLE "did_logs" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "scid" varchar NOT NULL, "logEntry" text NOT NULL)`);
        await queryRunner.query(`INSERT INTO "did_logs"("id", "scid", "logEntry") SELECT "id", "scid", "logEntry" FROM "temporary_did_logs"`);
        await queryRunner.query(`DROP TABLE "temporary_did_logs"`);
        await queryRunner.query(`ALTER TABLE "did_service" RENAME TO "temporary_did_service"`);
        await queryRunner.query(`CREATE TABLE "did_service" ("id" varchar PRIMARY KEY NOT NULL, "type" varchar NOT NULL, "serviceEndpoint" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "did_service"("id", "type", "serviceEndpoint") SELECT "id", "type", "serviceEndpoint" FROM "temporary_did_service"`);
        await queryRunner.query(`DROP TABLE "temporary_did_service"`);
        await queryRunner.query(`ALTER TABLE "did_documents" RENAME TO "temporary_did_documents"`);
        await queryRunner.query(`CREATE TABLE "did_documents" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "document" text NOT NULL)`);
        await queryRunner.query(`INSERT INTO "did_documents"("id", "document") SELECT "id", "document" FROM "temporary_did_documents"`);
        await queryRunner.query(`DROP TABLE "temporary_did_documents"`);
        await queryRunner.query(`ALTER TABLE "ci_access_token" RENAME TO "temporary_ci_access_token"`);
        await queryRunner.query(`CREATE TABLE "ci_access_token" ("access_token" varchar PRIMARY KEY NOT NULL, "expires_at" datetime NOT NULL, "refresh_token" varchar NOT NULL, "nonce" varchar NOT NULL, "issuanceId" integer, CONSTRAINT "FK_961e5cfd0bd678f6c91ce658848" FOREIGN KEY ("issuanceId") REFERENCES "credential_issuance" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "ci_access_token"("access_token", "expires_at", "refresh_token", "nonce", "issuanceId") SELECT "access_token", "expires_at", "refresh_token", "nonce", "issuanceId" FROM "temporary_ci_access_token"`);
        await queryRunner.query(`DROP TABLE "temporary_ci_access_token"`);
        await queryRunner.query(`ALTER TABLE "credential_issuance" RENAME TO "temporary_credential_issuance"`);
        await queryRunner.query(`CREATE TABLE "credential_issuance" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "preAuthorizedCode" varchar NOT NULL, "holderId" varchar, "credentialType" varchar NOT NULL, "credentialId" varchar, "revoked" boolean NOT NULL, "credentialSubject" text NOT NULL, CONSTRAINT "UQ_bbf0dd236b76f0665f5352c6a29" UNIQUE ("preAuthorizedCode"))`);
        await queryRunner.query(`INSERT INTO "credential_issuance"("id", "preAuthorizedCode", "holderId", "credentialType", "credentialId", "revoked", "credentialSubject") SELECT "id", "preAuthorizedCode", "holderId", "credentialType", "credentialId", "revoked", "credentialSubject" FROM "temporary_credential_issuance"`);
        await queryRunner.query(`DROP TABLE "temporary_credential_issuance"`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" RENAME TO "temporary_authorization_request_dao"`);
        await queryRunner.query(`CREATE TABLE "authorization_request_dao" ("identifier" varchar PRIMARY KEY NOT NULL, "presentationDefinition" text NOT NULL, "nonce" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "authorization_request_dao"("identifier", "presentationDefinition", "nonce") SELECT "identifier", "presentationDefinition", "nonce" FROM "temporary_authorization_request_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_authorization_request_dao"`);
        await queryRunner.query(`ALTER TABLE "jsonld_context" RENAME TO "temporary_jsonld_context"`);
        await queryRunner.query(`CREATE TABLE "jsonld_context" ("created" datetime NOT NULL DEFAULT (datetime('now')), "modified" datetime NOT NULL DEFAULT (datetime('now')), "deleted" datetime, "id" varchar PRIMARY KEY NOT NULL, "credentialType" varchar NOT NULL, "issuable" boolean NOT NULL, "documentUrl" varchar, "document" text, "schema" text)`);
        await queryRunner.query(`INSERT INTO "jsonld_context"("id", "credentialType", "issuable", "documentUrl", "document", "schema") SELECT "id", "credentialType", "issuable", "documentUrl", "document", "schema" FROM "temporary_jsonld_context"`);
        await queryRunner.query(`DROP TABLE "temporary_jsonld_context"`);
        await queryRunner.query(`ALTER TABLE "status_list_credential_dao" RENAME TO "temporary_status_list_credential_dao"`);
        await queryRunner.query(`CREATE TABLE "status_list_credential_dao" ("created" datetime NOT NULL DEFAULT (datetime('now')), "modified" datetime NOT NULL DEFAULT (datetime('now')), "deleted" datetime, "id" varchar PRIMARY KEY NOT NULL, "revoked" text NOT NULL, "full" boolean NOT NULL, "credentialId" varchar, CONSTRAINT "REL_20ce7613497c20b7cceabe6815" UNIQUE ("credentialId"), CONSTRAINT "FK_20ce7613497c20b7cceabe68154" FOREIGN KEY ("credentialId") REFERENCES "credentials" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "status_list_credential_dao"("id", "revoked", "full", "credentialId") SELECT "id", "revoked", "full", "credentialId" FROM "temporary_status_list_credential_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_status_list_credential_dao"`);
        await queryRunner.query(`ALTER TABLE "credentials" RENAME TO "temporary_credentials"`);
        await queryRunner.query(`CREATE TABLE "credentials" ("created" datetime NOT NULL DEFAULT (datetime('now')), "modified" datetime NOT NULL DEFAULT (datetime('now')), "deleted" datetime, "id" varchar PRIMARY KEY NOT NULL, "targetDid" varchar NOT NULL, "credential" text NOT NULL, "selfIssued" boolean NOT NULL, "revoked" boolean NOT NULL DEFAULT (0), "statusListIndex" integer, "statusListCredentialId" varchar, CONSTRAINT "FK_9bf957e3dd684407894be5c912b" FOREIGN KEY ("statusListCredentialId") REFERENCES "status_list_credential_dao" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "credentials"("id", "targetDid", "credential", "selfIssued", "revoked", "statusListIndex", "statusListCredentialId") SELECT "id", "targetDid", "credential", "selfIssued", "revoked", "statusListIndex", "statusListCredentialId" FROM "temporary_credentials"`);
        await queryRunner.query(`DROP TABLE "temporary_credentials"`);
        await queryRunner.query(`ALTER TABLE "key_materials" RENAME TO "temporary_key_materials"`);
        await queryRunner.query(`CREATE TABLE "key_materials" ("created" datetime NOT NULL DEFAULT (datetime('now')), "modified" datetime NOT NULL DEFAULT (datetime('now')), "deleted" datetime, "id" varchar PRIMARY KEY NOT NULL, "type" varchar NOT NULL, "default" boolean NOT NULL, "privateKey" text NOT NULL, "publicKey" text NOT NULL, "caChain" varchar)`);
        await queryRunner.query(`INSERT INTO "key_materials"("id", "type", "default", "privateKey", "publicKey", "caChain") SELECT "id", "type", "default", "privateKey", "publicKey", "caChain" FROM "temporary_key_materials"`);
        await queryRunner.query(`DROP TABLE "temporary_key_materials"`);
        await queryRunner.query(`ALTER TABLE "si_token" RENAME TO "temporary_si_token"`);
        await queryRunner.query(`CREATE TABLE "si_token" ("created" datetime NOT NULL DEFAULT (datetime('now')), "modified" datetime NOT NULL DEFAULT (datetime('now')), "deleted" datetime, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "accessToken" varchar, "audience" varchar NOT NULL, "scope" varchar)`);
        await queryRunner.query(`INSERT INTO "si_token"("id", "accessToken", "audience", "scope") SELECT "id", "accessToken", "audience", "scope" FROM "temporary_si_token"`);
        await queryRunner.query(`DROP TABLE "temporary_si_token"`);
        await queryRunner.query(`ALTER TABLE "did_logs" RENAME TO "temporary_did_logs"`);
        await queryRunner.query(`CREATE TABLE "did_logs" ("created" datetime NOT NULL DEFAULT (datetime('now')), "modified" datetime NOT NULL DEFAULT (datetime('now')), "deleted" datetime, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "scid" varchar NOT NULL, "logEntry" text NOT NULL)`);
        await queryRunner.query(`INSERT INTO "did_logs"("id", "scid", "logEntry") SELECT "id", "scid", "logEntry" FROM "temporary_did_logs"`);
        await queryRunner.query(`DROP TABLE "temporary_did_logs"`);
        await queryRunner.query(`ALTER TABLE "did_service" RENAME TO "temporary_did_service"`);
        await queryRunner.query(`CREATE TABLE "did_service" ("created" datetime NOT NULL DEFAULT (datetime('now')), "modified" datetime NOT NULL DEFAULT (datetime('now')), "deleted" datetime, "id" varchar PRIMARY KEY NOT NULL, "type" varchar NOT NULL, "serviceEndpoint" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "did_service"("id", "type", "serviceEndpoint") SELECT "id", "type", "serviceEndpoint" FROM "temporary_did_service"`);
        await queryRunner.query(`DROP TABLE "temporary_did_service"`);
        await queryRunner.query(`ALTER TABLE "did_documents" RENAME TO "temporary_did_documents"`);
        await queryRunner.query(`CREATE TABLE "did_documents" ("created" datetime NOT NULL DEFAULT (datetime('now')), "modified" datetime NOT NULL DEFAULT (datetime('now')), "deleted" datetime, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "document" text NOT NULL)`);
        await queryRunner.query(`INSERT INTO "did_documents"("id", "document") SELECT "id", "document" FROM "temporary_did_documents"`);
        await queryRunner.query(`DROP TABLE "temporary_did_documents"`);
        await queryRunner.query(`ALTER TABLE "ci_access_token" RENAME TO "temporary_ci_access_token"`);
        await queryRunner.query(`CREATE TABLE "ci_access_token" ("created" datetime NOT NULL DEFAULT (datetime('now')), "modified" datetime NOT NULL DEFAULT (datetime('now')), "deleted" datetime, "access_token" varchar PRIMARY KEY NOT NULL, "expires_at" datetime NOT NULL, "refresh_token" varchar NOT NULL, "nonce" varchar NOT NULL, "issuanceId" integer, CONSTRAINT "FK_961e5cfd0bd678f6c91ce658848" FOREIGN KEY ("issuanceId") REFERENCES "credential_issuance" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "ci_access_token"("access_token", "expires_at", "refresh_token", "nonce", "issuanceId") SELECT "access_token", "expires_at", "refresh_token", "nonce", "issuanceId" FROM "temporary_ci_access_token"`);
        await queryRunner.query(`DROP TABLE "temporary_ci_access_token"`);
        await queryRunner.query(`ALTER TABLE "credential_issuance" RENAME TO "temporary_credential_issuance"`);
        await queryRunner.query(`CREATE TABLE "credential_issuance" ("created" datetime NOT NULL DEFAULT (datetime('now')), "modified" datetime NOT NULL DEFAULT (datetime('now')), "deleted" datetime, "id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "preAuthorizedCode" varchar NOT NULL, "holderId" varchar, "credentialType" varchar NOT NULL, "credentialId" varchar, "revoked" boolean NOT NULL, "credentialSubject" text NOT NULL, CONSTRAINT "UQ_bbf0dd236b76f0665f5352c6a29" UNIQUE ("preAuthorizedCode"))`);
        await queryRunner.query(`INSERT INTO "credential_issuance"("id", "preAuthorizedCode", "holderId", "credentialType", "credentialId", "revoked", "credentialSubject") SELECT "id", "preAuthorizedCode", "holderId", "credentialType", "credentialId", "revoked", "credentialSubject" FROM "temporary_credential_issuance"`);
        await queryRunner.query(`DROP TABLE "temporary_credential_issuance"`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" RENAME TO "temporary_authorization_request_dao"`);
        await queryRunner.query(`CREATE TABLE "authorization_request_dao" ("created" datetime NOT NULL DEFAULT (datetime('now')), "modified" datetime NOT NULL DEFAULT (datetime('now')), "deleted" datetime, "identifier" varchar PRIMARY KEY NOT NULL, "presentationDefinition" text NOT NULL, "nonce" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "authorization_request_dao"("identifier", "presentationDefinition", "nonce") SELECT "identifier", "presentationDefinition", "nonce" FROM "temporary_authorization_request_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_authorization_request_dao"`);
    }

}
