db:
  type: sqlite
  database: ":memory:"
  # database: control-plane-b.sqlite

server:
  port: "3002"
  listen: "0.0.0.0"
  publicDomain: localhost:3002
  publicAddress: http://localhost:3002/api

runtime:
  controlPlaneInteractions: automatic
  color: "#3B8BF6"

iam:
  type: dev
  didId: did:web:localhost%3A3001
  tokenUrl: http://localhost:3001/api/auth/login
  walletUrl: http://localhost:3001/api
  clientId: client
  clientSecret: secret

registry:
  useRegistry: true
  registryIntervalInMilliseconds: 3000

auth:
  enabled: false

initCatalog:
  creator: did:web:localhost%3A3002
  publisher: did:web:localhost%3A3002
  title: Party 2
  description: TSG Test Connector testing Data Space Protocol support
  datasets: []
