db:
  type: sqlite
  database: ":memory:"

server:
  port: "3000"
  listen: "0.0.0.0"
  publicDomain: localhost:3000
  publicAddress: http://localhost:3000

auth:
  enabled: false

runtime:
  controlPlaneInteractions: automatic
  color: "#3B8BF6"

registry:
  useRegistry: true
  registryIntervalInMilliseconds: 30000

iam:
  type: dev
  didId: did:web:localhost%3A3001

initCatalog:
  participantId: did:web:localhost%3A3001
  creator: did:web:localhost%3A3001
  publisher: did:web:localhost%3A3001
  title: Party 1
  description: TSG Test Connector testing Data Space Protocol support
  datasets: []
