openapi: 3.1.0
info:
  title: TSG - Dataspace Protocol - Transfer Callback API
  description: API definition for communication for consumers in transfer sequences between Control Planes
  version: 0.0.1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost
security:
  - BearerAuth: []
paths:
  /transfers/callbacks/{id}/start:
    post:
      operationId: startCallback
      summary: Start the transfer process by the provider
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../schemas/dsp.schema.json#/definitions/TransferStartMessageDto
      responses:
        200:
          description: Transfer start processed
        404:
          description: Transfer process not found
        4XX:
          description: Request error
  /transfers/callbacks/{id}/complete:
    post:
      operationId: completeCallback
      summary: Complete the transfer process by the provider
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../schemas/dsp.schema.json#/definitions/TransferCompletionMessageDto
      responses:
        200:
          description: Transfer complete processed
        404:
          description: Transfer process not found
        4XX:
          description: Request error
  /transfers/callbacks/{id}/terminate:
    post:
      operationId: terminateCallback
      summary: Terminate the transfer process by the provider
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../schemas/dsp.schema.json#/definitions/TransferTerminationMessageDto
      responses:
        200:
          description: Transfer terminate processed
        404:
          description: Transfer process not found
        4XX:
          description: Request error
  /transfers/callbacks/{id}/suspend:
    post:
      operationId: suspendCallback
      summary: Suspend the transfer process by the provider
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../schemas/dsp.schema.json#/definitions/TransferSuspensionMessageDto
      responses:
        200:
          description: Transfer suspend processed
        404:
          description: Transfer process not found
        4XX:
          description: Request error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT-based Verifiable Presentation
