server:
  port: 3000
  listen: "0.0.0.0"
  publicDomain: localhost:3000
  publicAddress: "http://localhost:3000"

auth:
  enabled: false
  # authorizationURL: https://localhost/login/oauth/authorize
  # tokenURL: https://localhost/api/login/oauth/access_token
  # introspectionURL: https://localhost/api/login/oauth/introspect
  # callbackURL: http://localhost:5173/api/auth/callback
  # clientId:
  # clientSecret:
  # clientUsername:
  # clientPassword:
  # redirectURL: http://localhost:5173/

initKeys:
  - id: key-0
    type: EdDSA
    default: true

initCredentials: []

db:
  type: sqlite
  database: wallet.sqlite

runtime:
  color: "#3B8BF6"
  acceptUnauthenticatedCredentialRequests: true
  issueMobileCredentials: true
  issueDebugCredentials: true

trustAnchors:
  - id: did:web:localhost%3A3000
    credentialTypes:
      - SCSNCredential
      - scsn:SCSNCredential
      - http://localhost:3000/issue-configuration/SCSNCredential#SCSNCredential

issueConfigurations:
  - id: SCSN
    credentialType: SCSNCredential
    proofType: jwt
    document:
      "@context":
        "@protected": true
        "@version": 1.1
        xsd: "http://www.w3.org/2001/XMLSchema#"
        scsn: http://localhost:3000/issue-configuration/SCSNCredential#
        id: "@id"
        type: "@type"
        SCSNCredential:
          "@context":
            - https://www.w3.org/ns/credentials/v2
          "@id": scsn:SCSNCredential
        scsnIdentifier:
          "@id": scsn:scsnIdentifier
          "@type": xsd:string
        scsnRole:
          "@id": scsn:scsnRole
          "@type": "@vocab"
        ServiceProvider:
          "@id": scsn:ServiceProvider
        Manufacturer:
          "@id": scsn:Manufacturer
        Administrator:
          "@id": scsn:Administrator
    backgroundImage: https://smart-connected.nl/_theme/scsn/images/frontend/scsn-logo-white.svg
    backgroundColor: "#6bb542"
    textColor: "#ffffff"
    name: Membership Credential
    description: Service Provider
    schema:
      type: object
      additionalProperties: true
      properties:
        scsnIdentifier:
          type: string
          title: "SCSN Identifier"
          example: "urn:scsn:1234567890"
          pattern: "^urn:scsn:.*"
        id:
          type: string
          title: "Participant Identifier"
          example: "did:web:example.com"
          pattern: "^did:.*"
        scsnRole:
          type: string
          title: "SCSN Role"
          example: "ServiceProvider"
          enum:
            - ServiceProvider
            - Manufacturer
            - Administrator
      required:
        - scsnIdentifier
        - scsnRole
  - id: SCSNLdp
    credentialType: SCSNCredentialLdp
    proofType: ldp
    document:
      "@context":
        "@protected": true
        "@version": 1.1
        xsd: "http://www.w3.org/2001/XMLSchema#"
        scsn: http://localhost:3000/issue-configuration/SCSNCredentialLdp#
        id: "@id"
        type: "@type"
        SCSNCredentialLdp:
          "@context":
            - https://www.w3.org/ns/credentials/v2
          "@id": scsn:SCSNCredentialLdp
        scsnIdentifier:
          "@id": scsn:scsnIdentifier
          "@type": xsd:string
        scsnRole:
          "@id": scsn:scsnRole
          "@type": "@vocab"
        ServiceProvider:
          "@id": scsn:ServiceProvider
        Manufacturer:
          "@id": scsn:Manufacturer
        Administrator:
          "@id": scsn:Administrator
    backgroundImage: https://smart-connected.nl/_theme/scsn/images/frontend/scsn-logo-white.svg
    backgroundColor: "#6bb542"
    textColor: "#ffffff"
    name: Membership Credential
    description: Service Provider
    schema:
      type: object
      additionalProperties: true
      properties:
        scsnIdentifier:
          type: string
          title: "SCSN Identifier"
          example: "urn:scsn:1234567890"
          pattern: "^urn:scsn:.*"
        id:
          type: string
          title: "Participant Identifier"
          example: "did:web:example.com"
          pattern: "^did:.*"
        scsnRole:
          type: string
          title: "SCSN Role"
          example: "ServiceProvider"
          enum:
            - ServiceProvider
            - Manufacturer
            - Administrator
      required:
        - scsnIdentifier
        - scsnRole
did:
  method: "did:web:"
