{{- if .Values.ingress.enabled }}
{{ required "A hostname under the key 'host' is required to enable ingresses" .Values.host }}
{{- with .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "control-plane.fullname" $ }}-ingress
  labels: {{ include "control-plane.labels" $ | nindent 4 }}
  annotations:
    {{- if .clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .clusterIssuer }}
    {{- end }}
    {{- with .annotations }}
    {{- tpl (toYaml . ) $ | nindent 4 }}
    {{- end }}
    kubernetes.io/ingress.class: {{ .class | default "nginx" }} 
    {{- if .rewriteTarget}}    
    nginx.ingress.kubernetes.io/rewrite-target: {{ .rewriteTarget }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ $.Values.host }}
    secretName: {{ $.Values.host }}-tls-secret
  rules:
  - host: {{ $.Values.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ template "control-plane.fullname" $ }}
            port: 
              number: {{ $.Values.config.server.port | default 3000 }}
        path: {{ .path | default "/" }} 
        pathType: Prefix
{{- end }}
{{- end }}