openapi: 3.1.0
info:
  title: TSG - Dataspace Protocol - Negotiation API
  description: API definition for communication for providers in negotiation sequences between Control Planes
  version: 0.0.1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost
security:
  - BearerAuth: []
paths:
  /negotiations/request:
    post:
      operationId: contractRequest
      summary: Request a contract negotiation
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../schemas/dsp.schema.json#/definitions/ContractRequestMessageDto
      responses:
        200:
          description: Contract negotiation response
          content:
            application/json:
              schema:
                $ref: ../schemas/dsp.schema.json#/definitions/ContractNegotiationDto
        4XX:
          description: Request error
  /negotiations/{processId}:
    get:
      operationId: requestContractNegotiation
      summary: Request contract negotiation status
      parameters:
        - name: processId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Contract negotiation response
          content:
            application/json:
              schema:
                $ref: ../schemas/dsp.schema.json#/definitions/ContractNegotiationDto
        404:
          description: Contract negotiation not found
  /negotiations/{processId}/request:
    post:
      operationId: contractOffer
      summary: Make an offer initiated from a consumer
      parameters:
        - name: processId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../schemas/dsp.schema.json#/definitions/ContractRequestMessageDto
      responses:
        200:
          description: Offer processed
        404:
          description: Contract negotiation not found
  /negotiations/{processId}/events:
    post:
      operationId: offerAcceptance
      summary: Contract negotiation event indicating acceptance of the offer provided by the provider
      parameters:
        - name: processId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../schemas/dsp.schema.json#/definitions/ContractNegotiationEventMessageDto
      responses:
        200:
          description: Acceptance processed
        404:
          description: Contract negotiation not found
  /negotiations/{processId}/agreement/verification:
    post:
      operationId: agreementVerification
      summary: Contract agreement verification to cryptographically verify the acceptance of an agreement
      parameters:
        - name: processId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../schemas/dsp.schema.json#/definitions/ContractAgreementVerificationMessageDto
      responses:
        200:
          description: Verification processed
        404:
          description: Contract negotiation not found
  /negotiations/{processId}/termination:
    post:
      operationId: negotiationTermination
      summary: Negotiation termination
      parameters:
        - name: processId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../schemas/dsp.schema.json#/definitions/ContractNegotiationTerminationMessageDto
      responses:
        200:
          description: Termination processed
        404:
          description: Contract negotiation not found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT-based Verifiable Presentation
