import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "apis/wallet/tsg-wallet",
    },
    {
      type: "category",
      label: "Health",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/health-controller-get-health",
          label: "Health check",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Settings",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/config-controller-get-settings",
          label: "Retrieve settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/config-controller-update-settings",
          label: "Update settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/config-controller-upload-file",
          label: "Upload logo",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Authentication",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/auth-controller-get-user",
          label: "Retrieve current user status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/auth-controller-login",
          label: "Login redirect",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/auth-controller-logout",
          label: "Logout redirect",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/auth-controller-callback",
          label: "Login callback",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Keys",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/keys-controller-get-ca-chain",
          label: "Retrieve Key CA chain",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Credentials",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/credentials-controller-get-credentials",
          label: "List dataspace credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/credentials-controller-get-credential",
          label: "Retrieve credential",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Management DID",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/did-management-controller-get-did-document",
          label: "Retrieve DID document",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/did-management-controller-get-services",
          label: "Retrieve DID services",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/did-management-controller-add-service",
          label: "Add DID service",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/did-management-controller-update-service",
          label: "Update DID service",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/wallet/did-management-controller-delete-service",
          label: "Delete DID service",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Management Keys",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/keys-management-controller-get-keys",
          label: "Retrieve keys",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/keys-management-controller-add-key",
          label: "Add key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/keys-management-controller-get-key",
          label: "Retrieve key",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/keys-management-controller-delete-key",
          label: "Delete key",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/wallet/keys-management-controller-set-default-key",
          label: "Set default key",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Management Credentials",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/credentials-management-controller-get-credentials",
          label: "List credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/credentials-management-controller-add-credential",
          label: "Add credential",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/credentials-management-controller-get-dataspace-credentials",
          label: "List dataspace credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/credentials-management-controller-get-config",
          label: "Retrieve credential configuration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/credentials-management-controller-import-credential",
          label: "Import credential",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/credentials-management-controller-get-credential",
          label: "Retrieve credential",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/credentials-management-controller-update-credential",
          label: "Update credential",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/wallet/credentials-management-controller-delete-credential",
          label: "Delete credential",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/wallet/credentials-management-controller-revoke-credential",
          label: "Revoke credential",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Management Gaia-X Credentials",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/gaia-x-management-controller-request-legal-registration-number-credential",
          label: "Issue legal registration number credential",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/gaia-x-management-controller-request-compliance-credential",
          label: "Request compliance credential",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Management Presentation",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/presentation-management-controller-status",
          label: "Get the status of a credential",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/presentation-management-controller-get-scopes",
          label: "Get all defined scopes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/presentation-management-controller-add-scope",
          label: "Add new scope",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/presentation-management-controller-update-scope",
          label: "Update scope",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/wallet/presentation-management-controller-delete-scope",
          label: "Delete scope",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "OpenID 4 Verifiable Credential Issuance",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/oid-4-vci-holder-controller-request-credential",
          label: "Request credential via OID4VCI",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/oid-4-vci-issuer-controller-issuer-metadata",
          label: "OID4VCIIssuerController_issuerMetadata",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/oid-4-vci-issuer-controller-token-endpoint",
          label: "Request OID4VCI access token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/oid-4-vci-issuer-controller-nonce-endpoint",
          label: "Request OID4VCI nonce",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/oid-4-vci-issuer-controller-credential-endpoint",
          label: "Request OID4VCI credential",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Presentation DCP",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/dcp-holder-controller-presentation-query",
          label: "Retrieve presentation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/dcp-holder-management-controller-create-si-token",
          label: "Request a SIOP token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/dcp-verifier-management-controller-verify",
          label: "Start verification flow",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Status",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/status-controller-get-status",
          label: "Application status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "OID4VP",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/oid-4-vp-verifier-controller-get-authorization-request",
          label: "Get the Authorization Request",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/oid-4-vp-verifier-controller-status",
          label: "Submit Authorization Response",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/oid-4-vp-verifier-management-controller-create",
          label: "Add an Authorization Request",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/oid-4-vp-verifier-management-controller-create-public",
          label: "Add a public Authorization Request",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "DID Web",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/did-web-controller-get-did",
          label: "Retrieve DID document",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Management Signatures",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/signature-management-controller-sign",
          label: "Sign document",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/signature-management-controller-sign-jwt",
          label: "Sign document as JWT",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/signature-management-controller-validate",
          label: "Validate signed document",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/signature-management-controller-validate-jwt",
          label: "Validate signed JWT",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Issue Configurations",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/issue-configuration-controller-get-context",
          label: "Retrieve issue configuration document",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/issue-configuration-controller-get-background-image",
          label: "Retrieve issue configuration background image",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Management Issue Configurations",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/issue-configuration-management-controller-get-issue-configurations",
          label: "Retrieve issue configurations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/issue-configuration-management-controller-add-issue-configuration",
          label: "Add issue configuration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/issue-configuration-management-controller-update-issue-configuration",
          label: "Update issue configuration",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/wallet/issue-configuration-management-controller-delete-issue-configuration",
          label: "Delete issue configuration",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Issuance Management",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/issuance-management-controller-request-dcp-credential",
          label: "Request credential via DCP",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/issuance-management-controller-request-oid-4-vci-credential",
          label: "Request credential via OID4VCI",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/issuance-management-controller-list-offers",
          label: "Retrieve offered credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/issuance-management-controller-offer-endpoint",
          label: "Add offer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/issuance-management-controller-list-general-offers",
          label: "Retrieve offered credential",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/issuance-management-controller-public-offer-endpoint",
          label: "Add public offer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/issuance-management-controller-revoke-offer",
          label: "Revoke offer",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "DCP Credential Issuance",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/dcp-holder-controller-store-credential",
          label: "Store credential",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/dcp-holder-controller-credential-offer",
          label: "Offer credential",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/dcp-issuer-controller-metadata",
          label: "Issuer Metadata",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/wallet/dcp-issuer-controller-credential-request",
          label: "Request credential",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/wallet/dcp-issuer-controller-credential-status",
          label: "Credential status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/wallet/schemas/runtimeconfigdto",
          label: "RuntimeConfigDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/errordto",
          label: "ErrorDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/databasestatusdto",
          label: "DatabaseStatusDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/memoryusagedto",
          label: "MemoryUsageDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/statusissuancedto",
          label: "StatusIssuanceDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/statuscredentialdto",
          label: "StatusCredentialDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/statusdto",
          label: "StatusDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialstatusrequest",
          label: "CredentialStatusRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/verifiedcredentialstatus",
          label: "VerifiedCredentialStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/jwtvpclaimformat",
          label: "JwtVpClaimFormat",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/format",
          label: "Format",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/filteritems",
          label: "FilterItems",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/filter",
          label: "Filter",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/field",
          label: "Field",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/constraint",
          label: "Constraint",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/inputdescriptor",
          label: "InputDescriptor",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/presentationdefinition",
          label: "PresentationDefinition",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/scopedto",
          label: "ScopeDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/addscope",
          label: "AddScope",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/presentationquerymessage",
          label: "PresentationQueryMessage",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/statusmessage",
          label: "StatusMessage",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialstatus",
          label: "CredentialStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialsubject",
          label: "CredentialSubject",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/dataintegrityproof",
          label: "DataIntegrityProof",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/verifiablecredential",
          label: "VerifiableCredential",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/verifiablepresentation",
          label: "VerifiablePresentation",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/descriptormap",
          label: "DescriptorMap",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/presentationsubmission",
          label: "PresentationSubmission",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/presentationresponsemessage",
          label: "PresentationResponseMessage",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/verificationrequest",
          label: "VerificationRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/vptoken",
          label: "VpToken",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/oid-4-vpauthorizationresponse",
          label: "OID4VPAuthorizationResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialmeta",
          label: "CredentialMeta",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/trustedauthoritiesquery",
          label: "TrustedAuthoritiesQuery",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/claimsquery",
          label: "ClaimsQuery",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialquery",
          label: "CredentialQuery",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialsetquery",
          label: "CredentialSetQuery",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/dcqlquery",
          label: "DcqlQuery",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/clientinfo",
          label: "ClientInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/authenticateduser",
          label: "AuthenticatedUser",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/unauthenticateduser",
          label: "UnauthenticatedUser",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credential",
          label: "Credential",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialsdto",
          label: "CredentialsDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialconfigdto",
          label: "CredentialConfigDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/legalregistrationnumberrequest",
          label: "LegalRegistrationNumberRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/compliancerequest",
          label: "ComplianceRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/jsonwebkeydto",
          label: "JsonWebKeyDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/verificationmethoddto",
          label: "VerificationMethodDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/servicedto",
          label: "ServiceDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/diddocumentdto",
          label: "DIDDocumentDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/didserviceconfigdto",
          label: "DidServiceConfigDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/keytype",
          label: "KeyType",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/keyinfodto",
          label: "KeyInfoDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/keyconfigdto",
          label: "KeyConfigDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/partialtypeclass",
          label: "PartialTypeClass",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/signrequest",
          label: "SignRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/proofdocument",
          label: "ProofDocument",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/signrequestjwt",
          label: "SignRequestJwt",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/signedjwtresponse",
          label: "SignedJwtResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/validaterequest",
          label: "ValidateRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/validatejwtrequest",
          label: "ValidateJWTRequest",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/issueconfigurationdto",
          label: "IssueConfigurationDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/issueconfigurationconfigdto",
          label: "IssueConfigurationConfigDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/dcpcredentialrequestinitiation",
          label: "DCPCredentialRequestInitiation",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/authorizedrequestparams",
          label: "AuthorizedRequestParams",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/oid-4-vcicredentialrequestinitiation",
          label: "OID4VCICredentialRequestInitiation",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialofferstatus",
          label: "CredentialOfferStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/transactioncode",
          label: "TransactionCode",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/preauthorizedcodegrant",
          label: "PreAuthorizedCodeGrant",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/authorizationcode",
          label: "AuthorizationCode",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialoffergrants",
          label: "CredentialOfferGrants",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialoffer",
          label: "CredentialOffer",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialcontainer",
          label: "CredentialContainer",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialmessage",
          label: "CredentialMessage",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialobject",
          label: "CredentialObject",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialoffermessage",
          label: "CredentialOfferMessage",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialdefinition",
          label: "CredentialDefinition",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/logo",
          label: "Logo",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/image",
          label: "Image",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/extendeddisplay",
          label: "ExtendedDisplay",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/basedisplay",
          label: "BaseDisplay",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/claimdescription",
          label: "ClaimDescription",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialmetadata",
          label: "CredentialMetadata",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialconfiguration",
          label: "CredentialConfiguration",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialrequestencryption",
          label: "CredentialRequestEncryption",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialresponseencryption",
          label: "CredentialResponseEncryption",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/batchcredentialissuance",
          label: "BatchCredentialIssuance",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/logodisplay",
          label: "LogoDisplay",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialissuermetadata",
          label: "CredentialIssuerMetadata",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialrequestcredential",
          label: "CredentialRequestCredential",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialrequestmessage",
          label: "CredentialRequestMessage",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/dcpcredentialstatus",
          label: "DCPCredentialStatus",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/authorizationdetail",
          label: "AuthorizationDetail",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/accesstoken",
          label: "AccessToken",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/nonceresponse",
          label: "NonceResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialitem",
          label: "CredentialItem",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/immediatecredentialresponse",
          label: "ImmediateCredentialResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/deferredcredentialresponse",
          label: "DeferredCredentialResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/jwtproof",
          label: "JwtProof",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/vpproof",
          label: "VpProof",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/divpproof",
          label: "DiVpProof",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/attestationproof",
          label: "AttestationProof",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/wallet/schemas/credentialrequest",
          label: "CredentialRequest",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
