import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "apis/analytics-data-plane/tsg-analytics-data-plane",
    },
    {
      type: "category",
      label: "Settings",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/analytics-data-plane/config-controller-get-settings",
          label: "Retrieve settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/config-controller-update-settings",
          label: "Update settings",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/config-controller-upload-file",
          label: "Upload logo",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Authentication",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/analytics-data-plane/auth-controller-get-user",
          label: "Retrieve current user status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/auth-controller-login",
          label: "Login redirect",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/auth-controller-logout",
          label: "Logout redirect",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/auth-controller-callback",
          label: "Login callback",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Data Plane",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/analytics-data-plane/data-plane-controller-get-catalog",
          label: "Get catalog",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/data-plane-controller-health-check",
          label: "Health check",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/transfer-controller-request-transfer",
          label: "Request Transfer",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/transfer-controller-start-transfer",
          label: "Start transfer process",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/transfer-controller-complete-transfer",
          label: "Complete transfer process",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/transfer-controller-terminate-transfer",
          label: "Terminate transfer process",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/transfer-controller-suspend-transfer",
          label: "Suspend transfer process",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Data Plane Management",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/analytics-data-plane/data-plane-management-controller-get-state",
          label: "Get Data Plane state",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/data-plane-management-controller-get-catalog",
          label: "Get catalog",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/data-plane-management-controller-get-registry-addresses",
          label: "Get registry addresses",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/data-plane-management-controller-get-catalog-by-participant-id",
          label: "Get catalog by participant ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/data-plane-management-controller-get-participant-id",
          label: "Get current participant ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/data-plane-management-controller-refresh-registration",
          label: "(Re)register data plane",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/data-plane-management-controller-get-dataset-config",
          label: "Get dataset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/data-plane-management-controller-update-dataset-config",
          label: "Update dataset",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/data-plane-management-controller-add-dataset",
          label: "Add dataset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/data-plane-management-controller-delete-dataset",
          label: "Delete dataset",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/transfers-management-controller-get-transfers",
          label: "Get all transfers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/transfers-management-controller-get-transfer",
          label: "Get transfer by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/transfers-management-controller-get-metadata",
          label: "Get metadata of transfer by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/transfers-management-controller-start-transfer",
          label: "Start a transfer by ID",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/transfers-management-controller-complete-transfer",
          label: "Complete a transfer by ID",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/transfers-management-controller-terminate-transfer",
          label: "Terminate a transfer by ID",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/transfers-management-controller-suspend-transfer",
          label: "Suspend a transfer by ID",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/orchestration-management-controller-get-jobs-for-algorithm-instance",
          label: "Get jobs for algorithm instance",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/orchestration-management-controller-get-job-pods",
          label: "Get job pods",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/orchestration-management-controller-get-job-logs",
          label: "Get job logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/orchestration-management-controller-spawn-job",
          label: "Spawn a job",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Files",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/analytics-data-plane/files-controller-get-files",
          label: "Get all files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/files-controller-upload-file",
          label: "Upload files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/files-controller-sync-files",
          label: "Sync files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/files-controller-get-file",
          label: "Get file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/files-controller-update-file-metadata",
          label: "Update file metadata",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/files-controller-remove-file",
          label: "Delete file",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/files-controller-preview-file",
          label: "Preview file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/files-controller-update-file",
          label: "Upload updated file",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/files-controller-get-csvw",
          label: "Get CSVW",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/files-controller-get-dataset",
          label: "Get dataset",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Algorithm Instances",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/analytics-data-plane/algorithm-instances-management-controller-find-all",
          label: "Get all algorithm instances",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/algorithm-instances-management-controller-create",
          label: "Create algorithm instance",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/algorithm-instances-management-controller-find-by-transfer-id",
          label: "Get an algorithm instance by transfer ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/algorithm-instances-management-controller-find-one",
          label: "Get an algorithm instance by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/algorithm-instances-management-controller-remove",
          label: "Delete an algorithm instance by ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/algorithm-instances-controller-create-algorithm-instance",
          label: "Create an algorithm instance",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/algorithm-instances-controller-start-algorithm-instance",
          label: "Start an algorithm instance",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/events-management-controller-get-event-data-for-management",
          label: "Download algorithm event data (management)",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Project Agreements",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/analytics-data-plane/project-agreements-controller-handle-signature-request-message",
          label: "Handle Signature Request Message",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/project-agreements-controller-handle-finalization-message",
          label: "Handle Finalization Message",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/project-agreements-controller-handle-signature-callback",
          label: "Handle Signature Callback",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/project-agreements-management-controller-get-all",
          label: "Get all Project Agreements",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/project-agreements-management-controller-create",
          label: "Create Project Agreement",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/project-agreements-management-controller-sign-project-agreement",
          label: "Sign Project Agreement",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/project-agreements-management-controller-link-dataset-to-project-agreement",
          label: "Link Dataset to Project Agreement",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/project-agreements-management-controller-unlink-dataset-from-project-agreement",
          label: "Unlink Dataset from Project Agreement",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Events",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/analytics-data-plane/events-controller-create-internal-event",
          label: "EventsController_createInternalEvent",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/events-controller-create-algorithm-event",
          label: "Create an algorithm event",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/events-controller-upload-event-data",
          label: "Upload algorithm event data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/events-controller-get-event-data",
          label: "EventsController_getEventData",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/events-controller-poll-for-algorithm-event",
          label: "Poll for the next available algorithm event for this algorithm instance",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/events-controller-get-events-for-algorithm-instance",
          label: "Get all events for an algorithm instance",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/runtimeconfigdto",
          label: "RuntimeConfigDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/errordto",
          label: "ErrorDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/dataplanedetailsdto",
          label: "DataPlaneDetailsDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/dataplanestatedto",
          label: "DataPlaneStateDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/constraintschema",
          label: "ConstraintSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/permissionschema",
          label: "PermissionSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/prohibitionschema",
          label: "ProhibitionSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/dutyschema",
          label: "DutySchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/policyschema",
          label: "PolicySchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/durationschema",
          label: "DurationSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/datasetschema",
          label: "DatasetSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/resourceschema",
          label: "ResourceSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/catalogrecordschema",
          label: "CatalogRecordSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/dataserviceschema",
          label: "DataServiceSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/catalogschema",
          label: "CatalogSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/endpointpropertyschema",
          label: "EndpointPropertySchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/dataaddressschema",
          label: "DataAddressSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/transferrequestmessageschema",
          label: "TransferRequestMessageSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/dataplaneproperty",
          label: "DataPlaneProperty",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/dataplaneaddressdto",
          label: "DataPlaneAddressDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/dataplanerequestresponsedto",
          label: "DataPlaneRequestResponseDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/transferstartmessageschema",
          label: "TransferStartMessageSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/transfercompletionmessageschema",
          label: "TransferCompletionMessageSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/transferterminationmessageschema",
          label: "TransferTerminationMessageSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/transfersuspensionmessageschema",
          label: "TransferSuspensionMessageSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/transferdto",
          label: "TransferDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/agreementschema",
          label: "AgreementSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/metadatadto",
          label: "MetadataDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/clientinfo",
          label: "ClientInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/authenticateduser",
          label: "AuthenticatedUser",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/unauthenticateduser",
          label: "UnauthenticatedUser",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/csvwtableschema",
          label: "CSVWTableSchema",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/csvwtable",
          label: "CSVWTable",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/csvw",
          label: "CSVW",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/filemetadatadto",
          label: "FileMetadataDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/fileupdatedto",
          label: "FileUpdateDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/timedto",
          label: "TimeDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/managedfieldsentrydto",
          label: "ManagedFieldsEntryDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/ownerreferencedto",
          label: "OwnerReferenceDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/objectmetadto",
          label: "ObjectMetaDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/jobdto",
          label: "JobDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/podspecdto",
          label: "PodSpecDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/podstatusdto",
          label: "PodStatusDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/poddto",
          label: "PodDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/podlistdto",
          label: "PodListDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/algorithmdefinitiondto",
          label: "AlgorithmDefinitionDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/algorithmeventdto",
          label: "AlgorithmEventDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/internaleventdto",
          label: "InternalEventDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/algorithminstancedto",
          label: "AlgorithmInstanceDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/createalgorithminstancedto",
          label: "CreateAlgorithmInstanceDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/orchestrationstatusdto",
          label: "OrchestrationStatusDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/projectagreementparticipant",
          label: "ProjectAgreementParticipant",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/projectagreementdto",
          label: "ProjectAgreementDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/projectagreementcallbackdto",
          label: "ProjectAgreementCallbackDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/signaturerequestmessage",
          label: "SignatureRequestMessage",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/dcpcredentialrequestinitiation",
          label: "DCPCredentialRequestInitiation",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/projectagreementfinalizationmessage",
          label: "ProjectAgreementFinalizationMessage",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/signatureresponsemessage",
          label: "SignatureResponseMessage",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/projectagreementdetaildto",
          label: "ProjectAgreementDetailDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/createinternaleventdto",
          label: "CreateInternalEventDto",
          className: "schema",
        },
        {
          type: "doc",
          id: "apis/analytics-data-plane/schemas/createalgorithmeventdto",
          label: "CreateAlgorithmEventDto",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
