openapi: 3.1.0
info:
  title: TSG - Data Plane API
  description: API definition for communication from the Control plane towards a Data plane
  version: 0.0.1
  license: 
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers: 
  - url: http://localhost
security: 
  -  BearerAuth: []
tags:
  - name: generic
    description: Generic Control Plane-Data Plane interactions
  - name: transfer
    description: Transfer related endpoints
paths:
  /catalog:
    get:
      operationId: catalogPull
      summary: Pull up to date
      tags: 
        -  generic
      parameters: 
        - name: If-None-Match
          in: header
          description: Known entity tag to indicate the known hash of the last request (ETag)
          schema:
            type: string
          required: false
      responses: 
        "200":
          description: Successful Catalog response
          headers:
            ETag:
              schema: 
                type: string
              description: Entity tag with a hash of the response which only changes when the catalog itself has changed
          content:
            application/json:
              schema:
                $ref: ../schemas/dsp.schema.json#/definitions/CatalogDto
        "304":
          description: No change in the catalog
        "501":
          description: Data plane does not support pulling of catalog information
  /health:
    get:
      operationId: healthCheck
      summary: Health check
      tags:
        - generic
      responses: 
        "200":
          description: Successful health check
        "4XX":
          description: Unexpected behaviour
        "5XX":
          description: Data plane error
  /transfer/{role}:
    post:
      operationId: requestTransfer
      tags: 
        -  transfer
      summary: Request transfer
      parameters: 
        - name: role
          in: path
          required: true
          schema: 
            type: string
            enum: ["consumer", "provider"]
      requestBody: 
        content: 
          application/json: 
            schema:
              $ref: ../schemas/dsp.schema.json#/definitions/TransferRequestMessageDto
      responses: 
        "200":
          description: Accepted transfer request
          content:
            application/json:
              schema: 
                $ref: ../schemas/data-planes.schema.json#/definitions/DataPlaneRequestResponseDto
        "4XX":
          description: Declined transfer request
  /transfer/{transferId}/start:
    post:
      operationId: startTransfer
      summary: Start transfer
      tags: 
        -  transfer
      parameters: 
        - name: transferId
          in: path
          required: true
          schema: 
            type: string
      requestBody: 
        content: 
          application/json: 
            schema:
              $ref: ../schemas/dsp.schema.json#/definitions/TransferStartMessageDto
      responses: 
        "202":
          description: Accepted transfer start signal
        "404":
          description: Transfer not found
  /transfer/{transferId}/complete:
    post:
      operationId: completeTransfer
      summary: Complete transfer
      tags: 
        -  transfer
      parameters: 
        - name: transferId
          in: path
          required: true
          schema: 
            type: string
      requestBody: 
        content: 
          application/json: 
            schema:
              $ref: ../schemas/dsp.schema.json#/definitions/TransferCompletionMessageDto
      responses: 
        "202":
          description: Accepted transfer complete signal
        "404":
          description: Transfer not found
  /transfer/{transferId}/terminate:
    post:
      operationId: terminateTransfer
      summary: Terminate transfer
      tags: 
        -  transfer
      parameters: 
        - name: transferId
          in: path
          required: true
          schema: 
            type: string
      requestBody: 
        content: 
          application/json: 
            schema:
              $ref: ../schemas/dsp.schema.json#/definitions/TransferTerminationMessageDto
      responses: 
        "202":
          description: Accepted transfer terminate signal
        "404":
          description: Transfer not found
  /transfer/{transferId}/suspend:
    post:
      operationId: suspendTransfer
      summary: Suspend transfer
      tags: 
        -  transfer
      parameters: 
        - name: transferId
          in: path
          required: true
          schema: 
            type: string
      requestBody: 
        content: 
          application/json: 
            schema:
              $ref: ../schemas/dsp.schema.json#/definitions/TransferSuspensionMessageDto
      responses: 
        "202":
          description: Accepted transfer suspend signal
        "404":
          description: Transfer not found
        



components: 
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
#   schemas:
#     Catalog: