openapi: 3.1.0
info:
  title: TSG - Dataspace Protocol - Negotiation Callback API
  description: API definition for communication for consumers in negotiation sequences between Control Planes
  version: 0.0.1
  license: 
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers: 
  - url: http://localhost
security: 
  -  BearerAuth: []
paths: 
  /negotiation/callbacks/{id}/offer:
    post:
      operationId: offerCallback
      summary: Post a contract offer to a callback address
      parameters: 
        - name: id
          in: path
          required: true
          schema: 
            type: string
      requestBody: 
        content:
          application/json:
            schema: 
              $ref: ../schemas/dsp.schema.json#/definitions/ContractOfferMessageDto
      responses: 
        200:
          description: Offer processed
        404:
          description: Negotiation process not found
        4XX:
          description: Request error
  /negotiation/callbacks/{id}/agreement:
    post:
      operationId: agreementCallback
      summary: Post a contract agreement to a callback address
      parameters: 
        - name: id
          in: path
          required: true
          schema: 
            type: string
      requestBody: 
        content:
          application/json:
            schema: 
              $ref: ../schemas/dsp.schema.json#/definitions/ContractAgreementMessageDto
      responses: 
        200:
          description: Agreement processed
        404:
          description: Negotiation process not found
        4XX:
          description: Request error
  /negotiation/callbacks/{id}/events:
    post:
      operationId: eventsCallback
      summary: Post a negotiation finalized event to a callback address
      parameters: 
        - name: id
          in: path
          required: true
          schema: 
            type: string
      requestBody: 
        content:
          application/json:
            schema: 
              $ref: ../schemas/dsp.schema.json#/definitions/ContractNegotiationEventMessageDto
      responses: 
        200:
          description: Negotiation finalized event processed
        404:
          description: Negotiation process not found
        4XX:
          description: Request error
components: 
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
