openapi: 3.1.0
info:
  title: TSG - Management API
  description: API definition for management of the Control Plane by administrators or data planes
  version: 0.0.1
  license: 
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers: 
  - url: http://localhost
security: 
  -  BearerAuth: []
paths: 
  /transfer/request:
    post:
      operationId: transferRequest
      summary: Request a transfer from the provider
      requestBody: 
        content:
          application/json:
            schema: 
              $ref: ../schemas/dsp.schema.json#/definitions/TransferRequestMessageDto
      responses: 
        200:
          description: Transfer process response
          content:
            application/json:
              schema: 
                $ref: ../schemas/dsp.schema.json#/definitions/TransferProcessDto
        4XX:
          description: Request error
  /transfer/{id}:
    get: 
      operationId: requestTransferStatus
      summary: Request the transfer process status object
      parameters: 
        - name: id
          in: path
          required: true
          schema: 
            type: string
      responses: 
        200:
          description: Transfer process response
          content:
            application/json:
              schema: 
                $ref: ../schemas/dsp.schema.json#/definitions/TransferProcessDto
        404:
          description: Transfer process not found
  /transfer/{id}/start:
    post:
      operationId: startTransfer
      summary: Start the transfer process by the consumer
      parameters: 
        - name: id
          in: path
          required: true
          schema: 
            type: string
      requestBody: 
        content: 
          application/json:
            schema: 
              $ref: ../schemas/dsp.schema.json#/definitions/TransferStartMessageDto
      responses: 
        200:
          description: Transfer start processed
        404:
          description: Transfer process not found
        

  /transfer/{id}/complete:
    post:
      operationId: completeTransfer
      summary: Complete the transfer process by the consumer
      parameters: 
        - name: id
          in: path
          required: true
          schema: 
            type: string
      requestBody: 
        content: 
          application/json:
            schema: 
              $ref: ../schemas/dsp.schema.json#/definitions/TransferCompletionMessageDto
      responses: 
        200:
          description: Transfer complete processed
        404:
          description: Transfer process not found
        

  /transfer/{id}/terminate:
    post:
      operationId: terminateTransfer
      summary: Terminate the transfer process by the consumer
      parameters: 
        - name: id
          in: path
          required: true
          schema: 
            type: string
      requestBody: 
        content: 
          application/json:
            schema: 
              $ref: ../schemas/dsp.schema.json#/definitions/TransferTerminationMessageDto
      responses: 
        200:
          description: Transfer terminate processed
        404:
          description: Transfer process not found
        

  /transfer/{id}/suspend:
    post:
      operationId: suspendTransfer
      summary: Suspend the transfer process by the consumer
      parameters: 
        - name: id
          in: path
          required: true
          schema: 
            type: string
      requestBody: 
        content: 
          application/json:
            schema: 
              $ref: ../schemas/dsp.schema.json#/definitions/TransferSuspensionMessageDto
      responses: 
        200:
          description: Transfer suspend processed
        404:
          description: Transfer process not found
        

components: 
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
