export default {
  "@context": {
    tsg: "https://dataspac.es/ns/tsg#",
    iana: "https://www.iana.org/assignments/media-types/",
    "dct:created": { "@type": "xsd:dateTime" },
    "dct:publisher": { "@type": "@id" },
    "dct:format": { "@type": "@id" },
    "dct:type": { "@type": "@id" },
    "dcat:hasVersion": { "@container": "@set", "@type": "@id" },
    "dcat:contactPoint": { "@type": "@id" },
    "dcat:landingPage": { "@type": "@id" },
    "dcat:theme": { "@type": "@id", "@container": "@set" },
    "dct:isReferencedBy": { "@type": "@id" },
    "dct:language": { "@type": "@id" },
    "dct:license": { "@type": "@id" },
    "dct:relation": { "@type": "@id" },
    "dcat:isVersionOf": { "@type": "@id" },
    "dcat:hasCurrentVersion": { "@type": "@id" },
    "dcat:previousVersion": { "@type": "@id" },
    "dcat:themeTaxonomy": { "@type": "@id" },
  },
};
