apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "control-plane.fullname" . }}-config
  labels: {{ include "control-plane.labels" $ | nindent 4 }}
data:
  config.yaml: |-
    {{- tpl (.Values.config | toYaml) $ | nindent 4}}