import { MigrationInterface, QueryRunner } from "typeorm";

export class Postgres20260202164948 implements MigrationInterface {
    name = 'Postgres20260202164948'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" DROP CONSTRAINT "PK_99fc14b0dcc6dd517cb33446f60"`);
        // await queryRunner.query(`ALTER TABLE "authorization_request_dao" DROP COLUMN "identifier"`);
        await queryRunner.query(`ALTER TABLE "oauth_user" ADD "ownerId" character varying`);
        await queryRunner.query(`ALTER TABLE "oauth_user" ADD "ownerIdentifier" character varying`);
        await queryRunner.query(`ALTER TABLE "oauth_user" ADD "createdBy" character varying`);
        await queryRunner.query(`ALTER TABLE "oauth_user" ADD "tenantId" character varying`);
        await queryRunner.query(`ALTER TABLE "oauth_user" ADD "permissions" text NOT NULL DEFAULT ''`);
        // await queryRunner.query(`ALTER TABLE "authorization_request_dao" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" RENAME COLUMN "identifier" TO "id"`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" ADD CONSTRAINT "PK_de07b115c55ebe75c9d644629d2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "oauth_client" ADD "ownerId" character varying`);
        await queryRunner.query(`ALTER TABLE "oauth_client" ADD "ownerIdentifier" character varying`);
        await queryRunner.query(`ALTER TABLE "oauth_client" ADD "createdBy" character varying`);
        await queryRunner.query(`ALTER TABLE "oauth_client" ADD "tenantId" character varying`);
        await queryRunner.query(`ALTER TABLE "oauth_client" ADD "permissions" text NOT NULL DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" DROP CONSTRAINT "FK_f1462bf9279add899e91ff7489a" CASCADE`);
        await queryRunner.query(`ALTER TABLE "web_authn_credential" DROP CONSTRAINT "FK_609fa7bda999525a4fa55cd9354" CASCADE`);
        await queryRunner.query(`ALTER TABLE "totp_credential" DROP CONSTRAINT "FK_9180faedc035e0ba4514062a302" CASCADE`);
        await queryRunner.query(`ALTER TABLE "recovery_code" DROP CONSTRAINT "FK_0e10289994b9a90be4cde06e15c" CASCADE`);
        await queryRunner.query(`ALTER TABLE "oauth_user" DROP CONSTRAINT "PK_c1e31b84cedaa9135fd13ca1620" CASCADE`);
        // await queryRunner.query(`ALTER TABLE "oauth_user" DROP COLUMN "id"`);
        // await queryRunner.query(`ALTER TABLE "oauth_user" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "oauth_user" ALTER COLUMN "id" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "oauth_user" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "oauth_user" ADD CONSTRAINT "PK_c1e31b84cedaa9135fd13ca1620" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "recovery_code" DROP CONSTRAINT "PK_b7f1e23329e93a80e25fd281922" CASCADE`);
        // await queryRunner.query(`ALTER TABLE "recovery_code" DROP COLUMN "id"`);
        // await queryRunner.query(`ALTER TABLE "recovery_code" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recovery_code" ALTER COLUMN "id" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "recovery_code" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "recovery_code" ADD CONSTRAINT "PK_b7f1e23329e93a80e25fd281922" PRIMARY KEY ("id")`);
        // await queryRunner.query(`ALTER TABLE "recovery_code" DROP COLUMN "userId"`);
        // await queryRunner.query(`ALTER TABLE "recovery_code" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recovery_code" ALTER COLUMN "userId" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "totp_credential" DROP CONSTRAINT "PK_6ecb771ad9517a5b9ba9c8473e7" CASCADE`);
        // await queryRunner.query(`ALTER TABLE "totp_credential" DROP COLUMN "id"`);
        // await queryRunner.query(`ALTER TABLE "totp_credential" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "totp_credential" ALTER COLUMN "id" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "totp_credential" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "totp_credential" ADD CONSTRAINT "PK_6ecb771ad9517a5b9ba9c8473e7" PRIMARY KEY ("id")`);
        // await queryRunner.query(`ALTER TABLE "totp_credential" DROP COLUMN "userId"`);
        // await queryRunner.query(`ALTER TABLE "totp_credential" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "totp_credential" ALTER COLUMN "userId" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "web_authn_credential" DROP CONSTRAINT "PK_75836493a407b2d7a4cb926ad97" CASCADE`);
        // await queryRunner.query(`ALTER TABLE "web_authn_credential" DROP COLUMN "id"`);
        // await queryRunner.query(`ALTER TABLE "web_authn_credential" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "web_authn_credential" ALTER COLUMN "id" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "web_authn_credential" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "web_authn_credential" ADD CONSTRAINT "PK_75836493a407b2d7a4cb926ad97" PRIMARY KEY ("id")`);
        // await queryRunner.query(`ALTER TABLE "web_authn_credential" DROP COLUMN "userId"`);
        // await queryRunner.query(`ALTER TABLE "web_authn_credential" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "web_authn_credential" ALTER COLUMN "userId" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "token_dao" DROP CONSTRAINT "PK_126e2df3b842e5abafae4166274" CASCADE`);
        // await queryRunner.query(`ALTER TABLE "token_dao" DROP COLUMN "id"`);
        // await queryRunner.query(`ALTER TABLE "token_dao" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "token_dao" ALTER COLUMN "id" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "token_dao" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "token_dao" ADD CONSTRAINT "PK_126e2df3b842e5abafae4166274" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "token_dao" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "token_dao" ADD "userId" character varying`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" ADD "userId" character varying`);
        await queryRunner.query(`ALTER TABLE "oauth_client" DROP CONSTRAINT "PK_d6e58a7e0ec3ac17a67ba7f97cd" CASCADE`);
        // await queryRunner.query(`ALTER TABLE "oauth_client" DROP COLUMN "id"`);
        // await queryRunner.query(`ALTER TABLE "oauth_client" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "oauth_client" ALTER COLUMN "id" TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "oauth_client" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "oauth_client" ADD CONSTRAINT "PK_d6e58a7e0ec3ac17a67ba7f97cd" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "recovery_code" ADD CONSTRAINT "FK_0e10289994b9a90be4cde06e15c" FOREIGN KEY ("userId") REFERENCES "oauth_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "totp_credential" ADD CONSTRAINT "FK_9180faedc035e0ba4514062a302" FOREIGN KEY ("userId") REFERENCES "oauth_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "web_authn_credential" ADD CONSTRAINT "FK_609fa7bda999525a4fa55cd9354" FOREIGN KEY ("userId") REFERENCES "oauth_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" ADD CONSTRAINT "FK_f1462bf9279add899e91ff7489a" FOREIGN KEY ("userId") REFERENCES "oauth_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" DROP CONSTRAINT "FK_f1462bf9279add899e91ff7489a"`);
        await queryRunner.query(`ALTER TABLE "web_authn_credential" DROP CONSTRAINT "FK_609fa7bda999525a4fa55cd9354"`);
        await queryRunner.query(`ALTER TABLE "totp_credential" DROP CONSTRAINT "FK_9180faedc035e0ba4514062a302"`);
        await queryRunner.query(`ALTER TABLE "recovery_code" DROP CONSTRAINT "FK_0e10289994b9a90be4cde06e15c"`);
        await queryRunner.query(`ALTER TABLE "oauth_client" DROP CONSTRAINT "PK_d6e58a7e0ec3ac17a67ba7f97cd"`);
        await queryRunner.query(`ALTER TABLE "oauth_client" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "oauth_client" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "oauth_client" ADD CONSTRAINT "PK_d6e58a7e0ec3ac17a67ba7f97cd" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "token_dao" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "token_dao" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "token_dao" DROP CONSTRAINT "PK_126e2df3b842e5abafae4166274"`);
        await queryRunner.query(`ALTER TABLE "token_dao" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "token_dao" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "token_dao" ADD CONSTRAINT "PK_126e2df3b842e5abafae4166274" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "web_authn_credential" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "web_authn_credential" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "web_authn_credential" DROP CONSTRAINT "PK_75836493a407b2d7a4cb926ad97"`);
        await queryRunner.query(`ALTER TABLE "web_authn_credential" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "web_authn_credential" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "web_authn_credential" ADD CONSTRAINT "PK_75836493a407b2d7a4cb926ad97" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "totp_credential" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "totp_credential" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "totp_credential" DROP CONSTRAINT "PK_6ecb771ad9517a5b9ba9c8473e7"`);
        await queryRunner.query(`ALTER TABLE "totp_credential" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "totp_credential" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "totp_credential" ADD CONSTRAINT "PK_6ecb771ad9517a5b9ba9c8473e7" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "recovery_code" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "recovery_code" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recovery_code" DROP CONSTRAINT "PK_b7f1e23329e93a80e25fd281922"`);
        await queryRunner.query(`ALTER TABLE "recovery_code" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "recovery_code" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "recovery_code" ADD CONSTRAINT "PK_b7f1e23329e93a80e25fd281922" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "oauth_user" DROP CONSTRAINT "PK_c1e31b84cedaa9135fd13ca1620"`);
        await queryRunner.query(`ALTER TABLE "oauth_user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "oauth_user" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "oauth_user" ADD CONSTRAINT "PK_c1e31b84cedaa9135fd13ca1620" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "recovery_code" ADD CONSTRAINT "FK_0e10289994b9a90be4cde06e15c" FOREIGN KEY ("userId") REFERENCES "oauth_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "totp_credential" ADD CONSTRAINT "FK_9180faedc035e0ba4514062a302" FOREIGN KEY ("userId") REFERENCES "oauth_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "web_authn_credential" ADD CONSTRAINT "FK_609fa7bda999525a4fa55cd9354" FOREIGN KEY ("userId") REFERENCES "oauth_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" ADD CONSTRAINT "FK_f1462bf9279add899e91ff7489a" FOREIGN KEY ("userId") REFERENCES "oauth_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_client" DROP COLUMN "permissions"`);
        await queryRunner.query(`ALTER TABLE "oauth_client" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "oauth_client" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "oauth_client" DROP COLUMN "ownerIdentifier"`);
        await queryRunner.query(`ALTER TABLE "oauth_client" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" DROP CONSTRAINT "PK_de07b115c55ebe75c9d644629d2"`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "oauth_user" DROP COLUMN "permissions"`);
        await queryRunner.query(`ALTER TABLE "oauth_user" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "oauth_user" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "oauth_user" DROP COLUMN "ownerIdentifier"`);
        await queryRunner.query(`ALTER TABLE "oauth_user" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" ADD "identifier" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "authorization_request_dao" ADD CONSTRAINT "PK_99fc14b0dcc6dd517cb33446f60" PRIMARY KEY ("identifier")`);
    }

}
