db:
  type: "sqlite"
  database: "test.db"

auth:
  enabled: false
  # authorizationURL: https://localhost/login/oauth/authorize
  # tokenURL: https://localhost/api/login/oauth/access_token
  # introspectionURL: https://localhost/api/login/oauth/introspect
  # callbackURL: http://localhost:5173/api/auth/callback
  # clientId:
  # clientSecret:
  # clientUsername:
  # clientPassword:
  # rolePath: "$.roles[*].name"
  # redirectURL: http://localhost:5173/

controlPlane:
  dataPlaneEndpoint: http://localhost:3000/api/data-plane
  managementEndpoint: http://localhost:3000/api/management
  controlEndpoint: http://localhost:3000

dataset:
  title: HTTP Dataset
  versions:
    - version: "0.9.2"
      distributions:
        - format: "http/json"
          backendUrl: https://httpbin.org/anything
          openApiSpecRef: "https://httpbin.org/spec.json"
    - version: "0.9.1"
      distributions:
        - format: "http/json"
          backendUrl: https://httpbin.org/anything
          openApiSpecRef: "https://httpbin.org/spec.json"
    - version: "0.9.0"
      distributions:
        - format: "http/json"
          backendUrl: https://httpbin.org/anything
          openApiSpecRef: "https://httpbin.org/spec.json"
  currentVersion: "0.9.2"
