server:
  port: 3004
  listen: "0.0.0.0"
  publicAddress: http://localhost:3004

db:
  type: "sqlite"
  database: "sso-bridge-db.sqlite"

initClients:
  - clientId: "test-client"
    clientSecret: "test-secret"
    roles:
      - "admin"
    name: "Test Client"
    description: "This is a test client"

initUsers:
  - username: "alice"
    password: "password"
    email: "alice@example.com"
    roles:
      - "admin"

  - username: "bob"
    password: "password"
    email: "bob@example.com"
    roles:
      - "user"
