server:
  port: 3004
  listen: "0.0.0.0"
  publicAddress: http://localhost:3004

db:
  type: "sqlite"
  database: "sso-bridge-db.sqlite"

initRoles:
  - name: "ssobridge_admin"
    description: "SSO bridge administrator role with full access"
  - name: "ssobridge_user"
    description: "SSO bridge regular user role with limited access"

initClients:
  - clientId: "test-client"
    clientSecret: "test-secret"
    secretName: "k8s-secret-name"
    redirectUris:
      - "http://localhost:3000"
    roles:
      - "ssobridge_admin"
    name: "Test Client"
    description: "This is a test client"

initUsers:
  - username: "alice"
    password: "password"
    email: "alice@example.com"
    roles:
      - "ssobridge_admin"

  - username: "bob"
    password: "password"
    email: "bob@example.com"
    roles:
      - "ssobridge_user"
