db:
  type: "sqlite"
  # database: "test2.db"
  database: ":memory:"

auth:
  enabled: false

controlPlane:
  dataPlaneEndpoint: http://localhost:3002/api/data-plane
  managementEndpoint: http://localhost:3002/api/management
  controlEndpoint: http://localhost:3002

server:
  port: 3003
  publicAddress: http://localhost:3003

files:
  path: "./uploads"

runtime:
  color: "#3B8BF6"

kubernetesConfig:
  namespace: analytics-dataplane-test
