db:
  type: "sqlite"
  # database: "test.db"
  database: ":memory:"

auth:
  enabled: false

controlPlane:
  dataPlaneEndpoint: http://localhost:3000/api/data-plane
  managementEndpoint: http://localhost:3000/api/management
  controlEndpoint: http://localhost:3000

server:
  port: 3001
  publicAddress: http://localhost:3001

runtime:
  color: "#3B8BF6"

files:
  path: "./uploads"

kubernetesConfig:
  namespace: analytics-dataplane-test
