apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tsg.fullname" . }}-config
  labels: {{ include "tsg.labels" $ | nindent 4 }}
data:
  config.yaml: |-
    {{- tpl (.Values.config | toYaml) $ | nindent 4}}