apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tsg.fullname" . }}
  labels: {{ include "tsg.labels" $ | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "tsg.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "tsg.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ tpl (toYaml .Values.config) . | sha256sum }}
    spec:
      containers:
        - name: {{ template "tsg.name" . }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}"
          imagePullPolicy: Always
          env:
            - name: SUBPATH
              value: {{ template "tsg.subPath" . }}
            {{- if contains "Mi" .Values.resources.limits.memory}}
            - name: NODE_OPTIONS
              value: --max-old-space-size={{trimSuffix "Mi" .Values.resources.limits.memory | mulf 0.9 | floor}}
            {{- end }}
            {{- with concat .Values.env (fromYamlArray (list .Values.configFromSecrets "" | include "tsg.recurseSecretConfig"))}}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          resources: {{ .Values.resources | toYaml | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.config.server.port | default 3000 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.config.server.port | default 3000 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.config.server.port | default 3000 }}
          volumeMounts:
          - name: {{ template "tsg.name" . }}-config
            mountPath: "/app/config.yaml"
            subPath: "config.yaml"
          {{- if .Values.persistentVolume}}
          - name: {{ template "tsg.name" . }}-pvc
          {{- with .Values.persistentVolume }}
            mountPath: {{ .mountPath }}
            {{- end }}
          {{- end }}
      volumes:
      - name: {{ template "tsg.name" . }}-config
        configMap:
          name: {{ template "tsg.fullname" . }}-config
      {{- if .Values.persistentVolume }}
      - name: {{ template "tsg.name" . }}-pvc
        persistentVolumeClaim:
          claimName: {{ template "tsg.fullname" . }}-pvc
      {{- end }}