db:
  type: sqlite
  database: ":memory:"
  # database: tck-local.db
  synchronize: true

server:
  port: "32490"
  listen: "0.0.0.0"
  publicDomain: localhost:32490
  publicAddress: http://localhost:32490/api

auth:
  enabled: false

runtime:
  controlPlaneInteractions: manual

registry:
  useRegistry: false

iam:
  type: dev
  didId: did:web:localhost%3A32490

initCatalog:
  creator: did:web:localhost%3A32490
  publisher: did:web:localhost%3A32490
  title: TSG Test Connector
  description: TSG Test Connector testing Data Space Protocol support
  datasets: []
