server:
  publicAddress: http://localhost:3502
  publicDomain: localhost:3502
  port: 3502
  listen: "0.0.0.0"

db:
  type: "sqlite"
  database: "alfa.db"

auth:
  enabled: true
  openIdConfigurationURL: http://localhost:3700/.well-known/openid-configuration
  callbackURL: http://localhost:3552/api/auth/callback
  clientId: alfa-analytics-data-plane
  clientSecret: alfa-analytics-data-plane
  rolePath: "$.roles[*]"
  redirectURL: http://localhost:3552/

controlPlane:
  dataPlaneEndpoint: http://localhost:3501/data-plane
  managementEndpoint: http://localhost:3501/management
  controlEndpoint: http://localhost:3501
  walletEndpoint: http://localhost:3500

runtime:
  color: "#3B8BF6"

files:
  path: "./uploads"

orchestration:
  type: "docker"
  mountFiles: true
