server:
  publicAddress: http://localhost:3502
  publicDomain: localhost:3502
  port: 3502
  listen: "0.0.0.0"

db:
  type: "sqlite"
  database: "alfa.db"

auth:
  enabled: true
  openIdConfigurationURL: http://localhost:3700/.well-known/openid-configuration
  callbackURL: http://localhost:3552/api/auth/callback
  clientId: alfa-analytics-data-plane
  tokenEndpointAuthMethod: private_key_jwt
  privateKeyJwk:
    kty: EC
    x: nitXhI3Q5PC_K2drfQNG84l5XZw4l3nOcd3flYhHZYs
    y: 38vpVbroACnmdS0KHhlRc582dHxzVj-JxrMuZ1zCtX8
    crv: P-256
    d: eXdxjToDkX6-jJgnN4gWA4jriuzOoOdWkJor5c9TqAk
    kid: alfa-analytics-data-plane-key-1767782614226
    alg: ES256
    use: sig
  redirectURL: http://localhost:3552/

controlPlane:
  dataPlaneEndpoint: http://localhost:3501/data-plane
  managementEndpoint: http://localhost:3501/management
  controlEndpoint: http://localhost:3501
  walletEndpoint: http://localhost:3500

runtime:
  color: "#3B8BF6"

files:
  path: "./uploads"

orchestration:
  type: "docker"
  mountFiles: true

audit:
  logExecute: true
