server:
  publicAddress: http://localhost:3603
  publicDomain: localhost:3603
  port: 3603
  listen: "0.0.0.0"

db:
  type: "sqlite"
  database: "bravo-client.db"

auth:
  enabled: true
  openIdConfigurationURL: http://localhost:3700/.well-known/openid-configuration
  callbackURL: http://localhost:3653/api/auth/callback
  clientId: bravo-analytics-data-plane-client
  tokenEndpointAuthMethod: private_key_jwt
  privateKeyJwk:
    kty: EC
    x: 9E4CHxBJfmYzq-40kbSNCu_xkrs9u1_rG3dw-QiwA28
    y: eZh4c5Y1978C4CsH6uJM-eq1CeGGy_hPm2fFWZX_hfU
    crv: P-256
    d: CN7ImWz7ETut0I0O408A8Vv-Y0yseN5DJEiI53HoiRw
    kid: bravo-analytics-data-plane-client-key-1767782798995
    alg: ES256
    use: sig
  redirectURL: http://localhost:3653/

controlPlane:
  dataPlaneEndpoint: http://localhost:3601/data-plane
  managementEndpoint: http://localhost:3601/management
  controlEndpoint: http://localhost:3601
  walletEndpoint: http://localhost:3600

runtime:
  color: "#3B8BF6"

files:
  path: "./uploads"

orchestration:
  type: "docker"
  mountFiles: false

split:
  mode: client
  bridgePeerWsUrl: "ws://localhost:3602"

audit:
  logExecute: true
