server:
  publicAddress: http://localhost:3602
  publicDomain: localhost:3602
  port: 3602
  listen: "0.0.0.0"

db:
  type: "sqlite"
  database: "bravo.db"

auth:
  enabled: false

controlPlane:
  dataPlaneEndpoint: http://localhost:3601/data-plane
  managementEndpoint: http://localhost:3601/management
  controlEndpoint: http://localhost:3601
  walletEndpoint: http://localhost:3600

runtime:
  color: "#3B8BF6"

files:
  path: "./uploads"

orchestration:
  type: "docker"
  mountFiles: false
