server:
  publicAddress: http://localhost:3500
  publicDomain: localhost:3500
  port: 3500
  listen: "0.0.0.0"

db:
  type: "sqlite"
  database: "alfa.db"

auth:
  enabled: false

initKeys:
  - id: key-0
    type: EdDSA
    default: true

runtime:
  title: Alfa
  color: "#3B8BF6"
  acceptUnauthenticatedCredentialRequests: true
  issueMobileCredentials: true
  issueDebugCredentials: true

issuance:
  dcp:
    - credentialType:
        - ExampleCredential
      issuerId: did:web:localhost%3A3400
      preAuthorizedCode: 386527fd21960fd8bd3aa0208c9275a4437fde1bdae9469daaf91fb7cace67d827ff152e5f89c02ccdbde1766387feb2

trustAnchors:
  - id: did:web:localhost%3A3400
    credentialTypes:
      - ExampleCredential
      - alfa:ExampleCredential
      - http://localhost:3400/credentials/ExampleCredential

didServices:
  - id: did:web:localhost%3A3500#control-plane
    type: connector
    serviceEndpoint: http://localhost:3501/

did:
  method: "did:web:"
