.npm-package:
  extends: .base-rules
  stage: package
  rules:
    - if: '$RELEASE_NOW == "true"'
      when: never
    - if: $CI_COMMIT_TAG

cli-package:
  extends: .npm-package
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPMJS_TOKEN}" >> ./.npmrc
    - pnpm install --frozen-lockfile
    - pnpm --filter cli build
    - pnpm --filter cli publish --no-git-checks

e2e-dsp-local:
  extends: .base-rules
  stage: test
  tags:
    - saas-linux-medium-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - pnpm install --frozen-lockfile
    - pnpm build:libs
    - pnpm run --filter control-plane-api build
    - NODE_OPTIONS="--experimental-vm-modules" pnpm e2e:dsp-local

dsp-tck-fetch:
  image:
    name: eclipsedataspacetck/dsp-tck-runtime:1.0.0-RC4
    entrypoint:
      - "/bin/sh"
      - "-c"
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: "$CI_COMMIT_TAG"
  script:
    - echo "Fetching TCK test cases"
    - mkdir -p tools/e2e-testing/assets
    - cp /app/tck-runtime.jar tools/e2e-testing/assets/dsp-tck-runtime.jar
  artifacts:
    paths:
      - tools/e2e-testing/assets/dsp-tck-runtime.jar
    expire_in: 1 hour

e2e-dsp-tck:
  extends: .base-rules
  stage: test
  allow_failure: true
  variables:
    DISABLE_TCK_FETCH: "true"
  needs:
    - job: dsp-tck-fetch
      artifacts: true
  tags:
    - saas-linux-medium-amd64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: "$CI_COMMIT_TAG"
  script:
    - ls -la tools/e2e-testing/assets
    - wget -q https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb
    - dpkg -i jdk-21_linux-x64_bin.deb > /dev/null
    - pnpm install --frozen-lockfile
    - pnpm build:libs
    - pnpm run --filter control-plane-api build
    - NODE_OPTIONS="--experimental-vm-modules" pnpm e2e:dsp-tck
