image:
  repository: registry.gitlab.com/tno-tsg/dataspace-protocol/tno-security-gateway/http-data-plane
  tag: "v{{ .Chart.Version }}"
replicaCount: 1

host:

resources:
  requests:
    memory: "200Mi"
    cpu: "100m"
  limits:
    memory: "350Mi"
    cpu: "1150m"

serviceAccount:
  create: false

ingress:
  enabled: true
  clusterIssuer: letsencrypt
  paths:
    - path: '{{ template "tsg-core.subPath" $ }}/'
      type: Prefix

env: []
configFromSecrets: {}

subPath: ""

config:
  server:
    port: 3000
    listen: "0.0.0.0"
    publicDomain: "{{ .Values.host }}"
    publicAddress: https://{{ .Values.host }}{{ template "tsg-core.subPath" $ }}
  auth:
    openIdConfigurationURL: "https://{{ .Values.host }}/.well-known/openid-configuration"
    callbackURL: https://{{ .Values.host }}{{ template "tsg-core.subPath" $ }}/api/auth/callback
    redirectURL: https://{{ .Values.host }}{{ template "tsg-core.subPath" $ }}/
    rolePath: "$.roles[*]"
