# host: control-plane-spa.alpha.scsn.dataspac.es

image: docker.nexus.dataspac.es/dsp/control-plane:main
replicaCount: 1

ingress:
  enabled: true
  clusterIssuer: letsencrypt
  path: /control-plane(/|$)(.*)
  rewriteTarget: /$2
  # annotations: {}
  # class: nginx

# env:
#   - name: IAM__CLIENT_ID
#     valueFrom:
#       secretKeyRef:
#         name: wallet-auth
#         key: client-id
#   - name: IAM__CLIENT_SECRET
#     valueFrom:
#       secretKeyRef:
#         name: wallet-auth
#         key: client-secret
#   - name: USERS__0__USERNAME
#     valueFrom:
#       secretKeyRef:
#         name: cp-auth
#         key: username
#   - name: USERS__0__PASSWORD
#     valueFrom:
#       secretKeyRef:
#         name: cp-auth
#         key: password

config:
  server:
    port: 3000
    listen: '0.0.0.0'
    publicDomain: "{{ .Values.host }}"
    publicAddress: https://{{ .Values.host }}/control-plane
  
#   iam:
#     type: tsg
#     didId: did:web:{{ .Values.host }}
#     tokenUrl: https://{{ .Values.host }}/api/auth/login
#     presentationUrl: https://{{ .Values.host }}/api/presentations
#     validationUrl: https://{{ .Values.host }}/api/presentations/validate
#     clientId: # connector
#     clientSecret: # test
#     credentialId: # did:web:{{ .Values.host }}#00000000-0000-0000-0000-000000000000
#     validations:
#     - valid
  
#   users: []
  
#   initCatalog:
#     creator: did:web:{{ .Values.host }}
#     publisher: did:web:{{ .Values.host }}
#     title: TSG Test Connector A
#     description: TSG Test Connector A testing Data Space Protocol support
