import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

import analyticsdataPlaneItems from "./docs/apis/analytics-data-plane/sidebar";
import controlPlaneItems from "./docs/apis/control-plane/sidebar";
import httpdataPlaneItems from "./docs/apis/http-data-plane/sidebar";
import ssoBridgeItems from "./docs/apis/sso-bridge/sidebar";
import walletItems from "./docs/apis/wallet/sidebar";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "README",
    "getting-started",
    {
      type: "category",
      label: "Architecture",
      link: { type: "doc", id: "architecture/README" },
      items: [{ type: "autogenerated", dirName: "architecture" }]
    },
    {
      type: "category",
      label: "Applications",
      link: { type: "doc", id: "apps/README" },
      items: [
        'apps/README',
        {
          type: "category",
          label: "Control Plane",
          link: { type: "doc", id: "apps/control-plane/README" },
          items: [{ type: "autogenerated", dirName: "apps/control-plane" }]
        },
        {
          type: "category",
          label: "Wallet",
          link: { type: "doc", id: "apps/wallet/README" },
          items: [{ type: "autogenerated", dirName: "apps/wallet" }]
        },
        {
          type: "category",
          label: "HTTP Data Plane",
          link: { type: "doc", id: "apps/http-data-plane/README" },
          items: [{ type: "autogenerated", dirName: "apps/http-data-plane" }]
        },
        {
          type: "category",
          label: "Analytics Data Plane",
          link: { type: "doc", id: "apps/analytics-data-plane/README" },
          items: [{ type: "autogenerated", dirName: "apps/analytics-data-plane" }]
        },
        {
          type: "category",
          label: "SSO Bridge",
          link: { type: "doc", id: "apps/sso-bridge/README" },
          items: [{ type: "autogenerated", dirName: "apps/sso-bridge" }]
        }
      ]
    },
    {
      type: "category",
      label: "Deployment",
      link: { type: "doc", id: "deployment/README" },
      items: [{ type: "autogenerated", dirName: "deployment" }]
    },
    {
      type: "category",
      label: "Tools",
      link: { type: "doc", id: "tools/tools" },
      items: [
        'tools/tools',
        {
          type: "category",
          label: "CLI",
          link: { type: "doc", id: "tools/cli/README" },
          items: [
            { type: "autogenerated", dirName: "tools/cli" }
          ]
        }
      ]
    },
    "troubleshooting"
  ],
  controlPlaneSidebar: [
    { type: "category", items: controlPlaneItems, label: "Control Plane" }
  ],
  httpDataPlaneSidebar: [
    { type: "category", items: httpdataPlaneItems, label: "HTTP Data Plane" }
  ],
  analyticsdataPlaneSidebar: [
    { type: "category", items: analyticsdataPlaneItems, label: "Analytics Data Plane" }
  ],
  ssoBridgeSidebar: [{ type: "category", items: ssoBridgeItems, label: "SSO Bridge" },],
  walletSidebar: [{ type: "category", items: walletItems, label: "Wallet" }]
};

export default sidebars;
