import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import controlPlaneItems from "./docs/apis/control-plane/sidebar";
import httpdataPlaneItems from "./docs/apis/http-data-plane/sidebar";
import walletItems from "./docs/apis/wallet/sidebar";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "README",
    { type: "autogenerated", dirName: "apps" },
    { type: "autogenerated", dirName: "deployment" },
    {
      type: "category",
      label: "Tools",
      link: { type: "doc", id: "tools/tools" },
      items: [{ type: "autogenerated", dirName: "tools/cli" }]
    }
  ],
  apiSidebar: [
    { type: "category", items: controlPlaneItems, label: "Control Plane" },
    { type: "category", items: httpdataPlaneItems, label: "HTTP Data Plane" },
    { type: "category", items: walletItems, label: "Wallet" }
  ]
};

export default sidebars;
