image:
  repository: registry.gitlab.com/tno-tsg/dataspace-protocol/tno-security-gateway/wallet
  tag: "v{{ .Chart.Version }}"
replicaCount: 1

casdoor: ""
host:

ingress:
  enabled: true
  clusterIssuer: letsencrypt
  paths:
    - path: '{{ template "tsg.subPath" $ }}/'
      type: Prefix
    - path: /.well-known/did.json
      type: Exact
    - path: /.well-known/did.jsonl
      type: Exact
    - path: /.well-known/openid-credential-issuer
      type: Exact

env: []
configFromSecrets: {}

subPath: ""

config:
  server:
    port: 3000
    listen: "0.0.0.0"
    publicDomain: "{{ .Values.host }}"
    publicAddress: https://{{ .Values.host }}{{ template "tsg.subPath" $ }}
  db:
    type: postgres
    database: wallet
    host: postgresql
    port: 5432
    username: postgres
  auth:
    authorizationURL: https://{{ .Values.casdoor }}/login/oauth/authorize
    tokenURL: https://{{ .Values.casdoor }}/api/login/oauth/access_token
    introspectionURL: https://{{ .Values.casdoor }}/api/login/oauth/introspect
    callbackURL: https://{{ .Values.host }}{{ template "tsg.subPath" $ }}/api/auth/callback
    rolePath: "$.roles[*].name"
    redirectURL: https://{{ .Values.host }}{{ template "tsg.subPath" $ }}/
