import { MigrationInterface, QueryRunner } from "typeorm";

export class Postgres20260202164643 implements MigrationInterface {
    name = 'Postgres20260202164643'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" DROP CONSTRAINT "FK_6fd0401a16eab13575446a07fe7"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP CONSTRAINT "FK_8a7e36dd02b2df21bb2f8924b6a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a7e36dd02b2df21bb2f8924b6"`);
        await queryRunner.query(`ALTER TABLE "data_plane_state_dao" RENAME COLUMN "identifier" TO "id"`);
        await queryRunner.query(`ALTER TABLE "dataset_dao" RENAME COLUMN "identifier" TO "id"`);
        await queryRunner.query(`ALTER TABLE "dataset_dao" RENAME CONSTRAINT "PK_9fb98c8aa63b0528091e714c4a4" TO "PK_68415b58d67b58a56c35d7e2a6e"`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" DROP COLUMN "internalEventsId"`);
        await queryRunner.query(`ALTER TABLE "metadata" DROP CONSTRAINT "PK_8a70e29b7266f31e0ec3a8ec8a5"`);
        // await queryRunner.query(`ALTER TABLE "metadata" DROP COLUMN "identifier"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP CONSTRAINT "PK_ebb68abf8ff87b3d9c92ce9e445"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD CONSTRAINT "PK_367b764fe6c7ac512cd11cad4bb" PRIMARY KEY ("projectAgreementDaoId")`);
        // await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP COLUMN "datasetDaoIdentifier"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" ADD "modifiedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" ADD "deletedDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" ADD "ownerId" character varying`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" ADD "ownerIdentifier" character varying`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" ADD "createdBy" character varying`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" ADD "tenantId" character varying`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" ADD "ownerId" character varying`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" ADD "ownerIdentifier" character varying`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" ADD "createdBy" character varying`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" ADD "tenantId" character varying`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" ADD "modifiedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" ADD "deletedDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" ADD "ownerId" character varying`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" ADD "ownerIdentifier" character varying`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" ADD "createdBy" character varying`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" ADD "tenantId" character varying`);
        await queryRunner.query(`ALTER TABLE "metadata" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "metadata" ADD "modifiedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "metadata" ADD "deletedDate" TIMESTAMP`);
        // await queryRunner.query(`ALTER TABLE "metadata" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "metadata" RENAME COLUMN "identifier" to "id"`);
        await queryRunner.query(`ALTER TABLE "metadata" ADD CONSTRAINT "PK_56b22355e89941b9792c04ab176" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "metadata" ADD "ownerId" character varying`);
        await queryRunner.query(`ALTER TABLE "metadata" ADD "ownerIdentifier" character varying`);
        await queryRunner.query(`ALTER TABLE "metadata" ADD "createdBy" character varying`);
        await queryRunner.query(`ALTER TABLE "metadata" ADD "tenantId" character varying`);
        // await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD "datasetDaoId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" RENAME COLUMN "datasetDaoIdentifier" to "datasetDaoId"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP CONSTRAINT "PK_367b764fe6c7ac512cd11cad4bb"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD CONSTRAINT "PK_94445d80ffb4db148d067a55957" PRIMARY KEY ("projectAgreementDaoId", "datasetDaoId")`);
        await queryRunner.query(`ALTER TABLE "project_agreement_callback_dao" DROP CONSTRAINT "FK_e48050e64558c7a44fe5f086915"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP CONSTRAINT "FK_367b764fe6c7ac512cd11cad4bb"`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" DROP CONSTRAINT "FK_e16dc2433aa04af491c0def4571"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" DROP CONSTRAINT "PK_b15ea544513a08d9e406e672c79"`);
        // await queryRunner.query(`ALTER TABLE "project_agreement_dao" DROP COLUMN "id"`);
        // await queryRunner.query(`ALTER TABLE "project_agreement_dao" ADD "id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" ALTER COLUMN "id" SET DATA TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" ADD CONSTRAINT "PK_b15ea544513a08d9e406e672c79" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "project_agreement_callback_dao" DROP COLUMN "projectAgreementId"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_callback_dao" ADD "projectAgreementId" character varying`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" DROP COLUMN "modifiedDate"`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" ADD "modifiedDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" DROP COLUMN "deletedDate"`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" ADD "deletedDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" ADD "createdDate" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" DROP COLUMN "projectAgreementId"`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" ADD "projectAgreementId" character varying`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP CONSTRAINT "PK_94445d80ffb4db148d067a55957"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD CONSTRAINT "PK_eaaf8254752b30a470c544a1df8" PRIMARY KEY ("datasetDaoId")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_367b764fe6c7ac512cd11cad4b"`);
        // await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP COLUMN "projectAgreementDaoId"`);
        // await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD "projectAgreementDaoId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ALTER COLUMN "projectAgreementDaoId" SET DATA TYPE character varying`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP CONSTRAINT "PK_eaaf8254752b30a470c544a1df8"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD CONSTRAINT "PK_94445d80ffb4db148d067a55957" PRIMARY KEY ("datasetDaoId", "projectAgreementDaoId")`);
        await queryRunner.query(`CREATE INDEX "IDX_367b764fe6c7ac512cd11cad4b" ON "project_agreement_dao_datasets_dataset_dao" ("projectAgreementDaoId") `);
        await queryRunner.query(`CREATE INDEX "IDX_eaaf8254752b30a470c544a1df" ON "project_agreement_dao_datasets_dataset_dao" ("datasetDaoId") `);
        await queryRunner.query(`ALTER TABLE "project_agreement_callback_dao" ADD CONSTRAINT "FK_e48050e64558c7a44fe5f086915" FOREIGN KEY ("projectAgreementId") REFERENCES "project_agreement_dao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" ADD CONSTRAINT "FK_e16dc2433aa04af491c0def4571" FOREIGN KEY ("projectAgreementId") REFERENCES "project_agreement_dao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD CONSTRAINT "FK_367b764fe6c7ac512cd11cad4bb" FOREIGN KEY ("projectAgreementDaoId") REFERENCES "project_agreement_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD CONSTRAINT "FK_eaaf8254752b30a470c544a1df8" FOREIGN KEY ("datasetDaoId") REFERENCES "dataset_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);

        await queryRunner.query(`ALTER TABLE "project_agreement_callback_dao" DROP CONSTRAINT "FK_e48050e64558c7a44fe5f086915"`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" DROP CONSTRAINT "FK_e16dc2433aa04af491c0def4571"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP CONSTRAINT "FK_367b764fe6c7ac512cd11cad4bb"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "project_agreement_dao_id_seq"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_callback_dao" ADD CONSTRAINT "FK_e48050e64558c7a44fe5f086915" FOREIGN KEY ("projectAgreementId") REFERENCES "project_agreement_dao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" ADD CONSTRAINT "FK_e16dc2433aa04af491c0def4571" FOREIGN KEY ("projectAgreementId") REFERENCES "project_agreement_dao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD CONSTRAINT "FK_367b764fe6c7ac512cd11cad4bb" FOREIGN KEY ("projectAgreementDaoId") REFERENCES "project_agreement_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP CONSTRAINT "FK_eaaf8254752b30a470c544a1df8"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP CONSTRAINT "FK_367b764fe6c7ac512cd11cad4bb"`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" DROP CONSTRAINT "FK_e16dc2433aa04af491c0def4571"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_callback_dao" DROP CONSTRAINT "FK_e48050e64558c7a44fe5f086915"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eaaf8254752b30a470c544a1df"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_367b764fe6c7ac512cd11cad4b"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP CONSTRAINT "PK_94445d80ffb4db148d067a55957"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD CONSTRAINT "PK_eaaf8254752b30a470c544a1df8" PRIMARY KEY ("datasetDaoId")`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP COLUMN "projectAgreementDaoId"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD "projectAgreementDaoId" integer NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_367b764fe6c7ac512cd11cad4b" ON "project_agreement_dao_datasets_dataset_dao" ("projectAgreementDaoId") `);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP CONSTRAINT "PK_eaaf8254752b30a470c544a1df8"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD CONSTRAINT "PK_94445d80ffb4db148d067a55957" PRIMARY KEY ("projectAgreementDaoId", "datasetDaoId")`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" DROP COLUMN "projectAgreementId"`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" ADD "projectAgreementId" integer`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" ADD "createdDate" character varying NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" DROP COLUMN "deletedDate"`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" ADD "deletedDate" character varying`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" DROP COLUMN "modifiedDate"`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" ADD "modifiedDate" character varying NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" ADD "createdDate" character varying NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "project_agreement_callback_dao" DROP COLUMN "projectAgreementId"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_callback_dao" ADD "projectAgreementId" integer`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" DROP CONSTRAINT "PK_b15ea544513a08d9e406e672c79"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" ADD CONSTRAINT "PK_b15ea544513a08d9e406e672c79" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" ADD CONSTRAINT "FK_e16dc2433aa04af491c0def4571" FOREIGN KEY ("projectAgreementId") REFERENCES "project_agreement_dao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD CONSTRAINT "FK_367b764fe6c7ac512cd11cad4bb" FOREIGN KEY ("projectAgreementDaoId") REFERENCES "project_agreement_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "project_agreement_callback_dao" ADD CONSTRAINT "FK_e48050e64558c7a44fe5f086915" FOREIGN KEY ("projectAgreementId") REFERENCES "project_agreement_dao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP CONSTRAINT "PK_94445d80ffb4db148d067a55957"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD CONSTRAINT "PK_367b764fe6c7ac512cd11cad4bb" PRIMARY KEY ("projectAgreementDaoId")`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP COLUMN "datasetDaoId"`);
        await queryRunner.query(`ALTER TABLE "metadata" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "metadata" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "metadata" DROP COLUMN "ownerIdentifier"`);
        await queryRunner.query(`ALTER TABLE "metadata" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "metadata" DROP CONSTRAINT "PK_56b22355e89941b9792c04ab176"`);
        await queryRunner.query(`ALTER TABLE "metadata" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "metadata" DROP COLUMN "deletedDate"`);
        await queryRunner.query(`ALTER TABLE "metadata" DROP COLUMN "modifiedDate"`);
        await queryRunner.query(`ALTER TABLE "metadata" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" DROP COLUMN "ownerIdentifier"`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" DROP COLUMN "deletedDate"`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" DROP COLUMN "modifiedDate"`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" DROP COLUMN "ownerIdentifier"`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" DROP COLUMN "tenantId"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" DROP COLUMN "ownerIdentifier"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" DROP COLUMN "ownerId"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" DROP COLUMN "deletedDate"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" DROP COLUMN "modifiedDate"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" DROP COLUMN "createdDate"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD "datasetDaoIdentifier" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP CONSTRAINT "PK_367b764fe6c7ac512cd11cad4bb"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD CONSTRAINT "PK_ebb68abf8ff87b3d9c92ce9e445" PRIMARY KEY ("projectAgreementDaoId", "datasetDaoIdentifier")`);
        await queryRunner.query(`ALTER TABLE "metadata" ADD "identifier" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "metadata" ADD CONSTRAINT "PK_8a70e29b7266f31e0ec3a8ec8a5" PRIMARY KEY ("identifier")`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" ADD "internalEventsId" character varying`);
        await queryRunner.query(`ALTER TABLE "dataset_dao" RENAME CONSTRAINT "PK_68415b58d67b58a56c35d7e2a6e" TO "PK_9fb98c8aa63b0528091e714c4a4"`);
        await queryRunner.query(`ALTER TABLE "dataset_dao" RENAME COLUMN "id" TO "identifier"`);
        await queryRunner.query(`ALTER TABLE "data_plane_state_dao" RENAME COLUMN "id" TO "identifier"`);
        await queryRunner.query(`CREATE INDEX "IDX_8a7e36dd02b2df21bb2f8924b6" ON "project_agreement_dao_datasets_dataset_dao" ("datasetDaoIdentifier") `);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD CONSTRAINT "FK_8a7e36dd02b2df21bb2f8924b6a" FOREIGN KEY ("datasetDaoIdentifier") REFERENCES "dataset_dao"("identifier") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" ADD CONSTRAINT "FK_6fd0401a16eab13575446a07fe7" FOREIGN KEY ("internalEventsId") REFERENCES "internal_event_dao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" DROP CONSTRAINT "FK_367b764fe6c7ac512cd11cad4bb"`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" DROP CONSTRAINT "FK_e16dc2433aa04af491c0def4571"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_callback_dao" DROP CONSTRAINT "FK_e48050e64558c7a44fe5f086915"`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "project_agreement_dao_id_seq" OWNED BY "project_agreement_dao"."id"`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao" ALTER COLUMN "id" SET DEFAULT nextval('"project_agreement_dao_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "project_agreement_dao_datasets_dataset_dao" ADD CONSTRAINT "FK_367b764fe6c7ac512cd11cad4bb" FOREIGN KEY ("projectAgreementDaoId") REFERENCES "project_agreement_dao"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "algorithm_instance_dao" ADD CONSTRAINT "FK_e16dc2433aa04af491c0def4571" FOREIGN KEY ("projectAgreementId") REFERENCES "project_agreement_dao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_agreement_callback_dao" ADD CONSTRAINT "FK_e48050e64558c7a44fe5f086915" FOREIGN KEY ("projectAgreementId") REFERENCES "project_agreement_dao"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
