import { MigrationInterface, QueryRunner } from "typeorm";

export class Sqlite20260225084110 implements MigrationInterface {
    name = 'Sqlite20260225084110'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_transfer_dao" ("id" varchar PRIMARY KEY NOT NULL, "role" varchar NOT NULL, "processId" varchar NOT NULL, "remoteParty" varchar NOT NULL, "datasetId" varchar NOT NULL, "secret" varchar, "state" varchar CHECK( "state" IN ('REQUESTED','STARTED','TERMINATED','COMPLETED','SUSPENDED') ) NOT NULL, "request" text NOT NULL, "response" text NOT NULL, "dataAddress" text, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "algorithmInstanceId" varchar, "ownerId" varchar, "ownerIdentifier" varchar, "createdBy" varchar, "tenantId" varchar)`);
        await queryRunner.query(`INSERT INTO "temporary_transfer_dao"("id", "role", "processId", "remoteParty", "datasetId", "secret", "state", "request", "response", "dataAddress", "createdDate", "modifiedDate", "deletedDate", "algorithmInstanceId", "ownerId", "ownerIdentifier", "createdBy", "tenantId") SELECT "id", "role", "processId", "remoteParty", "datasetId", "secret", "state", "request", "response", "dataAddress", "createdDate", "modifiedDate", "deletedDate", "algorithmInstanceId", "ownerId", "ownerIdentifier", "createdBy", "tenantId" FROM "transfer_dao"`);
        await queryRunner.query(`DROP TABLE "transfer_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_transfer_dao" RENAME TO "transfer_dao"`);
        await queryRunner.query(`CREATE TABLE "temporary_internal_event_dao" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "number" integer NOT NULL, "timestamp" datetime NOT NULL, "data" text, "algorithmInstanceId" varchar)`);
        await queryRunner.query(`INSERT INTO "temporary_internal_event_dao"("id", "name", "number", "timestamp", "data", "algorithmInstanceId") SELECT "id", "name", "number", "timestamp", "data", "algorithmInstanceId" FROM "internal_event_dao"`);
        await queryRunner.query(`DROP TABLE "internal_event_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_internal_event_dao" RENAME TO "internal_event_dao"`);
        await queryRunner.query(`CREATE TABLE "temporary_algorithm_event_dao" ("id" varchar PRIMARY KEY NOT NULL, "eventId" varchar NOT NULL, "name" varchar NOT NULL, "number" integer NOT NULL, "timestamp" datetime NOT NULL, "data" blob, "isOwnEvent" boolean NOT NULL, "transferIds" text, "createdBy" varchar NOT NULL, "recipients" text, "algorithmInstanceId" varchar, CONSTRAINT "UQ_ef52d34206bc1c0b8476ddc1e6f" UNIQUE ("eventId"))`);
        await queryRunner.query(`INSERT INTO "temporary_algorithm_event_dao"("id", "eventId", "name", "number", "timestamp", "data", "isOwnEvent", "transferIds", "createdBy", "recipients", "algorithmInstanceId") SELECT "id", "eventId", "name", "number", "timestamp", "data", "isOwnEvent", "transferIds", "createdBy", "recipients", "algorithmInstanceId" FROM "algorithm_event_dao"`);
        await queryRunner.query(`DROP TABLE "algorithm_event_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_algorithm_event_dao" RENAME TO "algorithm_event_dao"`);
        await queryRunner.query(`CREATE TABLE "temporary_transfer_dao" ("id" varchar PRIMARY KEY NOT NULL, "role" varchar NOT NULL, "processId" varchar NOT NULL, "remoteParty" varchar NOT NULL, "datasetId" varchar NOT NULL, "secret" varchar, "state" varchar CHECK( "state" IN ('REQUESTED','STARTED','TERMINATED','COMPLETED','SUSPENDED') ) NOT NULL, "request" text NOT NULL, "response" text NOT NULL, "dataAddress" text, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "algorithmInstanceId" varchar, "ownerId" varchar, "ownerIdentifier" varchar, "createdBy" varchar, "tenantId" varchar, CONSTRAINT "FK_2cc4970e567c420b556cb2233e3" FOREIGN KEY ("algorithmInstanceId") REFERENCES "algorithm_instance_dao" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_transfer_dao"("id", "role", "processId", "remoteParty", "datasetId", "secret", "state", "request", "response", "dataAddress", "createdDate", "modifiedDate", "deletedDate", "algorithmInstanceId", "ownerId", "ownerIdentifier", "createdBy", "tenantId") SELECT "id", "role", "processId", "remoteParty", "datasetId", "secret", "state", "request", "response", "dataAddress", "createdDate", "modifiedDate", "deletedDate", "algorithmInstanceId", "ownerId", "ownerIdentifier", "createdBy", "tenantId" FROM "transfer_dao"`);
        await queryRunner.query(`DROP TABLE "transfer_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_transfer_dao" RENAME TO "transfer_dao"`);
        await queryRunner.query(`CREATE TABLE "temporary_internal_event_dao" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "number" integer NOT NULL, "timestamp" datetime NOT NULL, "data" text, "algorithmInstanceId" varchar, CONSTRAINT "FK_dd10057fa4d11c49cad9b3ff203" FOREIGN KEY ("algorithmInstanceId") REFERENCES "algorithm_instance_dao" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_internal_event_dao"("id", "name", "number", "timestamp", "data", "algorithmInstanceId") SELECT "id", "name", "number", "timestamp", "data", "algorithmInstanceId" FROM "internal_event_dao"`);
        await queryRunner.query(`DROP TABLE "internal_event_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_internal_event_dao" RENAME TO "internal_event_dao"`);
        await queryRunner.query(`CREATE TABLE "temporary_algorithm_event_dao" ("id" varchar PRIMARY KEY NOT NULL, "eventId" varchar NOT NULL, "name" varchar NOT NULL, "number" integer NOT NULL, "timestamp" datetime NOT NULL, "data" blob, "isOwnEvent" boolean NOT NULL, "transferIds" text, "createdBy" varchar NOT NULL, "recipients" text, "algorithmInstanceId" varchar, CONSTRAINT "UQ_ef52d34206bc1c0b8476ddc1e6f" UNIQUE ("eventId"), CONSTRAINT "FK_0a76821e01c305c8cc15c6a0a58" FOREIGN KEY ("algorithmInstanceId") REFERENCES "algorithm_instance_dao" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_algorithm_event_dao"("id", "eventId", "name", "number", "timestamp", "data", "isOwnEvent", "transferIds", "createdBy", "recipients", "algorithmInstanceId") SELECT "id", "eventId", "name", "number", "timestamp", "data", "isOwnEvent", "transferIds", "createdBy", "recipients", "algorithmInstanceId" FROM "algorithm_event_dao"`);
        await queryRunner.query(`DROP TABLE "algorithm_event_dao"`);
        await queryRunner.query(`ALTER TABLE "temporary_algorithm_event_dao" RENAME TO "algorithm_event_dao"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "algorithm_event_dao" RENAME TO "temporary_algorithm_event_dao"`);
        await queryRunner.query(`CREATE TABLE "algorithm_event_dao" ("id" varchar PRIMARY KEY NOT NULL, "eventId" varchar NOT NULL, "name" varchar NOT NULL, "number" integer NOT NULL, "timestamp" datetime NOT NULL, "data" blob, "isOwnEvent" boolean NOT NULL, "transferIds" text, "createdBy" varchar NOT NULL, "recipients" text, "algorithmInstanceId" varchar, CONSTRAINT "UQ_ef52d34206bc1c0b8476ddc1e6f" UNIQUE ("eventId"))`);
        await queryRunner.query(`INSERT INTO "algorithm_event_dao"("id", "eventId", "name", "number", "timestamp", "data", "isOwnEvent", "transferIds", "createdBy", "recipients", "algorithmInstanceId") SELECT "id", "eventId", "name", "number", "timestamp", "data", "isOwnEvent", "transferIds", "createdBy", "recipients", "algorithmInstanceId" FROM "temporary_algorithm_event_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_algorithm_event_dao"`);
        await queryRunner.query(`ALTER TABLE "internal_event_dao" RENAME TO "temporary_internal_event_dao"`);
        await queryRunner.query(`CREATE TABLE "internal_event_dao" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "number" integer NOT NULL, "timestamp" datetime NOT NULL, "data" text, "algorithmInstanceId" varchar)`);
        await queryRunner.query(`INSERT INTO "internal_event_dao"("id", "name", "number", "timestamp", "data", "algorithmInstanceId") SELECT "id", "name", "number", "timestamp", "data", "algorithmInstanceId" FROM "temporary_internal_event_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_internal_event_dao"`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" RENAME TO "temporary_transfer_dao"`);
        await queryRunner.query(`CREATE TABLE "transfer_dao" ("id" varchar PRIMARY KEY NOT NULL, "role" varchar NOT NULL, "processId" varchar NOT NULL, "remoteParty" varchar NOT NULL, "datasetId" varchar NOT NULL, "secret" varchar, "state" varchar CHECK( "state" IN ('REQUESTED','STARTED','TERMINATED','COMPLETED','SUSPENDED') ) NOT NULL, "request" text NOT NULL, "response" text NOT NULL, "dataAddress" text, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "algorithmInstanceId" varchar, "ownerId" varchar, "ownerIdentifier" varchar, "createdBy" varchar, "tenantId" varchar)`);
        await queryRunner.query(`INSERT INTO "transfer_dao"("id", "role", "processId", "remoteParty", "datasetId", "secret", "state", "request", "response", "dataAddress", "createdDate", "modifiedDate", "deletedDate", "algorithmInstanceId", "ownerId", "ownerIdentifier", "createdBy", "tenantId") SELECT "id", "role", "processId", "remoteParty", "datasetId", "secret", "state", "request", "response", "dataAddress", "createdDate", "modifiedDate", "deletedDate", "algorithmInstanceId", "ownerId", "ownerIdentifier", "createdBy", "tenantId" FROM "temporary_transfer_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_transfer_dao"`);
        await queryRunner.query(`ALTER TABLE "algorithm_event_dao" RENAME TO "temporary_algorithm_event_dao"`);
        await queryRunner.query(`CREATE TABLE "algorithm_event_dao" ("id" varchar PRIMARY KEY NOT NULL, "eventId" varchar NOT NULL, "name" varchar NOT NULL, "number" integer NOT NULL, "timestamp" datetime NOT NULL, "data" blob, "isOwnEvent" boolean NOT NULL, "transferIds" text, "createdBy" varchar NOT NULL, "recipients" text, "algorithmInstanceId" varchar, CONSTRAINT "UQ_ef52d34206bc1c0b8476ddc1e6f" UNIQUE ("eventId"), CONSTRAINT "FK_0a76821e01c305c8cc15c6a0a58" FOREIGN KEY ("algorithmInstanceId") REFERENCES "algorithm_instance_dao" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "algorithm_event_dao"("id", "eventId", "name", "number", "timestamp", "data", "isOwnEvent", "transferIds", "createdBy", "recipients", "algorithmInstanceId") SELECT "id", "eventId", "name", "number", "timestamp", "data", "isOwnEvent", "transferIds", "createdBy", "recipients", "algorithmInstanceId" FROM "temporary_algorithm_event_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_algorithm_event_dao"`);
        await queryRunner.query(`ALTER TABLE "internal_event_dao" RENAME TO "temporary_internal_event_dao"`);
        await queryRunner.query(`CREATE TABLE "internal_event_dao" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "number" integer NOT NULL, "timestamp" datetime NOT NULL, "data" text, "algorithmInstanceId" varchar, CONSTRAINT "FK_dd10057fa4d11c49cad9b3ff203" FOREIGN KEY ("algorithmInstanceId") REFERENCES "algorithm_instance_dao" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "internal_event_dao"("id", "name", "number", "timestamp", "data", "algorithmInstanceId") SELECT "id", "name", "number", "timestamp", "data", "algorithmInstanceId" FROM "temporary_internal_event_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_internal_event_dao"`);
        await queryRunner.query(`ALTER TABLE "transfer_dao" RENAME TO "temporary_transfer_dao"`);
        await queryRunner.query(`CREATE TABLE "transfer_dao" ("id" varchar PRIMARY KEY NOT NULL, "role" varchar NOT NULL, "processId" varchar NOT NULL, "remoteParty" varchar NOT NULL, "datasetId" varchar NOT NULL, "secret" varchar, "state" varchar CHECK( "state" IN ('REQUESTED','STARTED','TERMINATED','COMPLETED','SUSPENDED') ) NOT NULL, "request" text NOT NULL, "response" text NOT NULL, "dataAddress" text, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "modifiedDate" datetime NOT NULL DEFAULT (datetime('now')), "deletedDate" datetime, "algorithmInstanceId" varchar, "ownerId" varchar, "ownerIdentifier" varchar, "createdBy" varchar, "tenantId" varchar, CONSTRAINT "FK_2cc4970e567c420b556cb2233e3" FOREIGN KEY ("algorithmInstanceId") REFERENCES "algorithm_instance_dao" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "transfer_dao"("id", "role", "processId", "remoteParty", "datasetId", "secret", "state", "request", "response", "dataAddress", "createdDate", "modifiedDate", "deletedDate", "algorithmInstanceId", "ownerId", "ownerIdentifier", "createdBy", "tenantId") SELECT "id", "role", "processId", "remoteParty", "datasetId", "secret", "state", "request", "response", "dataAddress", "createdDate", "modifiedDate", "deletedDate", "algorithmInstanceId", "ownerId", "ownerIdentifier", "createdBy", "tenantId" FROM "temporary_transfer_dao"`);
        await queryRunner.query(`DROP TABLE "temporary_transfer_dao"`);
    }

}
